//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// LINT: LEGACY_NAMES

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/annotation.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Map entry from AnnotationSpec ID to AnnotationValue.
type AnnotationProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key for the map entry.
	Id *int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Value of the map entry.
	Value         *SimpleValueProto `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationProto) Reset() {
	*x = AnnotationProto{}
	mi := &file_googlesql_public_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationProto) ProtoMessage() {}

func (x *AnnotationProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationProto.ProtoReflect.Descriptor instead.
func (*AnnotationProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_annotation_proto_rawDescGZIP(), []int{0}
}

func (x *AnnotationProto) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AnnotationProto) GetValue() *SimpleValueProto {
	if x != nil {
		return x.Value
	}
	return nil
}

// This represents the serialized form of the annotation map for
// googlesql::AnnotatedType.
type AnnotationMapProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates that an element of array or a field of struct is null. In
	// ArrayAnnotationMap and StructAnnotationMap class, a null element/field
	// indicates that the AnnotationMap for the element/field (and all its
	// children if applicable) is empty.
	// <is_null> can only be true for struct field or array element, or an error
	// is throw during deserialization. If <is_null> is true, the rest of this
	// proto is ignored.
	IsNull      *bool              `protobuf:"varint,4,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	Annotations []*AnnotationProto `protobuf:"bytes,1,rep,name=annotations" json:"annotations,omitempty"`
	// If AnnotatedType is a complex type, then exactly one of the two
	// fields will be populated (and after the transition, only `struct_fields`
	// will be populated).
	// `array_element` is deprecated. Please use `struct_fields` instead.
	//
	// Deprecated: Marked as deprecated in googlesql/public/annotation.proto.
	ArrayElement  *AnnotationMapProto   `protobuf:"bytes,2,opt,name=array_element,json=arrayElement" json:"array_element,omitempty"`
	StructFields  []*AnnotationMapProto `protobuf:"bytes,3,rep,name=struct_fields,json=structFields" json:"struct_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationMapProto) Reset() {
	*x = AnnotationMapProto{}
	mi := &file_googlesql_public_annotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationMapProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationMapProto) ProtoMessage() {}

func (x *AnnotationMapProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_annotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationMapProto.ProtoReflect.Descriptor instead.
func (*AnnotationMapProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_annotation_proto_rawDescGZIP(), []int{1}
}

func (x *AnnotationMapProto) GetIsNull() bool {
	if x != nil && x.IsNull != nil {
		return *x.IsNull
	}
	return false
}

func (x *AnnotationMapProto) GetAnnotations() []*AnnotationProto {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// Deprecated: Marked as deprecated in googlesql/public/annotation.proto.
func (x *AnnotationMapProto) GetArrayElement() *AnnotationMapProto {
	if x != nil {
		return x.ArrayElement
	}
	return nil
}

func (x *AnnotationMapProto) GetStructFields() []*AnnotationMapProto {
	if x != nil {
		return x.StructFields
	}
	return nil
}

var File_googlesql_public_annotation_proto protoreflect.FileDescriptor

const file_googlesql_public_annotation_proto_rawDesc = "" +
	"\n" +
	"!googlesql/public/annotation.proto\x12\tgooglesql\x1a#googlesql/public/simple_value.proto\"T\n" +
	"\x0fAnnotationProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.googlesql.SimpleValueProtoR\x05value\"\xf7\x01\n" +
	"\x12AnnotationMapProto\x12\x17\n" +
	"\ais_null\x18\x04 \x01(\bR\x06isNull\x12<\n" +
	"\vannotations\x18\x01 \x03(\v2\x1a.googlesql.AnnotationProtoR\vannotations\x12F\n" +
	"\rarray_element\x18\x02 \x01(\v2\x1d.googlesql.AnnotationMapProtoB\x02\x18\x01R\farrayElement\x12B\n" +
	"\rstruct_fields\x18\x03 \x03(\v2\x1d.googlesql.AnnotationMapProtoR\fstructFieldsB.\n" +
	"\x14com.google.googlesqlB\x13GoogleSQLAnnotation\xf8\x01\x01"

var (
	file_googlesql_public_annotation_proto_rawDescOnce sync.Once
	file_googlesql_public_annotation_proto_rawDescData []byte
)

func file_googlesql_public_annotation_proto_rawDescGZIP() []byte {
	file_googlesql_public_annotation_proto_rawDescOnce.Do(func() {
		file_googlesql_public_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_annotation_proto_rawDesc), len(file_googlesql_public_annotation_proto_rawDesc)))
	})
	return file_googlesql_public_annotation_proto_rawDescData
}

var file_googlesql_public_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_googlesql_public_annotation_proto_goTypes = []any{
	(*AnnotationProto)(nil),    // 0: googlesql.AnnotationProto
	(*AnnotationMapProto)(nil), // 1: googlesql.AnnotationMapProto
	(*SimpleValueProto)(nil),   // 2: googlesql.SimpleValueProto
}
var file_googlesql_public_annotation_proto_depIdxs = []int32{
	2, // 0: googlesql.AnnotationProto.value:type_name -> googlesql.SimpleValueProto
	0, // 1: googlesql.AnnotationMapProto.annotations:type_name -> googlesql.AnnotationProto
	1, // 2: googlesql.AnnotationMapProto.array_element:type_name -> googlesql.AnnotationMapProto
	1, // 3: googlesql.AnnotationMapProto.struct_fields:type_name -> googlesql.AnnotationMapProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_googlesql_public_annotation_proto_init() }
func file_googlesql_public_annotation_proto_init() {
	if File_googlesql_public_annotation_proto != nil {
		return
	}
	file_googlesql_public_simple_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_annotation_proto_rawDesc), len(file_googlesql_public_annotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_annotation_proto_goTypes,
		DependencyIndexes: file_googlesql_public_annotation_proto_depIdxs,
		MessageInfos:      file_googlesql_public_annotation_proto_msgTypes,
	}.Build()
	File_googlesql_public_annotation_proto = out.File
	file_googlesql_public_annotation_proto_goTypes = nil
	file_googlesql_public_annotation_proto_depIdxs = nil
}
