//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file contains the constness levels defined by GoogleSQL.
// See (broken link) for more details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/constness_level.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConstnessLevelProto_Level int32

const (
	// Unspecified constness level.
	ConstnessLevelProto_CONSTNESS_UNSPECIFIED ConstnessLevelProto_Level = 0
	ConstnessLevelProto_FOREVER_CONST         ConstnessLevelProto_Level = 1
	ConstnessLevelProto_ANALYSIS_CONST        ConstnessLevelProto_Level = 2
	ConstnessLevelProto_IMMUTABLE_CONST       ConstnessLevelProto_Level = 3
	// TODO: b/277365877 - Deprecate the legacy constness level.
	// Currently, this means the argument must be a literal or parameter.
	// This is the serialization for FunctionArgumentType::must_be_constant().
	ConstnessLevelProto_LEGACY_LITERAL_OR_PARAMETER ConstnessLevelProto_Level = 1000
	// TODO: b/277365877 - Deprecate the legacy constness level.
	// The rules of classifying expression as this level are:
	//   - literals and parameters are constant
	//   - column references are not constant
	//   - correlated column references
	//   - scalar functions are constant if FunctionOptions::volatility is
	//     IMMUTABLE or STABLE, and if all arguments are constant
	//   - aggregate and analytic functions are not constant
	//   - DDL CONSTANTs
	//   - expression subqueries are not constant
	//   - built-in operators like CAST and CASE and struct field access are
	//     constant if all arguments are constant
	//   - UDF argument references
	//
	// This is the serialization for
	// FunctionArgumentType::must_be_constant_expression().
	ConstnessLevelProto_LEGACY_CONSTANT_EXPRESSION ConstnessLevelProto_Level = 1001
)

// Enum value maps for ConstnessLevelProto_Level.
var (
	ConstnessLevelProto_Level_name = map[int32]string{
		0:    "CONSTNESS_UNSPECIFIED",
		1:    "FOREVER_CONST",
		2:    "ANALYSIS_CONST",
		3:    "IMMUTABLE_CONST",
		1000: "LEGACY_LITERAL_OR_PARAMETER",
		1001: "LEGACY_CONSTANT_EXPRESSION",
	}
	ConstnessLevelProto_Level_value = map[string]int32{
		"CONSTNESS_UNSPECIFIED":       0,
		"FOREVER_CONST":               1,
		"ANALYSIS_CONST":              2,
		"IMMUTABLE_CONST":             3,
		"LEGACY_LITERAL_OR_PARAMETER": 1000,
		"LEGACY_CONSTANT_EXPRESSION":  1001,
	}
)

func (x ConstnessLevelProto_Level) Enum() *ConstnessLevelProto_Level {
	p := new(ConstnessLevelProto_Level)
	*p = x
	return p
}

func (x ConstnessLevelProto_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstnessLevelProto_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_constness_level_proto_enumTypes[0].Descriptor()
}

func (ConstnessLevelProto_Level) Type() protoreflect.EnumType {
	return &file_googlesql_public_constness_level_proto_enumTypes[0]
}

func (x ConstnessLevelProto_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ConstnessLevelProto_Level) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ConstnessLevelProto_Level(num)
	return nil
}

// Deprecated: Use ConstnessLevelProto_Level.Descriptor instead.
func (ConstnessLevelProto_Level) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_constness_level_proto_rawDescGZIP(), []int{0, 0}
}

type ConstnessLevelProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstnessLevelProto) Reset() {
	*x = ConstnessLevelProto{}
	mi := &file_googlesql_public_constness_level_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstnessLevelProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstnessLevelProto) ProtoMessage() {}

func (x *ConstnessLevelProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_constness_level_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstnessLevelProto.ProtoReflect.Descriptor instead.
func (*ConstnessLevelProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_constness_level_proto_rawDescGZIP(), []int{0}
}

var File_googlesql_public_constness_level_proto protoreflect.FileDescriptor

const file_googlesql_public_constness_level_proto_rawDesc = "" +
	"\n" +
	"&googlesql/public/constness_level.proto\x12\tgooglesql\"\xb9\x01\n" +
	"\x13ConstnessLevelProto\"\xa1\x01\n" +
	"\x05Level\x12\x19\n" +
	"\x15CONSTNESS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rFOREVER_CONST\x10\x01\x12\x12\n" +
	"\x0eANALYSIS_CONST\x10\x02\x12\x13\n" +
	"\x0fIMMUTABLE_CONST\x10\x03\x12 \n" +
	"\x1bLEGACY_LITERAL_OR_PARAMETER\x10\xe8\a\x12\x1f\n" +
	"\x1aLEGACY_CONSTANT_EXPRESSION\x10\xe9\aB.\n" +
	"\x14com.google.googlesqlB\x14ConstnessLevelProtosP\x01"

var (
	file_googlesql_public_constness_level_proto_rawDescOnce sync.Once
	file_googlesql_public_constness_level_proto_rawDescData []byte
)

func file_googlesql_public_constness_level_proto_rawDescGZIP() []byte {
	file_googlesql_public_constness_level_proto_rawDescOnce.Do(func() {
		file_googlesql_public_constness_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_constness_level_proto_rawDesc), len(file_googlesql_public_constness_level_proto_rawDesc)))
	})
	return file_googlesql_public_constness_level_proto_rawDescData
}

var file_googlesql_public_constness_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_googlesql_public_constness_level_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_googlesql_public_constness_level_proto_goTypes = []any{
	(ConstnessLevelProto_Level)(0), // 0: googlesql.ConstnessLevelProto.Level
	(*ConstnessLevelProto)(nil),    // 1: googlesql.ConstnessLevelProto
}
var file_googlesql_public_constness_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_constness_level_proto_init() }
func file_googlesql_public_constness_level_proto_init() {
	if File_googlesql_public_constness_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_constness_level_proto_rawDesc), len(file_googlesql_public_constness_level_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_constness_level_proto_goTypes,
		DependencyIndexes: file_googlesql_public_constness_level_proto_depIdxs,
		EnumInfos:         file_googlesql_public_constness_level_proto_enumTypes,
		MessageInfos:      file_googlesql_public_constness_level_proto_msgTypes,
	}.Build()
	File_googlesql_public_constness_level_proto = out.File
	file_googlesql_public_constness_level_proto_goTypes = nil
	file_googlesql_public_constness_level_proto_depIdxs = nil
}
