//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/feature_label_dictionary.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureLabelDictionaryProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoding map representing integer codes and their corresponding
	// feature labels.
	LabelMapping map[int32]string `protobuf:"bytes,1,rep,name=label_mapping,json=labelMapping" json:"label_mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Mapping of user supplied query id to set of encoded labels for that query.
	EncodedLabels map[int32]*FeatureLabelDictionaryProto_LabelSet `protobuf:"bytes,2,rep,name=encoded_labels,json=encodedLabels" json:"encoded_labels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureLabelDictionaryProto) Reset() {
	*x = FeatureLabelDictionaryProto{}
	mi := &file_googlesql_public_feature_label_dictionary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureLabelDictionaryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureLabelDictionaryProto) ProtoMessage() {}

func (x *FeatureLabelDictionaryProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_feature_label_dictionary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureLabelDictionaryProto.ProtoReflect.Descriptor instead.
func (*FeatureLabelDictionaryProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_feature_label_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureLabelDictionaryProto) GetLabelMapping() map[int32]string {
	if x != nil {
		return x.LabelMapping
	}
	return nil
}

func (x *FeatureLabelDictionaryProto) GetEncodedLabels() map[int32]*FeatureLabelDictionaryProto_LabelSet {
	if x != nil {
		return x.EncodedLabels
	}
	return nil
}

// Represents a set of encoded feature labels associated with a single query.
type FeatureLabelDictionaryProto_LabelSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         []int32                `protobuf:"varint,1,rep,packed,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureLabelDictionaryProto_LabelSet) Reset() {
	*x = FeatureLabelDictionaryProto_LabelSet{}
	mi := &file_googlesql_public_feature_label_dictionary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureLabelDictionaryProto_LabelSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureLabelDictionaryProto_LabelSet) ProtoMessage() {}

func (x *FeatureLabelDictionaryProto_LabelSet) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_feature_label_dictionary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureLabelDictionaryProto_LabelSet.ProtoReflect.Descriptor instead.
func (*FeatureLabelDictionaryProto_LabelSet) Descriptor() ([]byte, []int) {
	return file_googlesql_public_feature_label_dictionary_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FeatureLabelDictionaryProto_LabelSet) GetLabel() []int32 {
	if x != nil {
		return x.Label
	}
	return nil
}

var File_googlesql_public_feature_label_dictionary_proto protoreflect.FileDescriptor

const file_googlesql_public_feature_label_dictionary_proto_rawDesc = "" +
	"\n" +
	"/googlesql/public/feature_label_dictionary.proto\x12\tgooglesql\"\xb8\x03\n" +
	"\x1bFeatureLabelDictionaryProto\x12]\n" +
	"\rlabel_mapping\x18\x01 \x03(\v28.googlesql.FeatureLabelDictionaryProto.LabelMappingEntryR\flabelMapping\x12`\n" +
	"\x0eencoded_labels\x18\x02 \x03(\v29.googlesql.FeatureLabelDictionaryProto.EncodedLabelsEntryR\rencodedLabels\x1a?\n" +
	"\x11LabelMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a$\n" +
	"\bLabelSet\x12\x18\n" +
	"\x05label\x18\x01 \x03(\x05B\x02\x10\x01R\x05label\x1aq\n" +
	"\x12EncodedLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12E\n" +
	"\x05value\x18\x02 \x01(\v2/.googlesql.FeatureLabelDictionaryProto.LabelSetR\x05value:\x028\x01"

var (
	file_googlesql_public_feature_label_dictionary_proto_rawDescOnce sync.Once
	file_googlesql_public_feature_label_dictionary_proto_rawDescData []byte
)

func file_googlesql_public_feature_label_dictionary_proto_rawDescGZIP() []byte {
	file_googlesql_public_feature_label_dictionary_proto_rawDescOnce.Do(func() {
		file_googlesql_public_feature_label_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_feature_label_dictionary_proto_rawDesc), len(file_googlesql_public_feature_label_dictionary_proto_rawDesc)))
	})
	return file_googlesql_public_feature_label_dictionary_proto_rawDescData
}

var file_googlesql_public_feature_label_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_googlesql_public_feature_label_dictionary_proto_goTypes = []any{
	(*FeatureLabelDictionaryProto)(nil), // 0: googlesql.FeatureLabelDictionaryProto
	nil,                                 // 1: googlesql.FeatureLabelDictionaryProto.LabelMappingEntry
	(*FeatureLabelDictionaryProto_LabelSet)(nil), // 2: googlesql.FeatureLabelDictionaryProto.LabelSet
	nil, // 3: googlesql.FeatureLabelDictionaryProto.EncodedLabelsEntry
}
var file_googlesql_public_feature_label_dictionary_proto_depIdxs = []int32{
	1, // 0: googlesql.FeatureLabelDictionaryProto.label_mapping:type_name -> googlesql.FeatureLabelDictionaryProto.LabelMappingEntry
	3, // 1: googlesql.FeatureLabelDictionaryProto.encoded_labels:type_name -> googlesql.FeatureLabelDictionaryProto.EncodedLabelsEntry
	2, // 2: googlesql.FeatureLabelDictionaryProto.EncodedLabelsEntry.value:type_name -> googlesql.FeatureLabelDictionaryProto.LabelSet
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_googlesql_public_feature_label_dictionary_proto_init() }
func file_googlesql_public_feature_label_dictionary_proto_init() {
	if File_googlesql_public_feature_label_dictionary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_feature_label_dictionary_proto_rawDesc), len(file_googlesql_public_feature_label_dictionary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_feature_label_dictionary_proto_goTypes,
		DependencyIndexes: file_googlesql_public_feature_label_dictionary_proto_depIdxs,
		MessageInfos:      file_googlesql_public_feature_label_dictionary_proto_msgTypes,
	}.Build()
	File_googlesql_public_feature_label_dictionary_proto = out.File
	file_googlesql_public_feature_label_dictionary_proto_goTypes = nil
	file_googlesql_public_feature_label_dictionary_proto_depIdxs = nil
}
