//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/formatter_options.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormatterOptionsProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new line separator characters to use in the formatted output.
	// Usually one of "\n", "\r", "\n\r", or "\r\n".
	NewLineType *string `protobuf:"bytes,1,opt,name=new_line_type,json=newLineType" json:"new_line_type,omitempty"`
	// The line length limit, in characters.
	LineLengthLimit *int32 `protobuf:"varint,2,opt,name=line_length_limit,json=lineLengthLimit" json:"line_length_limit,omitempty"`
	// Number of spaces per level of indentation.
	IndentationSpaces *int32 `protobuf:"varint,3,opt,name=indentation_spaces,json=indentationSpaces" json:"indentation_spaces,omitempty"`
	// If true, formatter tries to proceed even if it encounters invalid GoogleSQL
	// tokens.
	AllowInvalidTokens *bool `protobuf:"varint,4,opt,name=allow_invalid_tokens,json=allowInvalidTokens" json:"allow_invalid_tokens,omitempty"`
	// If true, formatter capitalizes reserved GoogleSQL keywords.
	CapitalizeKeywords *bool `protobuf:"varint,5,opt,name=capitalize_keywords,json=capitalizeKeywords" json:"capitalize_keywords,omitempty"`
	// If true, formatter tries to preserve valid line breaks.
	PreserveLineBreaks *bool `protobuf:"varint,6,opt,name=preserve_line_breaks,json=preserveLineBreaks" json:"preserve_line_breaks,omitempty"`
	// If true and formatting only certain input ranges, the ranges are expanded
	// on both ends if needed to include entire statements.
	ExpandFormatRanges *bool `protobuf:"varint,7,opt,name=expand_format_ranges,json=expandFormatRanges" json:"expand_format_ranges,omitempty"`
	// If true, formatter replaces doubles quotes to single quotes for enclosing
	// string literals.
	EnforceSingleQuotes *bool `protobuf:"varint,8,opt,name=enforce_single_quotes,json=enforceSingleQuotes" json:"enforce_single_quotes,omitempty"`
	// If true, formatter capitalizes reserved GoogleSQL builtin functions.
	CapitalizeFunctions *bool `protobuf:"varint,9,opt,name=capitalize_functions,json=capitalizeFunctions" json:"capitalize_functions,omitempty"`
	// If true, formatter attempts to format the contents of annotated string
	// literals with structured content. Supported annotations:
	// /*sql*/ - for embedded SQL strings,
	// /*proto*/, /*txtpb*/ - for embedded textproto.
	FormatStructuredStrings *bool `protobuf:"varint,10,opt,name=format_structured_strings,json=formatStructuredStrings" json:"format_structured_strings,omitempty"`
	// If true, formatter fixes comments: adds space after comment symbol and
	// trims trailing whitespaces.
	FormatComments *bool `protobuf:"varint,11,opt,name=format_comments,json=formatComments" json:"format_comments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FormatterOptionsProto) Reset() {
	*x = FormatterOptionsProto{}
	mi := &file_googlesql_public_formatter_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatterOptionsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatterOptionsProto) ProtoMessage() {}

func (x *FormatterOptionsProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_formatter_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatterOptionsProto.ProtoReflect.Descriptor instead.
func (*FormatterOptionsProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_formatter_options_proto_rawDescGZIP(), []int{0}
}

func (x *FormatterOptionsProto) GetNewLineType() string {
	if x != nil && x.NewLineType != nil {
		return *x.NewLineType
	}
	return ""
}

func (x *FormatterOptionsProto) GetLineLengthLimit() int32 {
	if x != nil && x.LineLengthLimit != nil {
		return *x.LineLengthLimit
	}
	return 0
}

func (x *FormatterOptionsProto) GetIndentationSpaces() int32 {
	if x != nil && x.IndentationSpaces != nil {
		return *x.IndentationSpaces
	}
	return 0
}

func (x *FormatterOptionsProto) GetAllowInvalidTokens() bool {
	if x != nil && x.AllowInvalidTokens != nil {
		return *x.AllowInvalidTokens
	}
	return false
}

func (x *FormatterOptionsProto) GetCapitalizeKeywords() bool {
	if x != nil && x.CapitalizeKeywords != nil {
		return *x.CapitalizeKeywords
	}
	return false
}

func (x *FormatterOptionsProto) GetPreserveLineBreaks() bool {
	if x != nil && x.PreserveLineBreaks != nil {
		return *x.PreserveLineBreaks
	}
	return false
}

func (x *FormatterOptionsProto) GetExpandFormatRanges() bool {
	if x != nil && x.ExpandFormatRanges != nil {
		return *x.ExpandFormatRanges
	}
	return false
}

func (x *FormatterOptionsProto) GetEnforceSingleQuotes() bool {
	if x != nil && x.EnforceSingleQuotes != nil {
		return *x.EnforceSingleQuotes
	}
	return false
}

func (x *FormatterOptionsProto) GetCapitalizeFunctions() bool {
	if x != nil && x.CapitalizeFunctions != nil {
		return *x.CapitalizeFunctions
	}
	return false
}

func (x *FormatterOptionsProto) GetFormatStructuredStrings() bool {
	if x != nil && x.FormatStructuredStrings != nil {
		return *x.FormatStructuredStrings
	}
	return false
}

func (x *FormatterOptionsProto) GetFormatComments() bool {
	if x != nil && x.FormatComments != nil {
		return *x.FormatComments
	}
	return false
}

// Represents a byte range [start, end) in the input to be formatted.
// Also see expand_format_ranges above. If it is not enabled and a range
// starts/ends in the middle of a token, the result may be malformed.
type FormatterRangeProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0-based byte offset start, inclusive.
	Start *int32 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	// 0-based byte offset end, exclusive.
	End           *int32 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatterRangeProto) Reset() {
	*x = FormatterRangeProto{}
	mi := &file_googlesql_public_formatter_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatterRangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatterRangeProto) ProtoMessage() {}

func (x *FormatterRangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_formatter_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatterRangeProto.ProtoReflect.Descriptor instead.
func (*FormatterRangeProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_formatter_options_proto_rawDescGZIP(), []int{1}
}

func (x *FormatterRangeProto) GetStart() int32 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *FormatterRangeProto) GetEnd() int32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

var File_googlesql_public_formatter_options_proto protoreflect.FileDescriptor

const file_googlesql_public_formatter_options_proto_rawDesc = "" +
	"\n" +
	"(googlesql/public/formatter_options.proto\x12\tgooglesql\"\xa9\x04\n" +
	"\x15FormatterOptionsProto\x12\"\n" +
	"\rnew_line_type\x18\x01 \x01(\tR\vnewLineType\x12*\n" +
	"\x11line_length_limit\x18\x02 \x01(\x05R\x0flineLengthLimit\x12-\n" +
	"\x12indentation_spaces\x18\x03 \x01(\x05R\x11indentationSpaces\x120\n" +
	"\x14allow_invalid_tokens\x18\x04 \x01(\bR\x12allowInvalidTokens\x12/\n" +
	"\x13capitalize_keywords\x18\x05 \x01(\bR\x12capitalizeKeywords\x120\n" +
	"\x14preserve_line_breaks\x18\x06 \x01(\bR\x12preserveLineBreaks\x120\n" +
	"\x14expand_format_ranges\x18\a \x01(\bR\x12expandFormatRanges\x122\n" +
	"\x15enforce_single_quotes\x18\b \x01(\bR\x13enforceSingleQuotes\x121\n" +
	"\x14capitalize_functions\x18\t \x01(\bR\x13capitalizeFunctions\x12:\n" +
	"\x19format_structured_strings\x18\n" +
	" \x01(\bR\x17formatStructuredStrings\x12'\n" +
	"\x0fformat_comments\x18\v \x01(\bR\x0eformatComments\"=\n" +
	"\x13FormatterRangeProto\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03endB\x16\n" +
	"\x14com.google.googlesql"

var (
	file_googlesql_public_formatter_options_proto_rawDescOnce sync.Once
	file_googlesql_public_formatter_options_proto_rawDescData []byte
)

func file_googlesql_public_formatter_options_proto_rawDescGZIP() []byte {
	file_googlesql_public_formatter_options_proto_rawDescOnce.Do(func() {
		file_googlesql_public_formatter_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_formatter_options_proto_rawDesc), len(file_googlesql_public_formatter_options_proto_rawDesc)))
	})
	return file_googlesql_public_formatter_options_proto_rawDescData
}

var file_googlesql_public_formatter_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_googlesql_public_formatter_options_proto_goTypes = []any{
	(*FormatterOptionsProto)(nil), // 0: googlesql.FormatterOptionsProto
	(*FormatterRangeProto)(nil),   // 1: googlesql.FormatterRangeProto
}
var file_googlesql_public_formatter_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_formatter_options_proto_init() }
func file_googlesql_public_formatter_options_proto_init() {
	if File_googlesql_public_formatter_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_formatter_options_proto_rawDesc), len(file_googlesql_public_formatter_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_formatter_options_proto_goTypes,
		DependencyIndexes: file_googlesql_public_formatter_options_proto_depIdxs,
		MessageInfos:      file_googlesql_public_formatter_options_proto_msgTypes,
	}.Build()
	File_googlesql_public_formatter_options_proto = out.File
	file_googlesql_public_formatter_options_proto_goTypes = nil
	file_googlesql_public_formatter_options_proto_depIdxs = nil
}
