//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// LINT: LEGACY_NAMES

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/simple_value.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents an immutable simple value. SimpleValue is a light weight version
// of value class. It can be used in the type library to avoid circular
// dependency of directly using value class in the type library.
type SimpleValueProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SimpleValueProto_Int64Value
	//	*SimpleValueProto_StringValue
	//	*SimpleValueProto_BoolValue
	//	*SimpleValueProto_DoubleValue
	//	*SimpleValueProto_BytesValue
	//	*SimpleValueProto_X_SimpleValueProto_SwitchMustHaveADefault
	Value         isSimpleValueProto_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleValueProto) Reset() {
	*x = SimpleValueProto{}
	mi := &file_googlesql_public_simple_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleValueProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleValueProto) ProtoMessage() {}

func (x *SimpleValueProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_simple_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleValueProto.ProtoReflect.Descriptor instead.
func (*SimpleValueProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_simple_value_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleValueProto) GetValue() isSimpleValueProto_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SimpleValueProto) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*SimpleValueProto_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *SimpleValueProto) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*SimpleValueProto_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *SimpleValueProto) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*SimpleValueProto_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *SimpleValueProto) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*SimpleValueProto_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *SimpleValueProto) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*SimpleValueProto_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *SimpleValueProto) GetX_SimpleValueProto_SwitchMustHaveADefault() bool {
	if x != nil {
		if x, ok := x.Value.(*SimpleValueProto_X_SimpleValueProto_SwitchMustHaveADefault); ok {
			return x.X_SimpleValueProto_SwitchMustHaveADefault
		}
	}
	return false
}

type isSimpleValueProto_Value interface {
	isSimpleValueProto_Value()
}

type SimpleValueProto_Int64Value struct {
	Int64Value int64 `protobuf:"varint,1,opt,name=int64_value,json=int64Value,oneof"` // Set when SimpleValue::type_ is TYPE_INT64.
}

type SimpleValueProto_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,oneof"` // Set when SimpleValue::type_ is TYPE_STRING.
}

type SimpleValueProto_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,oneof"` // Set when SimpleValue::type_ is TYPE_BOOL.
}

type SimpleValueProto_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,oneof"` // Set when SimpleValue::type_ is TYPE_DOUBLE.
}

type SimpleValueProto_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,oneof"` // Set when SimpleValue::type_ is TYPE_BYTES.
}

type SimpleValueProto_X_SimpleValueProto_SwitchMustHaveADefault struct {
	// User code that switches on this oneof enum must have a default case so
	// builds won't break when new fields are added.
	X_SimpleValueProto_SwitchMustHaveADefault bool `protobuf:"varint,255,opt,name=__SimpleValueProto__switch_must_have_a_default,json=SimpleValueProtoSwitchMustHaveADefault,oneof"`
}

func (*SimpleValueProto_Int64Value) isSimpleValueProto_Value() {}

func (*SimpleValueProto_StringValue) isSimpleValueProto_Value() {}

func (*SimpleValueProto_BoolValue) isSimpleValueProto_Value() {}

func (*SimpleValueProto_DoubleValue) isSimpleValueProto_Value() {}

func (*SimpleValueProto_BytesValue) isSimpleValueProto_Value() {}

func (*SimpleValueProto_X_SimpleValueProto_SwitchMustHaveADefault) isSimpleValueProto_Value() {}

var File_googlesql_public_simple_value_proto protoreflect.FileDescriptor

const file_googlesql_public_simple_value_proto_rawDesc = "" +
	"\n" +
	"#googlesql/public/simple_value.proto\x12\tgooglesql\"\xaf\x02\n" +
	"\x10SimpleValueProto\x12!\n" +
	"\vint64_value\x18\x01 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12a\n" +
	".__SimpleValueProto__switch_must_have_a_default\x18\xff\x01 \x01(\bH\x00R&SimpleValueProtoSwitchMustHaveADefaultB\a\n" +
	"\x05valueB,\n" +
	"\x14com.google.googlesqlB\x14GoogleSQLSimpleValue"

var (
	file_googlesql_public_simple_value_proto_rawDescOnce sync.Once
	file_googlesql_public_simple_value_proto_rawDescData []byte
)

func file_googlesql_public_simple_value_proto_rawDescGZIP() []byte {
	file_googlesql_public_simple_value_proto_rawDescOnce.Do(func() {
		file_googlesql_public_simple_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_simple_value_proto_rawDesc), len(file_googlesql_public_simple_value_proto_rawDesc)))
	})
	return file_googlesql_public_simple_value_proto_rawDescData
}

var file_googlesql_public_simple_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_googlesql_public_simple_value_proto_goTypes = []any{
	(*SimpleValueProto)(nil), // 0: googlesql.SimpleValueProto
}
var file_googlesql_public_simple_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_simple_value_proto_init() }
func file_googlesql_public_simple_value_proto_init() {
	if File_googlesql_public_simple_value_proto != nil {
		return
	}
	file_googlesql_public_simple_value_proto_msgTypes[0].OneofWrappers = []any{
		(*SimpleValueProto_Int64Value)(nil),
		(*SimpleValueProto_StringValue)(nil),
		(*SimpleValueProto_BoolValue)(nil),
		(*SimpleValueProto_DoubleValue)(nil),
		(*SimpleValueProto_BytesValue)(nil),
		(*SimpleValueProto_X_SimpleValueProto_SwitchMustHaveADefault)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_simple_value_proto_rawDesc), len(file_googlesql_public_simple_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_simple_value_proto_goTypes,
		DependencyIndexes: file_googlesql_public_simple_value_proto_depIdxs,
		MessageInfos:      file_googlesql_public_simple_value_proto_msgTypes,
	}.Build()
	File_googlesql_public_simple_value_proto = out.File
	file_googlesql_public_simple_value_proto_goTypes = nil
	file_googlesql_public_simple_value_proto_depIdxs = nil
}
