//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/simple_sequence.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleSequenceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName      *string                `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleSequenceProto) Reset() {
	*x = SimpleSequenceProto{}
	mi := &file_googlesql_public_simple_sequence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleSequenceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleSequenceProto) ProtoMessage() {}

func (x *SimpleSequenceProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_simple_sequence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleSequenceProto.ProtoReflect.Descriptor instead.
func (*SimpleSequenceProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_simple_sequence_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleSequenceProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimpleSequenceProto) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

var File_googlesql_public_simple_sequence_proto protoreflect.FileDescriptor

const file_googlesql_public_simple_sequence_proto_rawDesc = "" +
	"\n" +
	"&googlesql/public/simple_sequence.proto\x12\tgooglesql\"F\n" +
	"\x13SimpleSequenceProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullNameB,\n" +
	"\x14com.google.googlesqlB\x14SimpleSequenceProtos"

var (
	file_googlesql_public_simple_sequence_proto_rawDescOnce sync.Once
	file_googlesql_public_simple_sequence_proto_rawDescData []byte
)

func file_googlesql_public_simple_sequence_proto_rawDescGZIP() []byte {
	file_googlesql_public_simple_sequence_proto_rawDescOnce.Do(func() {
		file_googlesql_public_simple_sequence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_simple_sequence_proto_rawDesc), len(file_googlesql_public_simple_sequence_proto_rawDesc)))
	})
	return file_googlesql_public_simple_sequence_proto_rawDescData
}

var file_googlesql_public_simple_sequence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_googlesql_public_simple_sequence_proto_goTypes = []any{
	(*SimpleSequenceProto)(nil), // 0: googlesql.SimpleSequenceProto
}
var file_googlesql_public_simple_sequence_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_simple_sequence_proto_init() }
func file_googlesql_public_simple_sequence_proto_init() {
	if File_googlesql_public_simple_sequence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_simple_sequence_proto_rawDesc), len(file_googlesql_public_simple_sequence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_simple_sequence_proto_goTypes,
		DependencyIndexes: file_googlesql_public_simple_sequence_proto_depIdxs,
		MessageInfos:      file_googlesql_public_simple_sequence_proto_msgTypes,
	}.Build()
	File_googlesql_public_simple_sequence_proto = out.File
	file_googlesql_public_simple_sequence_proto_goTypes = nil
	file_googlesql_public_simple_sequence_proto_depIdxs = nil
}
