//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This is a forwarding file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/type_annotation.proto

package googlesql_public

import (
	_ "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_googlesql_public_type_annotation_proto protoreflect.FileDescriptor

const file_googlesql_public_type_annotation_proto_rawDesc = "" +
	"\n" +
	"&googlesql/public/type_annotation.proto\x12\x11googlesql.storage\x1a,googlesql/public/proto/type_annotation.protoB\"\n" +
	"\x14com.google.googlesql\xa2\x02\tGOOGLESQL"

var file_googlesql_public_type_annotation_proto_goTypes = []any{}
var file_googlesql_public_type_annotation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_type_annotation_proto_init() }
func file_googlesql_public_type_annotation_proto_init() {
	if File_googlesql_public_type_annotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_type_annotation_proto_rawDesc), len(file_googlesql_public_type_annotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_type_annotation_proto_goTypes,
		DependencyIndexes: file_googlesql_public_type_annotation_proto_depIdxs,
	}.Build()
	File_googlesql_public_type_annotation_proto = out.File
	file_googlesql_public_type_annotation_proto_goTypes = nil
	file_googlesql_public_type_annotation_proto_depIdxs = nil
}
