//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// LINT: LEGACY_NAMES

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/value.proto

package googlesql_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValueProto represents the serialized form of the googlesql::Value.
//
// The intention is to support multiple languages including Java and C++, so we
// must be sensitive to the distinction between Java Strings and byte arrays or
// ByteStrings.
//
// We also want to support use-cases which do not want to serialize a copy of
// the GoogleSQL type for every instance (which might be very repetitive).
// Therefore, unlike googlesql::Value, ValueProto does not carry full type
// information with every instance, and can only be fully interpreted with an
// associated TypeProto.
type ValueProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each non-null value will have exactly one of these fields specified.
	// Null values will have no fields set.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*ValueProto_Int32Value
	//	*ValueProto_Int64Value
	//	*ValueProto_Uint32Value
	//	*ValueProto_Uint64Value
	//	*ValueProto_BoolValue
	//	*ValueProto_FloatValue
	//	*ValueProto_DoubleValue
	//	*ValueProto_StringValue
	//	*ValueProto_BytesValue
	//	*ValueProto_DateValue
	//	*ValueProto_EnumValue
	//	*ValueProto_ArrayValue
	//	*ValueProto_StructValue
	//	*ValueProto_ProtoValue
	//	*ValueProto_TimestampValue
	//	*ValueProto_TimestampPicoValue
	//	*ValueProto_TimestampPicosValue
	//	*ValueProto_DatetimeValue
	//	*ValueProto_TimeValue
	//	*ValueProto_GeographyValue
	//	*ValueProto_NumericValue
	//	*ValueProto_BignumericValue
	//	*ValueProto_JsonValue
	//	*ValueProto_IntervalValue
	//	*ValueProto_TokenlistValue
	//	*ValueProto_RangeValue
	//	*ValueProto_UuidValue
	//	*ValueProto_MapValue
	//	*ValueProto_X_ValueProto_SwitchMustHaveADefault
	Value         isValueProto_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto) Reset() {
	*x = ValueProto{}
	mi := &file_googlesql_public_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto) ProtoMessage() {}

func (x *ValueProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto.ProtoReflect.Descriptor instead.
func (*ValueProto) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0}
}

func (x *ValueProto) GetValue() isValueProto_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ValueProto) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *ValueProto) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *ValueProto) GetUint32Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_Uint32Value); ok {
			return x.Uint32Value
		}
	}
	return 0
}

func (x *ValueProto) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *ValueProto) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ValueProto) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *ValueProto) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *ValueProto) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ValueProto) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *ValueProto) GetDateValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_DateValue); ok {
			return x.DateValue
		}
	}
	return 0
}

func (x *ValueProto) GetEnumValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_EnumValue); ok {
			return x.EnumValue
		}
	}
	return 0
}

func (x *ValueProto) GetArrayValue() *ValueProto_Array {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *ValueProto) GetStructValue() *ValueProto_Struct {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *ValueProto) GetProtoValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_ProtoValue); ok {
			return x.ProtoValue
		}
	}
	return nil
}

func (x *ValueProto) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in googlesql/public/value.proto.
func (x *ValueProto) GetTimestampPicoValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_TimestampPicoValue); ok {
			return x.TimestampPicoValue
		}
	}
	return nil
}

func (x *ValueProto) GetTimestampPicosValue() *ValueProto_TimestampPicos {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_TimestampPicosValue); ok {
			return x.TimestampPicosValue
		}
	}
	return nil
}

func (x *ValueProto) GetDatetimeValue() *ValueProto_Datetime {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return nil
}

func (x *ValueProto) GetTimeValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_TimeValue); ok {
			return x.TimeValue
		}
	}
	return 0
}

func (x *ValueProto) GetGeographyValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_GeographyValue); ok {
			return x.GeographyValue
		}
	}
	return nil
}

func (x *ValueProto) GetNumericValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_NumericValue); ok {
			return x.NumericValue
		}
	}
	return nil
}

func (x *ValueProto) GetBignumericValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_BignumericValue); ok {
			return x.BignumericValue
		}
	}
	return nil
}

func (x *ValueProto) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

func (x *ValueProto) GetIntervalValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_IntervalValue); ok {
			return x.IntervalValue
		}
	}
	return nil
}

func (x *ValueProto) GetTokenlistValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_TokenlistValue); ok {
			return x.TokenlistValue
		}
	}
	return nil
}

func (x *ValueProto) GetRangeValue() *ValueProto_Range {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_RangeValue); ok {
			return x.RangeValue
		}
	}
	return nil
}

func (x *ValueProto) GetUuidValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_UuidValue); ok {
			return x.UuidValue
		}
	}
	return nil
}

func (x *ValueProto) GetMapValue() *ValueProto_Map {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

func (x *ValueProto) GetX_ValueProto_SwitchMustHaveADefault() bool {
	if x != nil {
		if x, ok := x.Value.(*ValueProto_X_ValueProto_SwitchMustHaveADefault); ok {
			return x.X_ValueProto_SwitchMustHaveADefault
		}
	}
	return false
}

type isValueProto_Value interface {
	isValueProto_Value()
}

type ValueProto_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,oneof"`
}

type ValueProto_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,oneof"`
}

type ValueProto_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,3,opt,name=uint32_value,json=uint32Value,oneof"`
}

type ValueProto_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,oneof"`
}

type ValueProto_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,oneof"`
}

type ValueProto_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,oneof"`
}

type ValueProto_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,oneof"`
}

type ValueProto_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}

type ValueProto_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,oneof"`
}

type ValueProto_DateValue struct {
	DateValue int32 `protobuf:"varint,10,opt,name=date_value,json=dateValue,oneof"`
}

type ValueProto_EnumValue struct {
	// Tag 11 was used for specifying micros timestamps as int64, now obsolete.
	EnumValue int32 `protobuf:"varint,12,opt,name=enum_value,json=enumValue,oneof"`
}

type ValueProto_ArrayValue struct {
	ArrayValue *ValueProto_Array `protobuf:"bytes,13,opt,name=array_value,json=arrayValue,oneof"`
}

type ValueProto_StructValue struct {
	StructValue *ValueProto_Struct `protobuf:"bytes,14,opt,name=struct_value,json=structValue,oneof"`
}

type ValueProto_ProtoValue struct {
	// Stores a serialized protocol message.
	ProtoValue []byte `protobuf:"bytes,15,opt,name=proto_value,json=protoValue,oneof"`
}

type ValueProto_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=timestamp_value,json=timestampValue,oneof"`
}

type ValueProto_TimestampPicoValue struct {
	// Deprecated: Marked as deprecated in googlesql/public/value.proto.
	TimestampPicoValue []byte `protobuf:"bytes,29,opt,name=timestamp_pico_value,json=timestampPicoValue,oneof"`
}

type ValueProto_TimestampPicosValue struct {
	TimestampPicosValue *ValueProto_TimestampPicos `protobuf:"bytes,30,opt,name=timestamp_picos_value,json=timestampPicosValue,oneof"`
}

type ValueProto_DatetimeValue struct {
	DatetimeValue *ValueProto_Datetime `protobuf:"bytes,17,opt,name=datetime_value,json=datetimeValue,oneof"`
}

type ValueProto_TimeValue struct {
	// Bit field encoding of hour/minute/second/nanos. See TimeValue class for
	// details.
	TimeValue int64 `protobuf:"varint,18,opt,name=time_value,json=timeValue,oneof"`
}

type ValueProto_GeographyValue struct {
	// Geography encoded using ::stlib::STGeographyEncoder
	GeographyValue []byte `protobuf:"bytes,19,opt,name=geography_value,json=geographyValue,oneof"`
}

type ValueProto_NumericValue struct {
	// Encoded numeric value. For the encoding format see documentation for
	// NumericValue::SerializeAsProtoBytes().
	NumericValue []byte `protobuf:"bytes,20,opt,name=numeric_value,json=numericValue,oneof"`
}

type ValueProto_BignumericValue struct {
	// Encoded bignumeric value. For the encoding format see documentation for
	// BigNumericValue::SerializeAsProtoBytes().
	BignumericValue []byte `protobuf:"bytes,21,opt,name=bignumeric_value,json=bignumericValue,oneof"`
}

type ValueProto_JsonValue struct {
	// Tag 22 was used for json value as bytes, now obsolete.
	// Json value represented as a string document.
	JsonValue string `protobuf:"bytes,23,opt,name=json_value,json=jsonValue,oneof"`
}

type ValueProto_IntervalValue struct {
	// Encoded interval value. For the encoding format see documentation for
	// IntervalValue::SerializeAsBytes().
	IntervalValue []byte `protobuf:"bytes,24,opt,name=interval_value,json=intervalValue,oneof"`
}

type ValueProto_TokenlistValue struct {
	// Encoded tokenlist value.
	TokenlistValue []byte `protobuf:"bytes,25,opt,name=tokenlist_value,json=tokenlistValue,oneof"`
}

type ValueProto_RangeValue struct {
	// Encoded range value. See (broken link).
	RangeValue *ValueProto_Range `protobuf:"bytes,26,opt,name=range_value,json=rangeValue,oneof"`
}

type ValueProto_UuidValue struct {
	// Encoded uuid value. For the encoding format see documentation for
	// UuidValue::SerializeAsBytes().
	UuidValue []byte `protobuf:"bytes,27,opt,name=uuid_value,json=uuidValue,oneof"`
}

type ValueProto_MapValue struct {
	// Encoded map value. See (broken link).
	MapValue *ValueProto_Map `protobuf:"bytes,28,opt,name=map_value,json=mapValue,oneof"`
}

type ValueProto_X_ValueProto_SwitchMustHaveADefault struct {
	// User code that switches on this oneoff enum must have a default case so
	// builds won't break when new fields are added.
	X_ValueProto_SwitchMustHaveADefault bool `protobuf:"varint,255,opt,name=__ValueProto__switch_must_have_a_default,json=ValueProtoSwitchMustHaveADefault,oneof"`
}

func (*ValueProto_Int32Value) isValueProto_Value() {}

func (*ValueProto_Int64Value) isValueProto_Value() {}

func (*ValueProto_Uint32Value) isValueProto_Value() {}

func (*ValueProto_Uint64Value) isValueProto_Value() {}

func (*ValueProto_BoolValue) isValueProto_Value() {}

func (*ValueProto_FloatValue) isValueProto_Value() {}

func (*ValueProto_DoubleValue) isValueProto_Value() {}

func (*ValueProto_StringValue) isValueProto_Value() {}

func (*ValueProto_BytesValue) isValueProto_Value() {}

func (*ValueProto_DateValue) isValueProto_Value() {}

func (*ValueProto_EnumValue) isValueProto_Value() {}

func (*ValueProto_ArrayValue) isValueProto_Value() {}

func (*ValueProto_StructValue) isValueProto_Value() {}

func (*ValueProto_ProtoValue) isValueProto_Value() {}

func (*ValueProto_TimestampValue) isValueProto_Value() {}

func (*ValueProto_TimestampPicoValue) isValueProto_Value() {}

func (*ValueProto_TimestampPicosValue) isValueProto_Value() {}

func (*ValueProto_DatetimeValue) isValueProto_Value() {}

func (*ValueProto_TimeValue) isValueProto_Value() {}

func (*ValueProto_GeographyValue) isValueProto_Value() {}

func (*ValueProto_NumericValue) isValueProto_Value() {}

func (*ValueProto_BignumericValue) isValueProto_Value() {}

func (*ValueProto_JsonValue) isValueProto_Value() {}

func (*ValueProto_IntervalValue) isValueProto_Value() {}

func (*ValueProto_TokenlistValue) isValueProto_Value() {}

func (*ValueProto_RangeValue) isValueProto_Value() {}

func (*ValueProto_UuidValue) isValueProto_Value() {}

func (*ValueProto_MapValue) isValueProto_Value() {}

func (*ValueProto_X_ValueProto_SwitchMustHaveADefault) isValueProto_Value() {}

// An ordered collection of elements of arbitrary count.
type ValueProto_Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Element       []*ValueProto          `protobuf:"bytes,1,rep,name=element" json:"element,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_Array) Reset() {
	*x = ValueProto_Array{}
	mi := &file_googlesql_public_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_Array) ProtoMessage() {}

func (x *ValueProto_Array) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_Array.ProtoReflect.Descriptor instead.
func (*ValueProto_Array) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ValueProto_Array) GetElement() []*ValueProto {
	if x != nil {
		return x.Element
	}
	return nil
}

// A collection of fields. The count, order, and type of the fields is
// determined by the type associated with this value.
type ValueProto_Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         []*ValueProto          `protobuf:"bytes,1,rep,name=field" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_Struct) Reset() {
	*x = ValueProto_Struct{}
	mi := &file_googlesql_public_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_Struct) ProtoMessage() {}

func (x *ValueProto_Struct) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_Struct.ProtoReflect.Descriptor instead.
func (*ValueProto_Struct) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ValueProto_Struct) GetField() []*ValueProto {
	if x != nil {
		return x.Field
	}
	return nil
}

type ValueProto_Datetime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents bit field encoding of year/month/day/hour/minute/second.
	// See class DatetimeValue in civil_time.h for details of encoding.
	BitFieldDatetimeSeconds *int64 `protobuf:"varint,1,opt,name=bit_field_datetime_seconds,json=bitFieldDatetimeSeconds" json:"bit_field_datetime_seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution.
	Nanos         *int32 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_Datetime) Reset() {
	*x = ValueProto_Datetime{}
	mi := &file_googlesql_public_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_Datetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_Datetime) ProtoMessage() {}

func (x *ValueProto_Datetime) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_Datetime.ProtoReflect.Descriptor instead.
func (*ValueProto_Datetime) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ValueProto_Datetime) GetBitFieldDatetimeSeconds() int64 {
	if x != nil && x.BitFieldDatetimeSeconds != nil {
		return *x.BitFieldDatetimeSeconds
	}
	return 0
}

func (x *ValueProto_Datetime) GetNanos() int32 {
	if x != nil && x.Nanos != nil {
		return *x.Nanos
	}
	return 0
}

// A range of values, bounded by the values 'start' (inclusive) and 'end'
// (exclusive). A range has an element type, and values must be of this
// element type. A range is contiguous, ie it contains all values of the given
// element type starting at 'start' and ending before 'end'.
//
// A "null" value on start or end represents an unbounded start or end value
// respectively. Start and end values must always be present.
type ValueProto_Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents the start of the range.
	Start *ValueProto `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	// Represents the end of the range.
	End           *ValueProto `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_Range) Reset() {
	*x = ValueProto_Range{}
	mi := &file_googlesql_public_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_Range) ProtoMessage() {}

func (x *ValueProto_Range) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_Range.ProtoReflect.Descriptor instead.
func (*ValueProto_Range) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ValueProto_Range) GetStart() *ValueProto {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ValueProto_Range) GetEnd() *ValueProto {
	if x != nil {
		return x.End
	}
	return nil
}

// A single entry in a Map, representing the mapping between `key` and
// `value`.
type ValueProto_MapEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents the serialized map key for the entry.
	Key *ValueProto `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// Represents the serialized map value of the entry.
	Value         *ValueProto `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_MapEntry) Reset() {
	*x = ValueProto_MapEntry{}
	mi := &file_googlesql_public_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_MapEntry) ProtoMessage() {}

func (x *ValueProto_MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_MapEntry.ProtoReflect.Descriptor instead.
func (*ValueProto_MapEntry) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ValueProto_MapEntry) GetKey() *ValueProto {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ValueProto_MapEntry) GetValue() *ValueProto {
	if x != nil {
		return x.Value
	}
	return nil
}

// An unordered mapping from key to value, represented as a collection of
// map entries.
type ValueProto_Map struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []*ValueProto_MapEntry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_Map) Reset() {
	*x = ValueProto_Map{}
	mi := &file_googlesql_public_value_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_Map) ProtoMessage() {}

func (x *ValueProto_Map) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_Map.ProtoReflect.Descriptor instead.
func (*ValueProto_Map) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ValueProto_Map) GetEntry() []*ValueProto_MapEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// A Timestamp with picosecond precision. It is a count of seconds and
// fractions of seconds at picosecond resolution. The count is relative to
// Unix Epoch, i.e. UTC midnight on January 1, 1970.
type ValueProto_TimestampPicos struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds *int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Non-negative fractions of a second at picosecond resolution.
	// Must be from 0 to 999,999,999,999 inclusive.
	Picos         *int64 `protobuf:"varint,2,opt,name=picos" json:"picos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueProto_TimestampPicos) Reset() {
	*x = ValueProto_TimestampPicos{}
	mi := &file_googlesql_public_value_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueProto_TimestampPicos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueProto_TimestampPicos) ProtoMessage() {}

func (x *ValueProto_TimestampPicos) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_value_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueProto_TimestampPicos.ProtoReflect.Descriptor instead.
func (*ValueProto_TimestampPicos) Descriptor() ([]byte, []int) {
	return file_googlesql_public_value_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ValueProto_TimestampPicos) GetSeconds() int64 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

func (x *ValueProto_TimestampPicos) GetPicos() int64 {
	if x != nil && x.Picos != nil {
		return *x.Picos
	}
	return 0
}

var File_googlesql_public_value_proto protoreflect.FileDescriptor

const file_googlesql_public_value_proto_rawDesc = "" +
	"\n" +
	"\x1cgooglesql/public/value.proto\x12\tgooglesql\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x0f\n" +
	"\n" +
	"ValueProto\x12!\n" +
	"\vint32_value\x18\x01 \x01(\x05H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint32_value\x18\x03 \x01(\rH\x00R\vuint32Value\x12#\n" +
	"\fuint64_value\x18\x04 \x01(\x04H\x00R\vuint64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vfloat_value\x18\x06 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\a \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\b \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\t \x01(\fH\x00R\n" +
	"bytesValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\n" +
	" \x01(\x05H\x00R\tdateValue\x12\x1f\n" +
	"\n" +
	"enum_value\x18\f \x01(\x05H\x00R\tenumValue\x12>\n" +
	"\varray_value\x18\r \x01(\v2\x1b.googlesql.ValueProto.ArrayH\x00R\n" +
	"arrayValue\x12A\n" +
	"\fstruct_value\x18\x0e \x01(\v2\x1c.googlesql.ValueProto.StructH\x00R\vstructValue\x12%\n" +
	"\vproto_value\x18\x0f \x01(\fB\x02\b\x01H\x00R\n" +
	"protoValue\x12E\n" +
	"\x0ftimestamp_value\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x126\n" +
	"\x14timestamp_pico_value\x18\x1d \x01(\fB\x02\x18\x01H\x00R\x12timestampPicoValue\x12Z\n" +
	"\x15timestamp_picos_value\x18\x1e \x01(\v2$.googlesql.ValueProto.TimestampPicosH\x00R\x13timestampPicosValue\x12G\n" +
	"\x0edatetime_value\x18\x11 \x01(\v2\x1e.googlesql.ValueProto.DatetimeH\x00R\rdatetimeValue\x12\x1f\n" +
	"\n" +
	"time_value\x18\x12 \x01(\x03H\x00R\ttimeValue\x12)\n" +
	"\x0fgeography_value\x18\x13 \x01(\fH\x00R\x0egeographyValue\x12%\n" +
	"\rnumeric_value\x18\x14 \x01(\fH\x00R\fnumericValue\x12+\n" +
	"\x10bignumeric_value\x18\x15 \x01(\fH\x00R\x0fbignumericValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x17 \x01(\tH\x00R\tjsonValue\x12'\n" +
	"\x0einterval_value\x18\x18 \x01(\fH\x00R\rintervalValue\x12)\n" +
	"\x0ftokenlist_value\x18\x19 \x01(\fH\x00R\x0etokenlistValue\x12>\n" +
	"\vrange_value\x18\x1a \x01(\v2\x1b.googlesql.ValueProto.RangeH\x00R\n" +
	"rangeValue\x12\x1f\n" +
	"\n" +
	"uuid_value\x18\x1b \x01(\fH\x00R\tuuidValue\x128\n" +
	"\tmap_value\x18\x1c \x01(\v2\x19.googlesql.ValueProto.MapH\x00R\bmapValue\x12U\n" +
	"(__ValueProto__switch_must_have_a_default\x18\xff\x01 \x01(\bH\x00R ValueProtoSwitchMustHaveADefault\x1a8\n" +
	"\x05Array\x12/\n" +
	"\aelement\x18\x01 \x03(\v2\x15.googlesql.ValueProtoR\aelement\x1a5\n" +
	"\x06Struct\x12+\n" +
	"\x05field\x18\x01 \x03(\v2\x15.googlesql.ValueProtoR\x05field\x1a]\n" +
	"\bDatetime\x12;\n" +
	"\x1abit_field_datetime_seconds\x18\x01 \x01(\x03R\x17bitFieldDatetimeSeconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\x1a]\n" +
	"\x05Range\x12+\n" +
	"\x05start\x18\x01 \x01(\v2\x15.googlesql.ValueProtoR\x05start\x12'\n" +
	"\x03end\x18\x02 \x01(\v2\x15.googlesql.ValueProtoR\x03end\x1a`\n" +
	"\bMapEntry\x12'\n" +
	"\x03key\x18\x01 \x01(\v2\x15.googlesql.ValueProtoR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.googlesql.ValueProtoR\x05value\x1a;\n" +
	"\x03Map\x124\n" +
	"\x05entry\x18\x01 \x03(\v2\x1e.googlesql.ValueProto.MapEntryR\x05entry\x1a@\n" +
	"\x0eTimestampPicos\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05picos\x18\x02 \x01(\x03R\x05picosB\a\n" +
	"\x05valueJ\x04\b\v\x10\fJ\x04\b\x16\x10\x17B)\n" +
	"\x14com.google.googlesqlB\x0eGoogleSQLValue\xf8\x01\x01"

var (
	file_googlesql_public_value_proto_rawDescOnce sync.Once
	file_googlesql_public_value_proto_rawDescData []byte
)

func file_googlesql_public_value_proto_rawDescGZIP() []byte {
	file_googlesql_public_value_proto_rawDescOnce.Do(func() {
		file_googlesql_public_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_value_proto_rawDesc), len(file_googlesql_public_value_proto_rawDesc)))
	})
	return file_googlesql_public_value_proto_rawDescData
}

var file_googlesql_public_value_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_googlesql_public_value_proto_goTypes = []any{
	(*ValueProto)(nil),                // 0: googlesql.ValueProto
	(*ValueProto_Array)(nil),          // 1: googlesql.ValueProto.Array
	(*ValueProto_Struct)(nil),         // 2: googlesql.ValueProto.Struct
	(*ValueProto_Datetime)(nil),       // 3: googlesql.ValueProto.Datetime
	(*ValueProto_Range)(nil),          // 4: googlesql.ValueProto.Range
	(*ValueProto_MapEntry)(nil),       // 5: googlesql.ValueProto.MapEntry
	(*ValueProto_Map)(nil),            // 6: googlesql.ValueProto.Map
	(*ValueProto_TimestampPicos)(nil), // 7: googlesql.ValueProto.TimestampPicos
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_googlesql_public_value_proto_depIdxs = []int32{
	1,  // 0: googlesql.ValueProto.array_value:type_name -> googlesql.ValueProto.Array
	2,  // 1: googlesql.ValueProto.struct_value:type_name -> googlesql.ValueProto.Struct
	8,  // 2: googlesql.ValueProto.timestamp_value:type_name -> google.protobuf.Timestamp
	7,  // 3: googlesql.ValueProto.timestamp_picos_value:type_name -> googlesql.ValueProto.TimestampPicos
	3,  // 4: googlesql.ValueProto.datetime_value:type_name -> googlesql.ValueProto.Datetime
	4,  // 5: googlesql.ValueProto.range_value:type_name -> googlesql.ValueProto.Range
	6,  // 6: googlesql.ValueProto.map_value:type_name -> googlesql.ValueProto.Map
	0,  // 7: googlesql.ValueProto.Array.element:type_name -> googlesql.ValueProto
	0,  // 8: googlesql.ValueProto.Struct.field:type_name -> googlesql.ValueProto
	0,  // 9: googlesql.ValueProto.Range.start:type_name -> googlesql.ValueProto
	0,  // 10: googlesql.ValueProto.Range.end:type_name -> googlesql.ValueProto
	0,  // 11: googlesql.ValueProto.MapEntry.key:type_name -> googlesql.ValueProto
	0,  // 12: googlesql.ValueProto.MapEntry.value:type_name -> googlesql.ValueProto
	5,  // 13: googlesql.ValueProto.Map.entry:type_name -> googlesql.ValueProto.MapEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_googlesql_public_value_proto_init() }
func file_googlesql_public_value_proto_init() {
	if File_googlesql_public_value_proto != nil {
		return
	}
	file_googlesql_public_value_proto_msgTypes[0].OneofWrappers = []any{
		(*ValueProto_Int32Value)(nil),
		(*ValueProto_Int64Value)(nil),
		(*ValueProto_Uint32Value)(nil),
		(*ValueProto_Uint64Value)(nil),
		(*ValueProto_BoolValue)(nil),
		(*ValueProto_FloatValue)(nil),
		(*ValueProto_DoubleValue)(nil),
		(*ValueProto_StringValue)(nil),
		(*ValueProto_BytesValue)(nil),
		(*ValueProto_DateValue)(nil),
		(*ValueProto_EnumValue)(nil),
		(*ValueProto_ArrayValue)(nil),
		(*ValueProto_StructValue)(nil),
		(*ValueProto_ProtoValue)(nil),
		(*ValueProto_TimestampValue)(nil),
		(*ValueProto_TimestampPicoValue)(nil),
		(*ValueProto_TimestampPicosValue)(nil),
		(*ValueProto_DatetimeValue)(nil),
		(*ValueProto_TimeValue)(nil),
		(*ValueProto_GeographyValue)(nil),
		(*ValueProto_NumericValue)(nil),
		(*ValueProto_BignumericValue)(nil),
		(*ValueProto_JsonValue)(nil),
		(*ValueProto_IntervalValue)(nil),
		(*ValueProto_TokenlistValue)(nil),
		(*ValueProto_RangeValue)(nil),
		(*ValueProto_UuidValue)(nil),
		(*ValueProto_MapValue)(nil),
		(*ValueProto_X_ValueProto_SwitchMustHaveADefault)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_value_proto_rawDesc), len(file_googlesql_public_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_value_proto_goTypes,
		DependencyIndexes: file_googlesql_public_value_proto_depIdxs,
		MessageInfos:      file_googlesql_public_value_proto_msgTypes,
	}.Build()
	File_googlesql_public_value_proto = out.File
	file_googlesql_public_value_proto_goTypes = nil
	file_googlesql_public_value_proto_depIdxs = nil
}
