//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/compliance/compliance_label.proto

package googlesql_compliance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComplianceTestsLabels struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	TestCases     []*ComplianceTestCaseLabels `protobuf:"bytes,1,rep,name=test_cases,json=testCases" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceTestsLabels) Reset() {
	*x = ComplianceTestsLabels{}
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceTestsLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceTestsLabels) ProtoMessage() {}

func (x *ComplianceTestsLabels) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceTestsLabels.ProtoReflect.Descriptor instead.
func (*ComplianceTestsLabels) Descriptor() ([]byte, []int) {
	return file_googlesql_compliance_compliance_label_proto_rawDescGZIP(), []int{0}
}

func (x *ComplianceTestsLabels) GetTestCases() []*ComplianceTestCaseLabels {
	if x != nil {
		return x.TestCases
	}
	return nil
}

// Information about each test case containing extracted label
type ComplianceTestCaseLabels struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TestName  *string                `protobuf:"bytes,1,opt,name=test_name,json=testName" json:"test_name,omitempty"`
	TestQuery *string                `protobuf:"bytes,2,opt,name=test_query,json=testQuery" json:"test_query,omitempty"`
	// Params are useful to repro failing queries identified in the report.
	Param            []*ComplianceTestCaseLabels_Param `protobuf:"bytes,7,rep,name=param" json:"param,omitempty"`
	TestErrorMode    *KnownErrorMode                   `protobuf:"varint,3,opt,name=test_error_mode,json=testErrorMode,enum=googlesql.KnownErrorMode" json:"test_error_mode,omitempty"`
	ComplianceLabels []string                          `protobuf:"bytes,4,rep,name=compliance_labels,json=complianceLabels" json:"compliance_labels,omitempty"`
	// This field was added for debugging the compliance reporting tool. We see
	// duplicate test names, and this should help us learn if the tests in
	// are duplicates in the same shard or across different shards.
	TestShard *int64 `protobuf:"varint,8,opt,name=test_shard,json=testShard" json:"test_shard,omitempty"`
	// This string encodes the file name and line for compliance based tests.
	// We are including it to help locate file based test cases.
	TestLocation  *ComplianceTestCaseLabels_Location `protobuf:"bytes,9,opt,name=test_location,json=testLocation" json:"test_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceTestCaseLabels) Reset() {
	*x = ComplianceTestCaseLabels{}
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceTestCaseLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceTestCaseLabels) ProtoMessage() {}

func (x *ComplianceTestCaseLabels) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceTestCaseLabels.ProtoReflect.Descriptor instead.
func (*ComplianceTestCaseLabels) Descriptor() ([]byte, []int) {
	return file_googlesql_compliance_compliance_label_proto_rawDescGZIP(), []int{1}
}

func (x *ComplianceTestCaseLabels) GetTestName() string {
	if x != nil && x.TestName != nil {
		return *x.TestName
	}
	return ""
}

func (x *ComplianceTestCaseLabels) GetTestQuery() string {
	if x != nil && x.TestQuery != nil {
		return *x.TestQuery
	}
	return ""
}

func (x *ComplianceTestCaseLabels) GetParam() []*ComplianceTestCaseLabels_Param {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *ComplianceTestCaseLabels) GetTestErrorMode() KnownErrorMode {
	if x != nil && x.TestErrorMode != nil {
		return *x.TestErrorMode
	}
	return KnownErrorMode_NONE
}

func (x *ComplianceTestCaseLabels) GetComplianceLabels() []string {
	if x != nil {
		return x.ComplianceLabels
	}
	return nil
}

func (x *ComplianceTestCaseLabels) GetTestShard() int64 {
	if x != nil && x.TestShard != nil {
		return *x.TestShard
	}
	return 0
}

func (x *ComplianceTestCaseLabels) GetTestLocation() *ComplianceTestCaseLabels_Location {
	if x != nil {
		return x.TestLocation
	}
	return nil
}

// A query parameter supplied to a test statement.
type ComplianceTestCaseLabels_Param struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParamName         *string                `protobuf:"bytes,1,opt,name=param_name,json=paramName" json:"param_name,omitempty"`
	ParamValueLiteral *string                `protobuf:"bytes,2,opt,name=param_value_literal,json=paramValueLiteral" json:"param_value_literal,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ComplianceTestCaseLabels_Param) Reset() {
	*x = ComplianceTestCaseLabels_Param{}
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceTestCaseLabels_Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceTestCaseLabels_Param) ProtoMessage() {}

func (x *ComplianceTestCaseLabels_Param) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceTestCaseLabels_Param.ProtoReflect.Descriptor instead.
func (*ComplianceTestCaseLabels_Param) Descriptor() ([]byte, []int) {
	return file_googlesql_compliance_compliance_label_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ComplianceTestCaseLabels_Param) GetParamName() string {
	if x != nil && x.ParamName != nil {
		return *x.ParamName
	}
	return ""
}

func (x *ComplianceTestCaseLabels_Param) GetParamValueLiteral() string {
	if x != nil && x.ParamValueLiteral != nil {
		return *x.ParamValueLiteral
	}
	return ""
}

// The location of a test statement in the repository.
type ComplianceTestCaseLabels_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *string                `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Line          *int32                 `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceTestCaseLabels_Location) Reset() {
	*x = ComplianceTestCaseLabels_Location{}
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceTestCaseLabels_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceTestCaseLabels_Location) ProtoMessage() {}

func (x *ComplianceTestCaseLabels_Location) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_compliance_compliance_label_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceTestCaseLabels_Location.ProtoReflect.Descriptor instead.
func (*ComplianceTestCaseLabels_Location) Descriptor() ([]byte, []int) {
	return file_googlesql_compliance_compliance_label_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ComplianceTestCaseLabels_Location) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

func (x *ComplianceTestCaseLabels_Location) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

var File_googlesql_compliance_compliance_label_proto protoreflect.FileDescriptor

const file_googlesql_compliance_compliance_label_proto_rawDesc = "" +
	"\n" +
	"+googlesql/compliance/compliance_label.proto\x12\tgooglesql\x1a&googlesql/compliance/known_error.proto\"[\n" +
	"\x15ComplianceTestsLabels\x12B\n" +
	"\n" +
	"test_cases\x18\x01 \x03(\v2#.googlesql.ComplianceTestCaseLabelsR\ttestCases\"\x85\x04\n" +
	"\x18ComplianceTestCaseLabels\x12\x1b\n" +
	"\ttest_name\x18\x01 \x01(\tR\btestName\x12\x1d\n" +
	"\n" +
	"test_query\x18\x02 \x01(\tR\ttestQuery\x12?\n" +
	"\x05param\x18\a \x03(\v2).googlesql.ComplianceTestCaseLabels.ParamR\x05param\x12A\n" +
	"\x0ftest_error_mode\x18\x03 \x01(\x0e2\x19.googlesql.KnownErrorModeR\rtestErrorMode\x12+\n" +
	"\x11compliance_labels\x18\x04 \x03(\tR\x10complianceLabels\x12\x1d\n" +
	"\n" +
	"test_shard\x18\b \x01(\x03R\ttestShard\x12Q\n" +
	"\rtest_location\x18\t \x01(\v2,.googlesql.ComplianceTestCaseLabels.LocationR\ftestLocation\x1aV\n" +
	"\x05Param\x12\x1d\n" +
	"\n" +
	"param_name\x18\x01 \x01(\tR\tparamName\x12.\n" +
	"\x13param_value_literal\x18\x02 \x01(\tR\x11paramValueLiteral\x1a2\n" +
	"\bLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line"

var (
	file_googlesql_compliance_compliance_label_proto_rawDescOnce sync.Once
	file_googlesql_compliance_compliance_label_proto_rawDescData []byte
)

func file_googlesql_compliance_compliance_label_proto_rawDescGZIP() []byte {
	file_googlesql_compliance_compliance_label_proto_rawDescOnce.Do(func() {
		file_googlesql_compliance_compliance_label_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_compliance_compliance_label_proto_rawDesc), len(file_googlesql_compliance_compliance_label_proto_rawDesc)))
	})
	return file_googlesql_compliance_compliance_label_proto_rawDescData
}

var file_googlesql_compliance_compliance_label_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_googlesql_compliance_compliance_label_proto_goTypes = []any{
	(*ComplianceTestsLabels)(nil),             // 0: googlesql.ComplianceTestsLabels
	(*ComplianceTestCaseLabels)(nil),          // 1: googlesql.ComplianceTestCaseLabels
	(*ComplianceTestCaseLabels_Param)(nil),    // 2: googlesql.ComplianceTestCaseLabels.Param
	(*ComplianceTestCaseLabels_Location)(nil), // 3: googlesql.ComplianceTestCaseLabels.Location
	(KnownErrorMode)(0),                       // 4: googlesql.KnownErrorMode
}
var file_googlesql_compliance_compliance_label_proto_depIdxs = []int32{
	1, // 0: googlesql.ComplianceTestsLabels.test_cases:type_name -> googlesql.ComplianceTestCaseLabels
	2, // 1: googlesql.ComplianceTestCaseLabels.param:type_name -> googlesql.ComplianceTestCaseLabels.Param
	4, // 2: googlesql.ComplianceTestCaseLabels.test_error_mode:type_name -> googlesql.KnownErrorMode
	3, // 3: googlesql.ComplianceTestCaseLabels.test_location:type_name -> googlesql.ComplianceTestCaseLabels.Location
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_googlesql_compliance_compliance_label_proto_init() }
func file_googlesql_compliance_compliance_label_proto_init() {
	if File_googlesql_compliance_compliance_label_proto != nil {
		return
	}
	file_googlesql_compliance_known_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_compliance_compliance_label_proto_rawDesc), len(file_googlesql_compliance_compliance_label_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_compliance_compliance_label_proto_goTypes,
		DependencyIndexes: file_googlesql_compliance_compliance_label_proto_depIdxs,
		MessageInfos:      file_googlesql_compliance_compliance_label_proto_msgTypes,
	}.Build()
	File_googlesql_compliance_compliance_label_proto = out.File
	file_googlesql_compliance_compliance_label_proto_goTypes = nil
	file_googlesql_compliance_compliance_label_proto_depIdxs = nil
}
