//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Definition of GoogleSQL "known error" protocol buffer. Used to parse
// known error files into protocol buffers. By convention, these are named
// "<engine>_known_error.textproto".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/compliance/known_error.proto

package googlesql_compliance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Known error modes. By default the compliance framework skips all modes of
// queries with known error entries.
// Use --sql_e2e_test_all to run all but queries in modes CRASHES_DO_NOT_RUN.
// Modes are ordered by severity. If a label appears in multiple known error
// lists, the label's mode is the highest one.
type KnownErrorMode int32

const (
	// Reserves zero value to enable natural conversion from mode to a boolean
	// where 0 = false means no error is known and non-zero values = true means
	// an error is known and expected. The zero value is not supposed to be used.
	KnownErrorMode_NONE                        KnownErrorMode = 0
	KnownErrorMode_ALLOW_UNIMPLEMENTED         KnownErrorMode = 10
	KnownErrorMode_ALLOW_ERROR                 KnownErrorMode = 20
	KnownErrorMode_ALLOW_ERROR_OR_WRONG_ANSWER KnownErrorMode = 30
	KnownErrorMode_CRASHES_DO_NOT_RUN          KnownErrorMode = 100
)

// Enum value maps for KnownErrorMode.
var (
	KnownErrorMode_name = map[int32]string{
		0:   "NONE",
		10:  "ALLOW_UNIMPLEMENTED",
		20:  "ALLOW_ERROR",
		30:  "ALLOW_ERROR_OR_WRONG_ANSWER",
		100: "CRASHES_DO_NOT_RUN",
	}
	KnownErrorMode_value = map[string]int32{
		"NONE":                        0,
		"ALLOW_UNIMPLEMENTED":         10,
		"ALLOW_ERROR":                 20,
		"ALLOW_ERROR_OR_WRONG_ANSWER": 30,
		"CRASHES_DO_NOT_RUN":          100,
	}
)

func (x KnownErrorMode) Enum() *KnownErrorMode {
	p := new(KnownErrorMode)
	*p = x
	return p
}

func (x KnownErrorMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KnownErrorMode) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_compliance_known_error_proto_enumTypes[0].Descriptor()
}

func (KnownErrorMode) Type() protoreflect.EnumType {
	return &file_googlesql_compliance_known_error_proto_enumTypes[0]
}

func (x KnownErrorMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *KnownErrorMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = KnownErrorMode(num)
	return nil
}

// Deprecated: Use KnownErrorMode.Descriptor instead.
func (KnownErrorMode) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_compliance_known_error_proto_rawDescGZIP(), []int{0}
}

type KnownErrorEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  *KnownErrorMode        `protobuf:"varint,3,opt,name=mode,enum=googlesql.KnownErrorMode,def=30" json:"mode,omitempty"`
	// The reason for the error, e.g., a bug.
	Reason *string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	// A label can be one defined in *.test files, or a query referred by
	// <filename>:<query_name>. A label can also be a RE2 regex that matches
	// a group of labels.
	Label         []string `protobuf:"bytes,2,rep,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for KnownErrorEntry fields.
const (
	Default_KnownErrorEntry_Mode = KnownErrorMode_ALLOW_ERROR_OR_WRONG_ANSWER
)

func (x *KnownErrorEntry) Reset() {
	*x = KnownErrorEntry{}
	mi := &file_googlesql_compliance_known_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownErrorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownErrorEntry) ProtoMessage() {}

func (x *KnownErrorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_compliance_known_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownErrorEntry.ProtoReflect.Descriptor instead.
func (*KnownErrorEntry) Descriptor() ([]byte, []int) {
	return file_googlesql_compliance_known_error_proto_rawDescGZIP(), []int{0}
}

func (x *KnownErrorEntry) GetMode() KnownErrorMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return Default_KnownErrorEntry_Mode
}

func (x *KnownErrorEntry) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *KnownErrorEntry) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

type KnownErrorFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lists of contacts for maintaining this list.
	ContactEmail []string `protobuf:"bytes,1,rep,name=contact_email,json=contactEmail" json:"contact_email,omitempty"`
	// A group of known error lists. It's recommended to define a `known_errors`
	// section for each unsupported functionality, bug, change list, etc.
	KnownErrors   []*KnownErrorEntry `protobuf:"bytes,2,rep,name=known_errors,json=knownErrors" json:"known_errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownErrorFile) Reset() {
	*x = KnownErrorFile{}
	mi := &file_googlesql_compliance_known_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownErrorFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownErrorFile) ProtoMessage() {}

func (x *KnownErrorFile) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_compliance_known_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownErrorFile.ProtoReflect.Descriptor instead.
func (*KnownErrorFile) Descriptor() ([]byte, []int) {
	return file_googlesql_compliance_known_error_proto_rawDescGZIP(), []int{1}
}

func (x *KnownErrorFile) GetContactEmail() []string {
	if x != nil {
		return x.ContactEmail
	}
	return nil
}

func (x *KnownErrorFile) GetKnownErrors() []*KnownErrorEntry {
	if x != nil {
		return x.KnownErrors
	}
	return nil
}

var File_googlesql_compliance_known_error_proto protoreflect.FileDescriptor

const file_googlesql_compliance_known_error_proto_rawDesc = "" +
	"\n" +
	"&googlesql/compliance/known_error.proto\x12\tgooglesql\"\x8b\x01\n" +
	"\x0fKnownErrorEntry\x12J\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x19.googlesql.KnownErrorMode:\x1bALLOW_ERROR_OR_WRONG_ANSWERR\x04mode\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x14\n" +
	"\x05label\x18\x02 \x03(\tR\x05label\"t\n" +
	"\x0eKnownErrorFile\x12#\n" +
	"\rcontact_email\x18\x01 \x03(\tR\fcontactEmail\x12=\n" +
	"\fknown_errors\x18\x02 \x03(\v2\x1a.googlesql.KnownErrorEntryR\vknownErrors*}\n" +
	"\x0eKnownErrorMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\x17\n" +
	"\x13ALLOW_UNIMPLEMENTED\x10\n" +
	"\x12\x0f\n" +
	"\vALLOW_ERROR\x10\x14\x12\x1f\n" +
	"\x1bALLOW_ERROR_OR_WRONG_ANSWER\x10\x1e\x12\x16\n" +
	"\x12CRASHES_DO_NOT_RUN\x10d"

var (
	file_googlesql_compliance_known_error_proto_rawDescOnce sync.Once
	file_googlesql_compliance_known_error_proto_rawDescData []byte
)

func file_googlesql_compliance_known_error_proto_rawDescGZIP() []byte {
	file_googlesql_compliance_known_error_proto_rawDescOnce.Do(func() {
		file_googlesql_compliance_known_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_compliance_known_error_proto_rawDesc), len(file_googlesql_compliance_known_error_proto_rawDesc)))
	})
	return file_googlesql_compliance_known_error_proto_rawDescData
}

var file_googlesql_compliance_known_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_googlesql_compliance_known_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_googlesql_compliance_known_error_proto_goTypes = []any{
	(KnownErrorMode)(0),     // 0: googlesql.KnownErrorMode
	(*KnownErrorEntry)(nil), // 1: googlesql.KnownErrorEntry
	(*KnownErrorFile)(nil),  // 2: googlesql.KnownErrorFile
}
var file_googlesql_compliance_known_error_proto_depIdxs = []int32{
	0, // 0: googlesql.KnownErrorEntry.mode:type_name -> googlesql.KnownErrorMode
	1, // 1: googlesql.KnownErrorFile.known_errors:type_name -> googlesql.KnownErrorEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_googlesql_compliance_known_error_proto_init() }
func file_googlesql_compliance_known_error_proto_init() {
	if File_googlesql_compliance_known_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_compliance_known_error_proto_rawDesc), len(file_googlesql_compliance_known_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_compliance_known_error_proto_goTypes,
		DependencyIndexes: file_googlesql_compliance_known_error_proto_depIdxs,
		EnumInfos:         file_googlesql_compliance_known_error_proto_enumTypes,
		MessageInfos:      file_googlesql_compliance_known_error_proto_msgTypes,
	}.Build()
	File_googlesql_compliance_known_error_proto = out.File
	file_googlesql_compliance_known_error_proto_goTypes = nil
	file_googlesql_compliance_known_error_proto_depIdxs = nil
}
