//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/functions/array_zip_mode.proto

package googlesql_public_functions

import (
	_ "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArrayZipEnums_ArrayZipMode int32

const (
	// Invalid in GoogleSQL.
	ArrayZipEnums_ARRAY_ZIP_MODE_INVALID ArrayZipEnums_ArrayZipMode = 0
	// Pad all arrays shorter than the longest one with NULL, so that
	// padded_array_length = GREATEST(ARRAY_LENGTH(array1),
	// ARRAY_LENGTH(array2), ..., ARRAY_LENGTH(arrayN))
	ArrayZipEnums_PAD ArrayZipEnums_ArrayZipMode = 1
	// Truncate all arrays longer than the shortest one before zipping, so that
	// truncated_array_length = LEAST(ARRAY_LENGTH(array1),
	// ARRAY_LENGTH(array2), ..., ARRAY_LENGTH(arrayN))
	ArrayZipEnums_TRUNCATE ArrayZipEnums_ArrayZipMode = 2
	// If the length of any of the ARRAY arguments is different from the others,
	// throw an error.
	ArrayZipEnums_STRICT ArrayZipEnums_ArrayZipMode = 3
)

// Enum value maps for ArrayZipEnums_ArrayZipMode.
var (
	ArrayZipEnums_ArrayZipMode_name = map[int32]string{
		0: "ARRAY_ZIP_MODE_INVALID",
		1: "PAD",
		2: "TRUNCATE",
		3: "STRICT",
	}
	ArrayZipEnums_ArrayZipMode_value = map[string]int32{
		"ARRAY_ZIP_MODE_INVALID": 0,
		"PAD":                    1,
		"TRUNCATE":               2,
		"STRICT":                 3,
	}
)

func (x ArrayZipEnums_ArrayZipMode) Enum() *ArrayZipEnums_ArrayZipMode {
	p := new(ArrayZipEnums_ArrayZipMode)
	*p = x
	return p
}

func (x ArrayZipEnums_ArrayZipMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArrayZipEnums_ArrayZipMode) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_functions_array_zip_mode_proto_enumTypes[0].Descriptor()
}

func (ArrayZipEnums_ArrayZipMode) Type() protoreflect.EnumType {
	return &file_googlesql_public_functions_array_zip_mode_proto_enumTypes[0]
}

func (x ArrayZipEnums_ArrayZipMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ArrayZipEnums_ArrayZipMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ArrayZipEnums_ArrayZipMode(num)
	return nil
}

// Deprecated: Use ArrayZipEnums_ArrayZipMode.Descriptor instead.
func (ArrayZipEnums_ArrayZipMode) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_functions_array_zip_mode_proto_rawDescGZIP(), []int{0, 0}
}

// Enum that defines the how arrays are "zipped" together when there are
// multiple arrays of different lengths.
// Currently the enum is used by:
// - ARRAY_ZIP function
// - UNNEST operator with at least two arrays inputs
// ARRAY_ZIP_MODE can only be used as specific function call argument, instead
// of standalone expression.
// See (broken link).
type ArrayZipEnums struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayZipEnums) Reset() {
	*x = ArrayZipEnums{}
	mi := &file_googlesql_public_functions_array_zip_mode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayZipEnums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayZipEnums) ProtoMessage() {}

func (x *ArrayZipEnums) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_array_zip_mode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayZipEnums.ProtoReflect.Descriptor instead.
func (*ArrayZipEnums) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_array_zip_mode_proto_rawDescGZIP(), []int{0}
}

var File_googlesql_public_functions_array_zip_mode_proto protoreflect.FileDescriptor

const file_googlesql_public_functions_array_zip_mode_proto_rawDesc = "" +
	"\n" +
	"/googlesql/public/functions/array_zip_mode.proto\x12\x13googlesql.functions\x1a\x1bgooglesql/public/type.proto\"\x80\x01\n" +
	"\rArrayZipEnums\"o\n" +
	"\fArrayZipMode\x12$\n" +
	"\x16ARRAY_ZIP_MODE_INVALID\x10\x00\x1a\b\xb2\xf2\xb0\x92\x0e\x02\b\x01\x12\a\n" +
	"\x03PAD\x10\x01\x12\f\n" +
	"\bTRUNCATE\x10\x02\x12\n" +
	"\n" +
	"\x06STRICT\x10\x03\x1a\x16\xb2Я\xfa\r\x10\n" +
	"\x0eARRAY_ZIP_MODEB7\n" +
	"\x1ecom.google.googlesql.functionsB\x15GoogleSQLArrayZipMode"

var (
	file_googlesql_public_functions_array_zip_mode_proto_rawDescOnce sync.Once
	file_googlesql_public_functions_array_zip_mode_proto_rawDescData []byte
)

func file_googlesql_public_functions_array_zip_mode_proto_rawDescGZIP() []byte {
	file_googlesql_public_functions_array_zip_mode_proto_rawDescOnce.Do(func() {
		file_googlesql_public_functions_array_zip_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_functions_array_zip_mode_proto_rawDesc), len(file_googlesql_public_functions_array_zip_mode_proto_rawDesc)))
	})
	return file_googlesql_public_functions_array_zip_mode_proto_rawDescData
}

var file_googlesql_public_functions_array_zip_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_googlesql_public_functions_array_zip_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_googlesql_public_functions_array_zip_mode_proto_goTypes = []any{
	(ArrayZipEnums_ArrayZipMode)(0), // 0: googlesql.functions.ArrayZipEnums.ArrayZipMode
	(*ArrayZipEnums)(nil),           // 1: googlesql.functions.ArrayZipEnums
}
var file_googlesql_public_functions_array_zip_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_functions_array_zip_mode_proto_init() }
func file_googlesql_public_functions_array_zip_mode_proto_init() {
	if File_googlesql_public_functions_array_zip_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_functions_array_zip_mode_proto_rawDesc), len(file_googlesql_public_functions_array_zip_mode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_functions_array_zip_mode_proto_goTypes,
		DependencyIndexes: file_googlesql_public_functions_array_zip_mode_proto_depIdxs,
		EnumInfos:         file_googlesql_public_functions_array_zip_mode_proto_enumTypes,
		MessageInfos:      file_googlesql_public_functions_array_zip_mode_proto_msgTypes,
	}.Build()
	File_googlesql_public_functions_array_zip_mode_proto = out.File
	file_googlesql_public_functions_array_zip_mode_proto_goTypes = nil
	file_googlesql_public_functions_array_zip_mode_proto_depIdxs = nil
}
