//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/functions/differential_privacy.proto

package googlesql_public_functions

import (
	googlesql_core "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_core"
	_ "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum that defines the output format of differential privacy functions that
// return report. See:
//
//	Detailed report description: (broken link).
//	Updated report syntax:  (broken link).
type DifferentialPrivacyEnums_ReportFormat int32

const (
	// Invalid in GoogleSQL.
	DifferentialPrivacyEnums_DIFFERENTIAL_PRIVACY_REPORT_FORMAT_INVALID DifferentialPrivacyEnums_ReportFormat = 0
	// Report output format is JSON.
	DifferentialPrivacyEnums_JSON DifferentialPrivacyEnums_ReportFormat = 1
	// Report output format is proto.
	DifferentialPrivacyEnums_PROTO DifferentialPrivacyEnums_ReportFormat = 2
)

// Enum value maps for DifferentialPrivacyEnums_ReportFormat.
var (
	DifferentialPrivacyEnums_ReportFormat_name = map[int32]string{
		0: "DIFFERENTIAL_PRIVACY_REPORT_FORMAT_INVALID",
		1: "JSON",
		2: "PROTO",
	}
	DifferentialPrivacyEnums_ReportFormat_value = map[string]int32{
		"DIFFERENTIAL_PRIVACY_REPORT_FORMAT_INVALID": 0,
		"JSON":  1,
		"PROTO": 2,
	}
)

func (x DifferentialPrivacyEnums_ReportFormat) Enum() *DifferentialPrivacyEnums_ReportFormat {
	p := new(DifferentialPrivacyEnums_ReportFormat)
	*p = x
	return p
}

func (x DifferentialPrivacyEnums_ReportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DifferentialPrivacyEnums_ReportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_functions_differential_privacy_proto_enumTypes[0].Descriptor()
}

func (DifferentialPrivacyEnums_ReportFormat) Type() protoreflect.EnumType {
	return &file_googlesql_public_functions_differential_privacy_proto_enumTypes[0]
}

func (x DifferentialPrivacyEnums_ReportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DifferentialPrivacyEnums_ReportFormat) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DifferentialPrivacyEnums_ReportFormat(num)
	return nil
}

// Deprecated: Use DifferentialPrivacyEnums_ReportFormat.Descriptor instead.
func (DifferentialPrivacyEnums_ReportFormat) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{0, 0}
}

// Enum representing the group selection strategy that can be passed by the
// user in the anonymization options.  LAPLACE_THRESHOLD is the default group
// selection strategy.
//
// See (broken link).
type DifferentialPrivacyEnums_GroupSelectionStrategy int32

const (
	DifferentialPrivacyEnums_DIFFERENTIAL_PRIVACY_GROUP_SELECTION_STRATEGY_INVALID DifferentialPrivacyEnums_GroupSelectionStrategy = 0
	DifferentialPrivacyEnums_LAPLACE_THRESHOLD                                     DifferentialPrivacyEnums_GroupSelectionStrategy = 1
	DifferentialPrivacyEnums_PUBLIC_GROUPS                                         DifferentialPrivacyEnums_GroupSelectionStrategy = 2
)

// Enum value maps for DifferentialPrivacyEnums_GroupSelectionStrategy.
var (
	DifferentialPrivacyEnums_GroupSelectionStrategy_name = map[int32]string{
		0: "DIFFERENTIAL_PRIVACY_GROUP_SELECTION_STRATEGY_INVALID",
		1: "LAPLACE_THRESHOLD",
		2: "PUBLIC_GROUPS",
	}
	DifferentialPrivacyEnums_GroupSelectionStrategy_value = map[string]int32{
		"DIFFERENTIAL_PRIVACY_GROUP_SELECTION_STRATEGY_INVALID": 0,
		"LAPLACE_THRESHOLD": 1,
		"PUBLIC_GROUPS":     2,
	}
)

func (x DifferentialPrivacyEnums_GroupSelectionStrategy) Enum() *DifferentialPrivacyEnums_GroupSelectionStrategy {
	p := new(DifferentialPrivacyEnums_GroupSelectionStrategy)
	*p = x
	return p
}

func (x DifferentialPrivacyEnums_GroupSelectionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DifferentialPrivacyEnums_GroupSelectionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_functions_differential_privacy_proto_enumTypes[1].Descriptor()
}

func (DifferentialPrivacyEnums_GroupSelectionStrategy) Type() protoreflect.EnumType {
	return &file_googlesql_public_functions_differential_privacy_proto_enumTypes[1]
}

func (x DifferentialPrivacyEnums_GroupSelectionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DifferentialPrivacyEnums_GroupSelectionStrategy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DifferentialPrivacyEnums_GroupSelectionStrategy(num)
	return nil
}

// Deprecated: Use DifferentialPrivacyEnums_GroupSelectionStrategy.Descriptor instead.
func (DifferentialPrivacyEnums_GroupSelectionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{0, 1}
}

// Enum that represents the contribution_bounding strategy for differentially
// private count distinct. For details, see
// (broken link).
type DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy int32

const (
	DifferentialPrivacyEnums_DIFFERENTIAL_PRIVACY_COUNT_DISTINCT_CONTRIBUTION_BOUNDING_STRATEGY_INVALID DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy = 0
	DifferentialPrivacyEnums_AUTO                                                                       DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy = 1
	DifferentialPrivacyEnums_SAMPLING                                                                   DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy = 2
	DifferentialPrivacyEnums_GREEDY                                                                     DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy = 3
	DifferentialPrivacyEnums_MATCHING                                                                   DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy = 4
)

// Enum value maps for DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy.
var (
	DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy_name = map[int32]string{
		0: "DIFFERENTIAL_PRIVACY_COUNT_DISTINCT_CONTRIBUTION_BOUNDING_STRATEGY_INVALID",
		1: "AUTO",
		2: "SAMPLING",
		3: "GREEDY",
		4: "MATCHING",
	}
	DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy_value = map[string]int32{
		"DIFFERENTIAL_PRIVACY_COUNT_DISTINCT_CONTRIBUTION_BOUNDING_STRATEGY_INVALID": 0,
		"AUTO":     1,
		"SAMPLING": 2,
		"GREEDY":   3,
		"MATCHING": 4,
	}
)

func (x DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) Enum() *DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy {
	p := new(DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy)
	*p = x
	return p
}

func (x DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_functions_differential_privacy_proto_enumTypes[2].Descriptor()
}

func (DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) Type() protoreflect.EnumType {
	return &file_googlesql_public_functions_differential_privacy_proto_enumTypes[2]
}

func (x DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy(num)
	return nil
}

// Deprecated: Use DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy.Descriptor instead.
func (DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{0, 2}
}

type DifferentialPrivacyEnums struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferentialPrivacyEnums) Reset() {
	*x = DifferentialPrivacyEnums{}
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyEnums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyEnums) ProtoMessage() {}

func (x *DifferentialPrivacyEnums) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialPrivacyEnums.ProtoReflect.Descriptor instead.
func (*DifferentialPrivacyEnums) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{0}
}

// Contains output from a GoogleSQL differential privacy function.
type DifferentialPrivacyOutputWithReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*DifferentialPrivacyOutputWithReport_Value
	//	*DifferentialPrivacyOutputWithReport_Values
	Result isDifferentialPrivacyOutputWithReport_Result `protobuf_oneof:"result"`
	// Types that are valid to be assigned to Report:
	//
	//	*DifferentialPrivacyOutputWithReport_BoundingReport
	//	*DifferentialPrivacyOutputWithReport_CountDistinctBoundingReport
	Report        isDifferentialPrivacyOutputWithReport_Report `protobuf_oneof:"report"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferentialPrivacyOutputWithReport) Reset() {
	*x = DifferentialPrivacyOutputWithReport{}
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyOutputWithReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyOutputWithReport) ProtoMessage() {}

func (x *DifferentialPrivacyOutputWithReport) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialPrivacyOutputWithReport.ProtoReflect.Descriptor instead.
func (*DifferentialPrivacyOutputWithReport) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{1}
}

func (x *DifferentialPrivacyOutputWithReport) GetResult() isDifferentialPrivacyOutputWithReport_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DifferentialPrivacyOutputWithReport) GetValue() *DifferentialPrivacyOutputValue {
	if x != nil {
		if x, ok := x.Result.(*DifferentialPrivacyOutputWithReport_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *DifferentialPrivacyOutputWithReport) GetValues() *DifferentialPrivacyOutputValues {
	if x != nil {
		if x, ok := x.Result.(*DifferentialPrivacyOutputWithReport_Values); ok {
			return x.Values
		}
	}
	return nil
}

func (x *DifferentialPrivacyOutputWithReport) GetReport() isDifferentialPrivacyOutputWithReport_Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *DifferentialPrivacyOutputWithReport) GetBoundingReport() *DifferentialPrivacyBoundingReport {
	if x != nil {
		if x, ok := x.Report.(*DifferentialPrivacyOutputWithReport_BoundingReport); ok {
			return x.BoundingReport
		}
	}
	return nil
}

func (x *DifferentialPrivacyOutputWithReport) GetCountDistinctBoundingReport() *DifferentiallyPrivateCountDistinctBoundingReport {
	if x != nil {
		if x, ok := x.Report.(*DifferentialPrivacyOutputWithReport_CountDistinctBoundingReport); ok {
			return x.CountDistinctBoundingReport
		}
	}
	return nil
}

type isDifferentialPrivacyOutputWithReport_Result interface {
	isDifferentialPrivacyOutputWithReport_Result()
}

type DifferentialPrivacyOutputWithReport_Value struct {
	Value *DifferentialPrivacyOutputValue `protobuf:"bytes,1,opt,name=value,oneof"`
}

type DifferentialPrivacyOutputWithReport_Values struct {
	Values *DifferentialPrivacyOutputValues `protobuf:"bytes,2,opt,name=values,oneof"`
}

func (*DifferentialPrivacyOutputWithReport_Value) isDifferentialPrivacyOutputWithReport_Result() {}

func (*DifferentialPrivacyOutputWithReport_Values) isDifferentialPrivacyOutputWithReport_Result() {}

type isDifferentialPrivacyOutputWithReport_Report interface {
	isDifferentialPrivacyOutputWithReport_Report()
}

type DifferentialPrivacyOutputWithReport_BoundingReport struct {
	BoundingReport *DifferentialPrivacyBoundingReport `protobuf:"bytes,3,opt,name=bounding_report,json=boundingReport,oneof"`
}

type DifferentialPrivacyOutputWithReport_CountDistinctBoundingReport struct {
	CountDistinctBoundingReport *DifferentiallyPrivateCountDistinctBoundingReport `protobuf:"bytes,4,opt,name=count_distinct_bounding_report,json=countDistinctBoundingReport,oneof"`
}

func (*DifferentialPrivacyOutputWithReport_BoundingReport) isDifferentialPrivacyOutputWithReport_Report() {
}

func (*DifferentialPrivacyOutputWithReport_CountDistinctBoundingReport) isDifferentialPrivacyOutputWithReport_Report() {
}

// When ApproxBounds is called by bounded algorithms, the BoundingReport can
// be used to pass differentially private intermediate results to help users
// understand the accuracy implications of the output.
type DifferentialPrivacyBoundingReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lower and upper bounds are either the explicit bounds specified in the
	// query, or are the (noisy) implicit bounds that were derived by the
	// ApproxBounds algorithm.
	LowerBound *DifferentialPrivacyOutputValue `protobuf:"bytes,1,opt,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	UpperBound *DifferentialPrivacyOutputValue `protobuf:"bytes,2,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	// `num_inputs` and `num_outside` in the BoundingReport are *noisy*
	// counts, not exact.
	// Noisy number of total inputs to the bounding algorithm.
	NumInputs *float64 `protobuf:"fixed64,3,opt,name=num_inputs,json=numInputs" json:"num_inputs,omitempty"`
	// Noisy number of inputs lying outside the bounds.
	NumOutside    *float64 `protobuf:"fixed64,4,opt,name=num_outside,json=numOutside" json:"num_outside,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferentialPrivacyBoundingReport) Reset() {
	*x = DifferentialPrivacyBoundingReport{}
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyBoundingReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyBoundingReport) ProtoMessage() {}

func (x *DifferentialPrivacyBoundingReport) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialPrivacyBoundingReport.ProtoReflect.Descriptor instead.
func (*DifferentialPrivacyBoundingReport) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{2}
}

func (x *DifferentialPrivacyBoundingReport) GetLowerBound() *DifferentialPrivacyOutputValue {
	if x != nil {
		return x.LowerBound
	}
	return nil
}

func (x *DifferentialPrivacyBoundingReport) GetUpperBound() *DifferentialPrivacyOutputValue {
	if x != nil {
		return x.UpperBound
	}
	return nil
}

func (x *DifferentialPrivacyBoundingReport) GetNumInputs() float64 {
	if x != nil && x.NumInputs != nil {
		return *x.NumInputs
	}
	return 0
}

func (x *DifferentialPrivacyBoundingReport) GetNumOutside() float64 {
	if x != nil && x.NumOutside != nil {
		return *x.NumOutside
	}
	return 0
}

type DifferentiallyPrivateCountDistinctBoundingReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The contribution strategy that was used to bound the contribution of each
	// user. If the contribution bounding strategy is set to `SAMPLING`, `GREEDY`
	// or `MATCHING` in the input, then this field will be set to the same value.
	// If the contribution bounding strategy is set to `AUTO`, then this field
	// will be set to the contribution bounding strategy that was chosen by the
	// algorithm.
	ContributionBoundingStrategy *DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy `protobuf:"varint,1,opt,name=contribution_bounding_strategy,json=contributionBoundingStrategy,enum=googlesql.functions.DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy" json:"contribution_bounding_strategy,omitempty"`
	// The upper bound is either explicitly specified in the query, or is the
	// implicit (noisy) bound derived by the algorithm. There is no lower bound,
	// because it is always zero. In that regard, note that there is no good way
	// to clamp a user to have more distinct values than they have.
	UpperBound *int64 `protobuf:"varint,2,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	// The noisy number of inputs to the bounding algorithm. This is the same as
	// the noisy number of privacy units that contributed to the given
	// partition/group.
	NumInputs     *float64 `protobuf:"fixed64,3,opt,name=num_inputs,json=numInputs" json:"num_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferentiallyPrivateCountDistinctBoundingReport) Reset() {
	*x = DifferentiallyPrivateCountDistinctBoundingReport{}
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentiallyPrivateCountDistinctBoundingReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentiallyPrivateCountDistinctBoundingReport) ProtoMessage() {}

func (x *DifferentiallyPrivateCountDistinctBoundingReport) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentiallyPrivateCountDistinctBoundingReport.ProtoReflect.Descriptor instead.
func (*DifferentiallyPrivateCountDistinctBoundingReport) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{3}
}

func (x *DifferentiallyPrivateCountDistinctBoundingReport) GetContributionBoundingStrategy() DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy {
	if x != nil && x.ContributionBoundingStrategy != nil {
		return *x.ContributionBoundingStrategy
	}
	return DifferentialPrivacyEnums_DIFFERENTIAL_PRIVACY_COUNT_DISTINCT_CONTRIBUTION_BOUNDING_STRATEGY_INVALID
}

func (x *DifferentiallyPrivateCountDistinctBoundingReport) GetUpperBound() int64 {
	if x != nil && x.UpperBound != nil {
		return *x.UpperBound
	}
	return 0
}

func (x *DifferentiallyPrivateCountDistinctBoundingReport) GetNumInputs() float64 {
	if x != nil && x.NumInputs != nil {
		return *x.NumInputs
	}
	return 0
}

type DifferentialPrivacyOutputValues struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Values        []*DifferentialPrivacyOutputValue `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferentialPrivacyOutputValues) Reset() {
	*x = DifferentialPrivacyOutputValues{}
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyOutputValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyOutputValues) ProtoMessage() {}

func (x *DifferentialPrivacyOutputValues) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialPrivacyOutputValues.ProtoReflect.Descriptor instead.
func (*DifferentialPrivacyOutputValues) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{4}
}

func (x *DifferentialPrivacyOutputValues) GetValues() []*DifferentialPrivacyOutputValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type DifferentialPrivacyOutputValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*DifferentialPrivacyOutputValue_IntValue
	//	*DifferentialPrivacyOutputValue_FloatValue
	//	*DifferentialPrivacyOutputValue_StringValue
	Value                   isDifferentialPrivacyOutputValue_Value  `protobuf_oneof:"value"`
	NoiseConfidenceInterval *googlesql_core.NoiseConfidenceInterval `protobuf:"bytes,4,opt,name=noise_confidence_interval,json=noiseConfidenceInterval" json:"noise_confidence_interval,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DifferentialPrivacyOutputValue) Reset() {
	*x = DifferentialPrivacyOutputValue{}
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyOutputValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyOutputValue) ProtoMessage() {}

func (x *DifferentialPrivacyOutputValue) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_functions_differential_privacy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialPrivacyOutputValue.ProtoReflect.Descriptor instead.
func (*DifferentialPrivacyOutputValue) Descriptor() ([]byte, []int) {
	return file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP(), []int{5}
}

func (x *DifferentialPrivacyOutputValue) GetValue() isDifferentialPrivacyOutputValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DifferentialPrivacyOutputValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*DifferentialPrivacyOutputValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *DifferentialPrivacyOutputValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*DifferentialPrivacyOutputValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *DifferentialPrivacyOutputValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*DifferentialPrivacyOutputValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *DifferentialPrivacyOutputValue) GetNoiseConfidenceInterval() *googlesql_core.NoiseConfidenceInterval {
	if x != nil {
		return x.NoiseConfidenceInterval
	}
	return nil
}

type isDifferentialPrivacyOutputValue_Value interface {
	isDifferentialPrivacyOutputValue_Value()
}

type DifferentialPrivacyOutputValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,oneof"`
}

type DifferentialPrivacyOutputValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,2,opt,name=float_value,json=floatValue,oneof"`
}

type DifferentialPrivacyOutputValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,oneof"`
}

func (*DifferentialPrivacyOutputValue_IntValue) isDifferentialPrivacyOutputValue_Value() {}

func (*DifferentialPrivacyOutputValue_FloatValue) isDifferentialPrivacyOutputValue_Value() {}

func (*DifferentialPrivacyOutputValue_StringValue) isDifferentialPrivacyOutputValue_Value() {}

var File_googlesql_public_functions_differential_privacy_proto protoreflect.FileDescriptor

const file_googlesql_public_functions_differential_privacy_proto_rawDesc = "" +
	"\n" +
	"5googlesql/public/functions/differential_privacy.proto\x12\x13googlesql.functions\x1a-googlesql/proto/anon_output_with_report.proto\x1a\x1bgooglesql/public/type.proto\"\xed\x04\n" +
	"\x18DifferentialPrivacyEnums\"\x89\x01\n" +
	"\fReportFormat\x128\n" +
	"*DIFFERENTIAL_PRIVACY_REPORT_FORMAT_INVALID\x10\x00\x1a\b\xb2\xf2\xb0\x92\x0e\x02\b\x01\x12\b\n" +
	"\x04JSON\x10\x01\x12\t\n" +
	"\x05PROTO\x10\x02\x1a*\xb2Я\xfa\r$\n" +
	"\"DIFFERENTIAL_PRIVACY_REPORT_FORMAT\"\xbe\x01\n" +
	"\x16GroupSelectionStrategy\x12C\n" +
	"5DIFFERENTIAL_PRIVACY_GROUP_SELECTION_STRATEGY_INVALID\x10\x00\x1a\b\xb2\xf2\xb0\x92\x0e\x02\b\x01\x12\x15\n" +
	"\x11LAPLACE_THRESHOLD\x10\x01\x12\x11\n" +
	"\rPUBLIC_GROUPS\x10\x02\x1a5\xb2Я\xfa\r/\n" +
	"-DIFFERENTIAL_PRIVACY_GROUP_SELECTION_STRATEGY\"\x83\x02\n" +
	")CountDistinctContributionBoundingStrategy\x12X\n" +
	"JDIFFERENTIAL_PRIVACY_COUNT_DISTINCT_CONTRIBUTION_BOUNDING_STRATEGY_INVALID\x10\x00\x1a\b\xb2\xf2\xb0\x92\x0e\x02\b\x01\x12\b\n" +
	"\x04AUTO\x10\x01\x12\f\n" +
	"\bSAMPLING\x10\x02\x12\n" +
	"\n" +
	"\x06GREEDY\x10\x03\x12\f\n" +
	"\bMATCHING\x10\x04\x1aJ\xb2Я\xfa\rD\n" +
	"BDIFFERENTIAL_PRIVACY_COUNT_DISTINCT_CONTRIBUTION_BOUNDING_STRATEGY\"\xc8\x03\n" +
	"#DifferentialPrivacyOutputWithReport\x12K\n" +
	"\x05value\x18\x01 \x01(\v23.googlesql.functions.DifferentialPrivacyOutputValueH\x00R\x05value\x12N\n" +
	"\x06values\x18\x02 \x01(\v24.googlesql.functions.DifferentialPrivacyOutputValuesH\x00R\x06values\x12a\n" +
	"\x0fbounding_report\x18\x03 \x01(\v26.googlesql.functions.DifferentialPrivacyBoundingReportH\x01R\x0eboundingReport\x12\x8c\x01\n" +
	"\x1ecount_distinct_bounding_report\x18\x04 \x01(\v2E.googlesql.functions.DifferentiallyPrivateCountDistinctBoundingReportH\x01R\x1bcountDistinctBoundingReportB\b\n" +
	"\x06resultB\b\n" +
	"\x06report\"\x8f\x02\n" +
	"!DifferentialPrivacyBoundingReport\x12T\n" +
	"\vlower_bound\x18\x01 \x01(\v23.googlesql.functions.DifferentialPrivacyOutputValueR\n" +
	"lowerBound\x12T\n" +
	"\vupper_bound\x18\x02 \x01(\v23.googlesql.functions.DifferentialPrivacyOutputValueR\n" +
	"upperBound\x12\x1d\n" +
	"\n" +
	"num_inputs\x18\x03 \x01(\x01R\tnumInputs\x12\x1f\n" +
	"\vnum_outside\x18\x04 \x01(\x01R\n" +
	"numOutside\"\x92\x02\n" +
	"0DifferentiallyPrivateCountDistinctBoundingReport\x12\x9d\x01\n" +
	"\x1econtribution_bounding_strategy\x18\x01 \x01(\x0e2W.googlesql.functions.DifferentialPrivacyEnums.CountDistinctContributionBoundingStrategyR\x1ccontributionBoundingStrategy\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\x03R\n" +
	"upperBound\x12\x1d\n" +
	"\n" +
	"num_inputs\x18\x03 \x01(\x01R\tnumInputs\"n\n" +
	"\x1fDifferentialPrivacyOutputValues\x12K\n" +
	"\x06values\x18\x01 \x03(\v23.googlesql.functions.DifferentialPrivacyOutputValueR\x06values\"\xf0\x01\n" +
	"\x1eDifferentialPrivacyOutputValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x02 \x01(\x01H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12^\n" +
	"\x19noise_confidence_interval\x18\x04 \x01(\v2\".googlesql.NoiseConfidenceIntervalR\x17noiseConfidenceIntervalB\a\n" +
	"\x05valueB>\n" +
	"\x1ecom.google.googlesql.functionsB\x1cGoogleSQLDifferentialPrivacy"

var (
	file_googlesql_public_functions_differential_privacy_proto_rawDescOnce sync.Once
	file_googlesql_public_functions_differential_privacy_proto_rawDescData []byte
)

func file_googlesql_public_functions_differential_privacy_proto_rawDescGZIP() []byte {
	file_googlesql_public_functions_differential_privacy_proto_rawDescOnce.Do(func() {
		file_googlesql_public_functions_differential_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_functions_differential_privacy_proto_rawDesc), len(file_googlesql_public_functions_differential_privacy_proto_rawDesc)))
	})
	return file_googlesql_public_functions_differential_privacy_proto_rawDescData
}

var file_googlesql_public_functions_differential_privacy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_googlesql_public_functions_differential_privacy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_googlesql_public_functions_differential_privacy_proto_goTypes = []any{
	(DifferentialPrivacyEnums_ReportFormat)(0),                              // 0: googlesql.functions.DifferentialPrivacyEnums.ReportFormat
	(DifferentialPrivacyEnums_GroupSelectionStrategy)(0),                    // 1: googlesql.functions.DifferentialPrivacyEnums.GroupSelectionStrategy
	(DifferentialPrivacyEnums_CountDistinctContributionBoundingStrategy)(0), // 2: googlesql.functions.DifferentialPrivacyEnums.CountDistinctContributionBoundingStrategy
	(*DifferentialPrivacyEnums)(nil),                                        // 3: googlesql.functions.DifferentialPrivacyEnums
	(*DifferentialPrivacyOutputWithReport)(nil),                             // 4: googlesql.functions.DifferentialPrivacyOutputWithReport
	(*DifferentialPrivacyBoundingReport)(nil),                               // 5: googlesql.functions.DifferentialPrivacyBoundingReport
	(*DifferentiallyPrivateCountDistinctBoundingReport)(nil),                // 6: googlesql.functions.DifferentiallyPrivateCountDistinctBoundingReport
	(*DifferentialPrivacyOutputValues)(nil),                                 // 7: googlesql.functions.DifferentialPrivacyOutputValues
	(*DifferentialPrivacyOutputValue)(nil),                                  // 8: googlesql.functions.DifferentialPrivacyOutputValue
	(*googlesql_core.NoiseConfidenceInterval)(nil),                          // 9: googlesql.NoiseConfidenceInterval
}
var file_googlesql_public_functions_differential_privacy_proto_depIdxs = []int32{
	8, // 0: googlesql.functions.DifferentialPrivacyOutputWithReport.value:type_name -> googlesql.functions.DifferentialPrivacyOutputValue
	7, // 1: googlesql.functions.DifferentialPrivacyOutputWithReport.values:type_name -> googlesql.functions.DifferentialPrivacyOutputValues
	5, // 2: googlesql.functions.DifferentialPrivacyOutputWithReport.bounding_report:type_name -> googlesql.functions.DifferentialPrivacyBoundingReport
	6, // 3: googlesql.functions.DifferentialPrivacyOutputWithReport.count_distinct_bounding_report:type_name -> googlesql.functions.DifferentiallyPrivateCountDistinctBoundingReport
	8, // 4: googlesql.functions.DifferentialPrivacyBoundingReport.lower_bound:type_name -> googlesql.functions.DifferentialPrivacyOutputValue
	8, // 5: googlesql.functions.DifferentialPrivacyBoundingReport.upper_bound:type_name -> googlesql.functions.DifferentialPrivacyOutputValue
	2, // 6: googlesql.functions.DifferentiallyPrivateCountDistinctBoundingReport.contribution_bounding_strategy:type_name -> googlesql.functions.DifferentialPrivacyEnums.CountDistinctContributionBoundingStrategy
	8, // 7: googlesql.functions.DifferentialPrivacyOutputValues.values:type_name -> googlesql.functions.DifferentialPrivacyOutputValue
	9, // 8: googlesql.functions.DifferentialPrivacyOutputValue.noise_confidence_interval:type_name -> googlesql.NoiseConfidenceInterval
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_googlesql_public_functions_differential_privacy_proto_init() }
func file_googlesql_public_functions_differential_privacy_proto_init() {
	if File_googlesql_public_functions_differential_privacy_proto != nil {
		return
	}
	file_googlesql_public_functions_differential_privacy_proto_msgTypes[1].OneofWrappers = []any{
		(*DifferentialPrivacyOutputWithReport_Value)(nil),
		(*DifferentialPrivacyOutputWithReport_Values)(nil),
		(*DifferentialPrivacyOutputWithReport_BoundingReport)(nil),
		(*DifferentialPrivacyOutputWithReport_CountDistinctBoundingReport)(nil),
	}
	file_googlesql_public_functions_differential_privacy_proto_msgTypes[5].OneofWrappers = []any{
		(*DifferentialPrivacyOutputValue_IntValue)(nil),
		(*DifferentialPrivacyOutputValue_FloatValue)(nil),
		(*DifferentialPrivacyOutputValue_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_functions_differential_privacy_proto_rawDesc), len(file_googlesql_public_functions_differential_privacy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_functions_differential_privacy_proto_goTypes,
		DependencyIndexes: file_googlesql_public_functions_differential_privacy_proto_depIdxs,
		EnumInfos:         file_googlesql_public_functions_differential_privacy_proto_enumTypes,
		MessageInfos:      file_googlesql_public_functions_differential_privacy_proto_msgTypes,
	}.Build()
	File_googlesql_public_functions_differential_privacy_proto = out.File
	file_googlesql_public_functions_differential_privacy_proto_goTypes = nil
	file_googlesql_public_functions_differential_privacy_proto_depIdxs = nil
}
