//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/functions/rounding_mode.proto

package googlesql_public_functions

import (
	_ "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum that defines the modes used for rounding values in the ROUND function
// The RoundingMode could be one of the following
//   - ROUND_HALF_AWAY_FROM_ZERO: will round halfway values away from zero.
//     for example: 0.5 would round to 1, 1.5 would round to 2.
//   - ROUND_HALF_EVEN: will round halfway values to the nearest even value.
//     otherwise known as bankers rounding. for example: 0.5 would round to 0,
//     1.5 would round to 2.
//
// In both rounding modes, .1 .2 .3. 4, and .6 .7 .8 and .9 behave identically
// and as expected. For example, in both rounding modes 1.1 will round down to
// 1, and 1.8 will round up to 2. Negative numbers act identical. For example,
// -1.1 will round to -1, and -1.8 will round to -2.
type RoundingMode int32

const (
	// Invalid in GoogleSQL.
	RoundingMode_ROUNDING_MODE_UNSPECIFIED RoundingMode = 0
	// Round halfway values away from zero (the default rounding mode).
	RoundingMode_ROUND_HALF_AWAY_FROM_ZERO RoundingMode = 1
	// Round halfway values to the nearest even.
	RoundingMode_ROUND_HALF_EVEN RoundingMode = 2
)

// Enum value maps for RoundingMode.
var (
	RoundingMode_name = map[int32]string{
		0: "ROUNDING_MODE_UNSPECIFIED",
		1: "ROUND_HALF_AWAY_FROM_ZERO",
		2: "ROUND_HALF_EVEN",
	}
	RoundingMode_value = map[string]int32{
		"ROUNDING_MODE_UNSPECIFIED": 0,
		"ROUND_HALF_AWAY_FROM_ZERO": 1,
		"ROUND_HALF_EVEN":           2,
	}
)

func (x RoundingMode) Enum() *RoundingMode {
	p := new(RoundingMode)
	*p = x
	return p
}

func (x RoundingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoundingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_functions_rounding_mode_proto_enumTypes[0].Descriptor()
}

func (RoundingMode) Type() protoreflect.EnumType {
	return &file_googlesql_public_functions_rounding_mode_proto_enumTypes[0]
}

func (x RoundingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RoundingMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RoundingMode(num)
	return nil
}

// Deprecated: Use RoundingMode.Descriptor instead.
func (RoundingMode) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_functions_rounding_mode_proto_rawDescGZIP(), []int{0}
}

var File_googlesql_public_functions_rounding_mode_proto protoreflect.FileDescriptor

const file_googlesql_public_functions_rounding_mode_proto_rawDesc = "" +
	"\n" +
	".googlesql/public/functions/rounding_mode.proto\x12\x13googlesql.functions\x1a\x1bgooglesql/public/type.proto*\x82\x01\n" +
	"\fRoundingMode\x12'\n" +
	"\x19ROUNDING_MODE_UNSPECIFIED\x10\x00\x1a\b\xb2\xf2\xb0\x92\x0e\x02\b\x01\x12\x1d\n" +
	"\x19ROUND_HALF_AWAY_FROM_ZERO\x10\x01\x12\x13\n" +
	"\x0fROUND_HALF_EVEN\x10\x02\x1a\x15\xb2Я\xfa\r\x0f\n" +
	"\rROUNDING_MODEB7\n" +
	"\x1ecom.google.googlesql.functionsB\x15GoogleSQLRoundingMode"

var (
	file_googlesql_public_functions_rounding_mode_proto_rawDescOnce sync.Once
	file_googlesql_public_functions_rounding_mode_proto_rawDescData []byte
)

func file_googlesql_public_functions_rounding_mode_proto_rawDescGZIP() []byte {
	file_googlesql_public_functions_rounding_mode_proto_rawDescOnce.Do(func() {
		file_googlesql_public_functions_rounding_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_functions_rounding_mode_proto_rawDesc), len(file_googlesql_public_functions_rounding_mode_proto_rawDesc)))
	})
	return file_googlesql_public_functions_rounding_mode_proto_rawDescData
}

var file_googlesql_public_functions_rounding_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_googlesql_public_functions_rounding_mode_proto_goTypes = []any{
	(RoundingMode)(0), // 0: googlesql.functions.RoundingMode
}
var file_googlesql_public_functions_rounding_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_functions_rounding_mode_proto_init() }
func file_googlesql_public_functions_rounding_mode_proto_init() {
	if File_googlesql_public_functions_rounding_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_functions_rounding_mode_proto_rawDesc), len(file_googlesql_public_functions_rounding_mode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_functions_rounding_mode_proto_goTypes,
		DependencyIndexes: file_googlesql_public_functions_rounding_mode_proto_depIdxs,
		EnumInfos:         file_googlesql_public_functions_rounding_mode_proto_enumTypes,
	}.Build()
	File_googlesql_public_functions_rounding_mode_proto = out.File
	file_googlesql_public_functions_rounding_mode_proto_goTypes = nil
	file_googlesql_public_functions_rounding_mode_proto_depIdxs = nil
}
