//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file contains the type annotations supported by GoogleSQL.
//
// These annotations can be used to change the interpretation of proto
// fields when interpreting those fields in GoogleSQL. (e.g. An int32 field can
// be marked as storing a DATE to make it queryable as a date in GoogleSQL.)
// When applying to an existing field, please check the existing scripts that
// use the field to avoid potential breakage.
//
// These annotations can also be used to indicate that missing fields should
// be treated as NULL values rather than returning the proto field default.
//
// Example:
//
//   import "googlesql/public/proto/type_annotation.proto";
//
//   message SomeMessage {
//     // Date field.
//     optional int32 date = 1 [ (googlesql.format) = DATE ];
//
//     // String field, where GoogleSQL will interpret missing values as NULLs.
//     optional string str = 2 [ (googlesql.use_defaults) = false ];
//
//     // Timestamp field, which can store GoogleSQL NULLs.
//     optional int64 time_millis = 3
//         [ (googlesql.format) = TIMESTAMP_MILLIS,
//           (googlesql.use_defaults) = false ];
//   }
//
//   message OtherMessage {
//     // Interpret missing value as NULLs for all fields in this message.
//     option (googlesql.use_field_defaults) = false;
//
//     optional int64 nullable_int = 1;
//     optional string nullable_string = 2;
//   }

// LINT: LEGACY_NAMES

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/public/proto/type_annotation.proto

package googlesql_public_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldFormat_Format int32

const (
	// No format annotation.
	// This is meant as a no-annotation marker in code and should not actually
	// be written as an annotation in .proto files.
	FieldFormat_DEFAULT_FORMAT FieldFormat_Format = 0
	// A GoogleSQL DATE, encoded as days since 1970-01-01 UTC.
	// Can be applied to a field with ctype int32 or an int64.
	//
	// The function DecodeFormattedDate in public/functions/date_time_util.h
	// can be used to decode all supported date formats.
	FieldFormat_DATE FieldFormat_Format = 1
	// A GoogleSQL timestamp.  Timestamps are encoded as elapsed
	// seconds, millis, micros, or nanos since 1970-01-01 00:00:00 UTC.
	// TIMESTAMP_SECONDS is the standard unix time_t type.
	// Should be applied to fields with ctype int64.
	FieldFormat_TIMESTAMP_SECONDS FieldFormat_Format = 2
	FieldFormat_TIMESTAMP_MILLIS  FieldFormat_Format = 3
	FieldFormat_TIMESTAMP_MICROS  FieldFormat_Format = 4
	FieldFormat_TIMESTAMP_NANOS   FieldFormat_Format = 5
	// A GoogleSQL TIMESTAMP_PICOS value. These values are encoded as 16 bytes
	// (2 uint64s). See TimestampPicosValue::SerializeAsBytes() for
	// serialization format details.
	//
	// Can be applied to bytes fields.
	FieldFormat_TIMESTAMP_PICOS FieldFormat_Format = 20
	// A GoogleSQL TIMESTAMP value. It represents a timestamp with
	// precision up to picoseconds. Under the hood, all the
	// timestamps are stored as TimestampPicos.
	// See TimestampPicosValue::SerializeAsBytes() for
	// serialization format details.
	//
	// Can be applied to bytes fields.
	FieldFormat_TIMESTAMP FieldFormat_Format = 21
	// A GoogleSQL DATE encoded in the MySQL date decimal format,
	// which looks like YYYYMMDD written as an integer.
	// Can be applied to a field with type int32 or an int64.
	//
	// NOTE: The value 0 decodes to NULL in this format.  (Otherwise it would
	// be an invalid date.)
	//
	// The function DecodeFormattedDate in
	// googlesql/public/functions/date_time_util.h
	// can be used to decode all supported date formats.
	FieldFormat_DATE_DECIMAL FieldFormat_Format = 6
	// A GoogleSQL TIME encoded in an 8-byte bit field.
	// See googlesql/public/civil_time.h for encoding methods.
	// Can be applied to a field with ctype int64.
	FieldFormat_TIME_MICROS FieldFormat_Format = 7
	// A GoogleSQL DATETIME encoded in an 8-byte bit field.
	// See googlesql/public/civil_time.h for encoding methods.
	// Can be applied to a field with ctype int64.
	//
	// NOTE: An explicitly-set 0 value is an invalid datetime. An unset field
	// with a proto default 0 value decodes to NULL. To have the default
	// DATETIME value at 1970-01-01 00:00:00, use 138630961515462656 as the
	// default.
	FieldFormat_DATETIME_MICROS FieldFormat_Format = 8
	// A GoogleSQL GEOGRAPHY binary encoding.
	//
	// Can be applied to bytes fields.
	FieldFormat_ST_GEOGRAPHY_ENCODED FieldFormat_Format = 9
	// A GoogleSQL NUMERIC value. These values are encoded as scaled integers in
	// two's complement form with the most significant bit storing the sign. See
	// NumericValue::SerializeAsProtoBytes() for serialization format details.
	//
	// Can be applied to bytes fields.
	FieldFormat_NUMERIC FieldFormat_Format = 10
	// A GoogleSQL BIGNUMERIC value. These values are encoded as scaled integers
	// in two's complement form with the most significant bit storing the sign.
	// See BigNumericValue::SerializeAsProtoBytes() for serialization format
	// details.
	//
	// Can be applied to bytes fields.
	FieldFormat_BIGNUMERIC FieldFormat_Format = 11
	// A GoogleSQL JSON value. These values are encoded as JSON strings
	// according to the JSON RFC (RFC 7159)).
	//
	// Can be applied to string fields.
	FieldFormat_JSON FieldFormat_Format = 12
	// A GoogleSQL INTERVAL value.
	// See IntervalValue::SerializeAsBytes() for serialization format details.
	//
	// Can be applied to bytes fields.
	FieldFormat_INTERVAL FieldFormat_Format = 14
	// A GoogleSQL TOKENLIST value.
	// Can be applied to bytes fields.
	FieldFormat_TOKENLIST FieldFormat_Format = 15
	// A GoogleSQL Range value encoded as bytes.
	//
	// Can be applied to bytes fields.
	FieldFormat_RANGE_DATES_ENCODED      FieldFormat_Format = 16
	FieldFormat_RANGE_DATETIMES_ENCODED  FieldFormat_Format = 17
	FieldFormat_RANGE_TIMESTAMPS_ENCODED FieldFormat_Format = 18
	// A GoogleSQL UUID value. These values are encoded as 16 bytes (2 uint64s).
	FieldFormat_UUID FieldFormat_Format = 19
	// User code that switches on this enum must have a default case so
	// builds won't break if new enums get added.
	FieldFormat___FieldFormat_Type__switch_must_have_a_default__ FieldFormat_Format = -1
)

// Enum value maps for FieldFormat_Format.
var (
	FieldFormat_Format_name = map[int32]string{
		0:  "DEFAULT_FORMAT",
		1:  "DATE",
		2:  "TIMESTAMP_SECONDS",
		3:  "TIMESTAMP_MILLIS",
		4:  "TIMESTAMP_MICROS",
		5:  "TIMESTAMP_NANOS",
		20: "TIMESTAMP_PICOS",
		21: "TIMESTAMP",
		6:  "DATE_DECIMAL",
		7:  "TIME_MICROS",
		8:  "DATETIME_MICROS",
		9:  "ST_GEOGRAPHY_ENCODED",
		10: "NUMERIC",
		11: "BIGNUMERIC",
		12: "JSON",
		14: "INTERVAL",
		15: "TOKENLIST",
		16: "RANGE_DATES_ENCODED",
		17: "RANGE_DATETIMES_ENCODED",
		18: "RANGE_TIMESTAMPS_ENCODED",
		19: "UUID",
		-1: "__FieldFormat_Type__switch_must_have_a_default__",
	}
	FieldFormat_Format_value = map[string]int32{
		"DEFAULT_FORMAT":           0,
		"DATE":                     1,
		"TIMESTAMP_SECONDS":        2,
		"TIMESTAMP_MILLIS":         3,
		"TIMESTAMP_MICROS":         4,
		"TIMESTAMP_NANOS":          5,
		"TIMESTAMP_PICOS":          20,
		"TIMESTAMP":                21,
		"DATE_DECIMAL":             6,
		"TIME_MICROS":              7,
		"DATETIME_MICROS":          8,
		"ST_GEOGRAPHY_ENCODED":     9,
		"NUMERIC":                  10,
		"BIGNUMERIC":               11,
		"JSON":                     12,
		"INTERVAL":                 14,
		"TOKENLIST":                15,
		"RANGE_DATES_ENCODED":      16,
		"RANGE_DATETIMES_ENCODED":  17,
		"RANGE_TIMESTAMPS_ENCODED": 18,
		"UUID":                     19,
		"__FieldFormat_Type__switch_must_have_a_default__": -1,
	}
)

func (x FieldFormat_Format) Enum() *FieldFormat_Format {
	p := new(FieldFormat_Format)
	*p = x
	return p
}

func (x FieldFormat_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldFormat_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_proto_type_annotation_proto_enumTypes[0].Descriptor()
}

func (FieldFormat_Format) Type() protoreflect.EnumType {
	return &file_googlesql_public_proto_type_annotation_proto_enumTypes[0]
}

func (x FieldFormat_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FieldFormat_Format) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FieldFormat_Format(num)
	return nil
}

// Deprecated: Use FieldFormat_Format.Descriptor instead.
func (FieldFormat_Format) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_proto_type_annotation_proto_rawDescGZIP(), []int{0, 0}
}

// DEPRECATED - Encoding has been folded into the Type enum above.
// This should not be used directly.
// TODO Remove this once there are no more references.
type DeprecatedEncoding_Encoding int32

const (
	DeprecatedEncoding_DEFAULT_ENCODING DeprecatedEncoding_Encoding = 0
	DeprecatedEncoding_DATE_DECIMAL     DeprecatedEncoding_Encoding = 1
	// Like in FieldFormat, PACKED32 is the wrong name, and people should be
	// using DATE_DECIMAL instead.  This whole enum definition is deprecated
	// though, so this definition probably won't be fixed.
	//
	// Deprecated: Marked as deprecated in googlesql/public/proto/type_annotation.proto.
	DeprecatedEncoding_DATE_PACKED32                                        DeprecatedEncoding_Encoding = 1 // This is the wrong name. The format is DATE_DECIMAL.
	DeprecatedEncoding___FieldFormat_Encoding__switch_must_have_a_default__ DeprecatedEncoding_Encoding = -1
)

// Enum value maps for DeprecatedEncoding_Encoding.
var (
	DeprecatedEncoding_Encoding_name = map[int32]string{
		0: "DEFAULT_ENCODING",
		1: "DATE_DECIMAL",
		// Duplicate value: 1: "DATE_PACKED32",
		-1: "__FieldFormat_Encoding__switch_must_have_a_default__",
	}
	DeprecatedEncoding_Encoding_value = map[string]int32{
		"DEFAULT_ENCODING": 0,
		"DATE_DECIMAL":     1,
		"DATE_PACKED32":    1,
		"__FieldFormat_Encoding__switch_must_have_a_default__": -1,
	}
)

func (x DeprecatedEncoding_Encoding) Enum() *DeprecatedEncoding_Encoding {
	p := new(DeprecatedEncoding_Encoding)
	*p = x
	return p
}

func (x DeprecatedEncoding_Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeprecatedEncoding_Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_public_proto_type_annotation_proto_enumTypes[1].Descriptor()
}

func (DeprecatedEncoding_Encoding) Type() protoreflect.EnumType {
	return &file_googlesql_public_proto_type_annotation_proto_enumTypes[1]
}

func (x DeprecatedEncoding_Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeprecatedEncoding_Encoding) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeprecatedEncoding_Encoding(num)
	return nil
}

// Deprecated: Use DeprecatedEncoding_Encoding.Descriptor instead.
func (DeprecatedEncoding_Encoding) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_public_proto_type_annotation_proto_rawDescGZIP(), []int{1, 0}
}

type FieldFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldFormat) Reset() {
	*x = FieldFormat{}
	mi := &file_googlesql_public_proto_type_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldFormat) ProtoMessage() {}

func (x *FieldFormat) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_proto_type_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldFormat.ProtoReflect.Descriptor instead.
func (*FieldFormat) Descriptor() ([]byte, []int) {
	return file_googlesql_public_proto_type_annotation_proto_rawDescGZIP(), []int{0}
}

type DeprecatedEncoding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecatedEncoding) Reset() {
	*x = DeprecatedEncoding{}
	mi := &file_googlesql_public_proto_type_annotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecatedEncoding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecatedEncoding) ProtoMessage() {}

func (x *DeprecatedEncoding) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_public_proto_type_annotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecatedEncoding.ProtoReflect.Descriptor instead.
func (*DeprecatedEncoding) Descriptor() ([]byte, []int) {
	return file_googlesql_public_proto_type_annotation_proto_rawDescGZIP(), []int{1}
}

var file_googlesql_public_proto_type_annotation_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldFormat_Format)(nil),
		Field:         68711883,
		Name:          "googlesql.format",
		Tag:           "varint,68711883,opt,name=format,enum=googlesql.FieldFormat_Format",
		Filename:      "googlesql/public/proto/type_annotation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldFormat_Format)(nil),
		Field:         49796453,
		Name:          "googlesql.type",
		Tag:           "varint,49796453,opt,name=type,enum=googlesql.FieldFormat_Format",
		Filename:      "googlesql/public/proto/type_annotation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*DeprecatedEncoding_Encoding)(nil),
		Field:         62897319,
		Name:          "googlesql.encoding",
		Tag:           "varint,62897319,opt,name=encoding,enum=googlesql.DeprecatedEncoding_Encoding",
		Filename:      "googlesql/public/proto/type_annotation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         49779519,
		Name:          "googlesql.use_defaults",
		Tag:           "varint,49779519,opt,name=use_defaults,def=1",
		Filename:      "googlesql/public/proto/type_annotation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         49659010,
		Name:          "googlesql.use_field_defaults",
		Tag:           "varint,49659010,opt,name=use_field_defaults,def=1",
		Filename:      "googlesql/public/proto/type_annotation.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Interpret a proto field using a specific GoogleSQL format, which
	// indicates both the GoogleSQL type and the encoding.
	//
	// When reading this field in SQL, it will act semantically as the specified
	// type rather than the underlying proto field type, and it will
	// be decoded by engines according to the specified encoding.
	// See FieldFormat.Format above.
	//
	// Engines should access this using ProtoType::GetFormatAnnotation rather
	// than extracting it themselves so they handle the deprecated variants
	// below correctly.
	//
	// optional googlesql.FieldFormat.Format format = 68711883;
	E_Format = &file_googlesql_public_proto_type_annotation_proto_extTypes[0]
	// DEPRECATED: This is the legacy name for format.  It is here for
	// compatibility with old proto Descriptors.  It should not be used in
	// new .proto files.
	//
	// googlesql::ProtoType::GetFormatAnnotation will look in both places and use
	// the deprecated annotation if necessary.  If both are present, this one
	// is ignored.
	//
	// optional googlesql.FieldFormat.Format type = 49796453;
	E_Type = &file_googlesql_public_proto_type_annotation_proto_extTypes[1]
	// DEPRECATED.  The encoding has been folded into the Format annotation above.
	// This exists only for legacy .proto files that include this annotation.
	// ProtoType::GetFormatAnnotation automatically merges the legacy encoding
	// annotations into the type annotation so callers can ignore this.
	//
	// optional googlesql.DeprecatedEncoding.Encoding encoding = 62897319;
	E_Encoding = &file_googlesql_public_proto_type_annotation_proto_extTypes[2]
	// Interpret missing optional scalar fields as NULLs, rather than using
	// the field's default value, if this is set to false.
	//
	// By default, use_defaults = true, and GoogleSQL will use the field's
	// default value when accessing an optional scalar field that isn't present.
	//
	// Notes:
	//  1. In protocol buffers, all optional scalar fields have a default default
	//     (usually 0 or ""), so absence of a declared default has no effect.
	//  2. Repeated fields cannot have absent values, and cannot store NULLs
	//     without using a wrapper message.  See is_wrapper annotation.
	//     use_defaults is invalid on repeated fields.
	//  3. Message types do not have defaults, and not present optional message
	//     fields will always be interpreted as NULL.
	//     use_defaults has no effect on message type fields.
	//
	// optional bool use_defaults = 49779519;
	E_UseDefaults = &file_googlesql_public_proto_type_annotation_proto_extTypes[3]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Same as field-level use_defaults, but applies to all top-level fields in
	// this message.  Does not apply to fields recursively inside sub-messages.
	// Field-level use_defaults overrides message-level use_field_defaults.
	// (Would be called use_defaults, except the name cannot be reused.)
	//
	// optional bool use_field_defaults = 49659010;
	E_UseFieldDefaults = &file_googlesql_public_proto_type_annotation_proto_extTypes[4]
)

var File_googlesql_public_proto_type_annotation_proto protoreflect.FileDescriptor

const file_googlesql_public_proto_type_annotation_proto_rawDesc = "" +
	"\n" +
	",googlesql/public/proto/type_annotation.proto\x12\tgooglesql\x1a google/protobuf/descriptor.proto\"\xe5\x03\n" +
	"\vFieldFormat\"\xd5\x03\n" +
	"\x06Format\x12\x12\n" +
	"\x0eDEFAULT_FORMAT\x10\x00\x12\b\n" +
	"\x04DATE\x10\x01\x12\x15\n" +
	"\x11TIMESTAMP_SECONDS\x10\x02\x12\x14\n" +
	"\x10TIMESTAMP_MILLIS\x10\x03\x12\x14\n" +
	"\x10TIMESTAMP_MICROS\x10\x04\x12\x13\n" +
	"\x0fTIMESTAMP_NANOS\x10\x05\x12\x13\n" +
	"\x0fTIMESTAMP_PICOS\x10\x14\x12\r\n" +
	"\tTIMESTAMP\x10\x15\x12\x10\n" +
	"\fDATE_DECIMAL\x10\x06\x12\x0f\n" +
	"\vTIME_MICROS\x10\a\x12\x13\n" +
	"\x0fDATETIME_MICROS\x10\b\x12\x18\n" +
	"\x14ST_GEOGRAPHY_ENCODED\x10\t\x12\v\n" +
	"\aNUMERIC\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"BIGNUMERIC\x10\v\x12\b\n" +
	"\x04JSON\x10\f\x12\f\n" +
	"\bINTERVAL\x10\x0e\x12\r\n" +
	"\tTOKENLIST\x10\x0f\x12\x17\n" +
	"\x13RANGE_DATES_ENCODED\x10\x10\x12\x1b\n" +
	"\x17RANGE_DATETIMES_ENCODED\x10\x11\x12\x1c\n" +
	"\x18RANGE_TIMESTAMPS_ENCODED\x10\x12\x12\b\n" +
	"\x04UUID\x10\x13\x12=\n" +
	"0__FieldFormat_Type__switch_must_have_a_default__\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\"\xa7\x01\n" +
	"\x12DeprecatedEncoding\"\x90\x01\n" +
	"\bEncoding\x12\x14\n" +
	"\x10DEFAULT_ENCODING\x10\x00\x12\x10\n" +
	"\fDATE_DECIMAL\x10\x01\x12\x15\n" +
	"\rDATE_PACKED32\x10\x01\x1a\x02\b\x01\x12A\n" +
	"4__FieldFormat_Encoding__switch_must_have_a_default__\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x1a\x02\x10\x01:W\n" +
	"\x06format\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xeb\xe1  \x01(\x0e2\x1d.googlesql.FieldFormat.FormatR\x06format:S\n" +
	"\x04type\x12\x1d.google.protobuf.FieldOptions\x18\xe5\xaa\xdf\x17 \x01(\x0e2\x1d.googlesql.FieldFormat.FormatR\x04type:d\n" +
	"\bencoding\x12\x1d.google.protobuf.FieldOptions\x18\xa7\xf9\xfe\x1d \x01(\x0e2&.googlesql.DeprecatedEncoding.EncodingR\bencoding:I\n" +
	"\fuse_defaults\x12\x1d.google.protobuf.FieldOptions\x18\xbf\xa6\xde\x17 \x01(\b:\x04trueR\vuseDefaults:V\n" +
	"\x12use_field_defaults\x12\x1f.google.protobuf.MessageOptions\x18\x82\xf9\xd6\x17 \x01(\b:\x04trueR\x10useFieldDefaultsB.\n" +
	"\x14com.google.googlesqlB\x13TypeAnnotationProto\xf8\x01\x01"

var (
	file_googlesql_public_proto_type_annotation_proto_rawDescOnce sync.Once
	file_googlesql_public_proto_type_annotation_proto_rawDescData []byte
)

func file_googlesql_public_proto_type_annotation_proto_rawDescGZIP() []byte {
	file_googlesql_public_proto_type_annotation_proto_rawDescOnce.Do(func() {
		file_googlesql_public_proto_type_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_public_proto_type_annotation_proto_rawDesc), len(file_googlesql_public_proto_type_annotation_proto_rawDesc)))
	})
	return file_googlesql_public_proto_type_annotation_proto_rawDescData
}

var file_googlesql_public_proto_type_annotation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_googlesql_public_proto_type_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_googlesql_public_proto_type_annotation_proto_goTypes = []any{
	(FieldFormat_Format)(0),             // 0: googlesql.FieldFormat.Format
	(DeprecatedEncoding_Encoding)(0),    // 1: googlesql.DeprecatedEncoding.Encoding
	(*FieldFormat)(nil),                 // 2: googlesql.FieldFormat
	(*DeprecatedEncoding)(nil),          // 3: googlesql.DeprecatedEncoding
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
}
var file_googlesql_public_proto_type_annotation_proto_depIdxs = []int32{
	4, // 0: googlesql.format:extendee -> google.protobuf.FieldOptions
	4, // 1: googlesql.type:extendee -> google.protobuf.FieldOptions
	4, // 2: googlesql.encoding:extendee -> google.protobuf.FieldOptions
	4, // 3: googlesql.use_defaults:extendee -> google.protobuf.FieldOptions
	5, // 4: googlesql.use_field_defaults:extendee -> google.protobuf.MessageOptions
	0, // 5: googlesql.format:type_name -> googlesql.FieldFormat.Format
	0, // 6: googlesql.type:type_name -> googlesql.FieldFormat.Format
	1, // 7: googlesql.encoding:type_name -> googlesql.DeprecatedEncoding.Encoding
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	5, // [5:8] is the sub-list for extension type_name
	0, // [0:5] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_public_proto_type_annotation_proto_init() }
func file_googlesql_public_proto_type_annotation_proto_init() {
	if File_googlesql_public_proto_type_annotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_public_proto_type_annotation_proto_rawDesc), len(file_googlesql_public_proto_type_annotation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_public_proto_type_annotation_proto_goTypes,
		DependencyIndexes: file_googlesql_public_proto_type_annotation_proto_depIdxs,
		EnumInfos:         file_googlesql_public_proto_type_annotation_proto_enumTypes,
		MessageInfos:      file_googlesql_public_proto_type_annotation_proto_msgTypes,
		ExtensionInfos:    file_googlesql_public_proto_type_annotation_proto_extTypes,
	}.Build()
	File_googlesql_public_proto_type_annotation_proto = out.File
	file_googlesql_public_proto_type_annotation_proto_goTypes = nil
	file_googlesql_public_proto_type_annotation_proto_depIdxs = nil
}
