//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/internal_fix_suggestion.proto

package googlesql_core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A range expressed as (1-based) start and end positions.
// A range is comparable to a selection in an editor. Therefore the end position
// is exclusive.
type InternalFixRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The range's start position.
	Start *InternalErrorLocation `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	// The range length.
	Length        *int32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalFixRange) Reset() {
	*x = InternalFixRange{}
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalFixRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalFixRange) ProtoMessage() {}

func (x *InternalFixRange) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalFixRange.ProtoReflect.Descriptor instead.
func (*InternalFixRange) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_internal_fix_suggestion_proto_rawDescGZIP(), []int{0}
}

func (x *InternalFixRange) GetStart() *InternalErrorLocation {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *InternalFixRange) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

// A text edit to be applied to a file.
type InternalTextEdit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (required) The range of the SQL file or input to be manipulated. To insert
	// text, create a range where start == end.
	Range *InternalFixRange `protobuf:"bytes,1,opt,name=range" json:"range,omitempty"`
	// The string to be inserted. For delete operations use an empty string.
	NewText       *string `protobuf:"bytes,2,opt,name=new_text,json=newText" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalTextEdit) Reset() {
	*x = InternalTextEdit{}
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTextEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTextEdit) ProtoMessage() {}

func (x *InternalTextEdit) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTextEdit.ProtoReflect.Descriptor instead.
func (*InternalTextEdit) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_internal_fix_suggestion_proto_rawDescGZIP(), []int{1}
}

func (x *InternalTextEdit) GetRange() *InternalFixRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *InternalTextEdit) GetNewText() string {
	if x != nil && x.NewText != nil {
		return *x.NewText
	}
	return ""
}

// Edits to be applied to a file.
type InternalEdits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A string replacement representation of the edits. Each text_edit is a text
	// replacement in a file range.
	TextEdits     []*InternalTextEdit `protobuf:"bytes,1,rep,name=text_edits,json=textEdits" json:"text_edits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalEdits) Reset() {
	*x = InternalEdits{}
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalEdits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalEdits) ProtoMessage() {}

func (x *InternalEdits) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalEdits.ProtoReflect.Descriptor instead.
func (*InternalEdits) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_internal_fix_suggestion_proto_rawDescGZIP(), []int{2}
}

func (x *InternalEdits) GetTextEdits() []*InternalTextEdit {
	if x != nil {
		return x.TextEdits
	}
	return nil
}

// A fix suggestion for an error with the corresponding edits.
type InternalFix struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (required) A short, human-readable, title for this fix (e.g. a fix for “Did
	// you mean this_proto_field instead?” would have a title like “Replace by
	// this_proto_field”). This is the title that will allow the user to pick from
	// different fixes, sometimes in scenarios where they will not see a diff
	// preview, so it should be short, but fully capture the changes that will be
	// applied.
	Title *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	// (required) The edits to be applied in order to implement the fix.
	Edits         *InternalEdits `protobuf:"bytes,2,opt,name=edits" json:"edits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalFix) Reset() {
	*x = InternalFix{}
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalFix) ProtoMessage() {}

func (x *InternalFix) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalFix.ProtoReflect.Descriptor instead.
func (*InternalFix) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_internal_fix_suggestion_proto_rawDescGZIP(), []int{3}
}

func (x *InternalFix) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *InternalFix) GetEdits() *InternalEdits {
	if x != nil {
		return x.Edits
	}
	return nil
}

// This proto is used as a absl::Status error payload to provide potential fixes
// for SQL parsing and analysis errors.
type InternalErrorFixSuggestions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The possible fixes for the error. Each fix is a potential candidate to
	// resolve the error (e.g. multiple options to a “Did you mean…?” scenario
	// would be represented as multiple `fix_suggestions`).
	FixSuggestions []*InternalFix `protobuf:"bytes,1,rep,name=fix_suggestions,json=fixSuggestions" json:"fix_suggestions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InternalErrorFixSuggestions) Reset() {
	*x = InternalErrorFixSuggestions{}
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalErrorFixSuggestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalErrorFixSuggestions) ProtoMessage() {}

func (x *InternalErrorFixSuggestions) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_internal_fix_suggestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalErrorFixSuggestions.ProtoReflect.Descriptor instead.
func (*InternalErrorFixSuggestions) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_internal_fix_suggestion_proto_rawDescGZIP(), []int{4}
}

func (x *InternalErrorFixSuggestions) GetFixSuggestions() []*InternalFix {
	if x != nil {
		return x.FixSuggestions
	}
	return nil
}

var File_googlesql_proto_internal_fix_suggestion_proto protoreflect.FileDescriptor

const file_googlesql_proto_internal_fix_suggestion_proto_rawDesc = "" +
	"\n" +
	"-googlesql/proto/internal_fix_suggestion.proto\x12\tgooglesql\x1a-googlesql/proto/internal_error_location.proto\"b\n" +
	"\x10InternalFixRange\x126\n" +
	"\x05start\x18\x01 \x01(\v2 .googlesql.InternalErrorLocationR\x05start\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"`\n" +
	"\x10InternalTextEdit\x121\n" +
	"\x05range\x18\x01 \x01(\v2\x1b.googlesql.InternalFixRangeR\x05range\x12\x19\n" +
	"\bnew_text\x18\x02 \x01(\tR\anewText\"K\n" +
	"\rInternalEdits\x12:\n" +
	"\n" +
	"text_edits\x18\x01 \x03(\v2\x1b.googlesql.InternalTextEditR\ttextEdits\"S\n" +
	"\vInternalFix\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12.\n" +
	"\x05edits\x18\x02 \x01(\v2\x18.googlesql.InternalEditsR\x05edits\"^\n" +
	"\x1bInternalErrorFixSuggestions\x12?\n" +
	"\x0ffix_suggestions\x18\x01 \x03(\v2\x16.googlesql.InternalFixR\x0efixSuggestionsB3\n" +
	"\x14com.google.googlesqlB\x1bInternalFixSuggestionProtos"

var (
	file_googlesql_proto_internal_fix_suggestion_proto_rawDescOnce sync.Once
	file_googlesql_proto_internal_fix_suggestion_proto_rawDescData []byte
)

func file_googlesql_proto_internal_fix_suggestion_proto_rawDescGZIP() []byte {
	file_googlesql_proto_internal_fix_suggestion_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_internal_fix_suggestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_internal_fix_suggestion_proto_rawDesc), len(file_googlesql_proto_internal_fix_suggestion_proto_rawDesc)))
	})
	return file_googlesql_proto_internal_fix_suggestion_proto_rawDescData
}

var file_googlesql_proto_internal_fix_suggestion_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_googlesql_proto_internal_fix_suggestion_proto_goTypes = []any{
	(*InternalFixRange)(nil),            // 0: googlesql.InternalFixRange
	(*InternalTextEdit)(nil),            // 1: googlesql.InternalTextEdit
	(*InternalEdits)(nil),               // 2: googlesql.InternalEdits
	(*InternalFix)(nil),                 // 3: googlesql.InternalFix
	(*InternalErrorFixSuggestions)(nil), // 4: googlesql.InternalErrorFixSuggestions
	(*InternalErrorLocation)(nil),       // 5: googlesql.InternalErrorLocation
}
var file_googlesql_proto_internal_fix_suggestion_proto_depIdxs = []int32{
	5, // 0: googlesql.InternalFixRange.start:type_name -> googlesql.InternalErrorLocation
	0, // 1: googlesql.InternalTextEdit.range:type_name -> googlesql.InternalFixRange
	1, // 2: googlesql.InternalEdits.text_edits:type_name -> googlesql.InternalTextEdit
	2, // 3: googlesql.InternalFix.edits:type_name -> googlesql.InternalEdits
	3, // 4: googlesql.InternalErrorFixSuggestions.fix_suggestions:type_name -> googlesql.InternalFix
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_googlesql_proto_internal_fix_suggestion_proto_init() }
func file_googlesql_proto_internal_fix_suggestion_proto_init() {
	if File_googlesql_proto_internal_fix_suggestion_proto != nil {
		return
	}
	file_googlesql_proto_internal_error_location_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_internal_fix_suggestion_proto_rawDesc), len(file_googlesql_proto_internal_fix_suggestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_internal_fix_suggestion_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_internal_fix_suggestion_proto_depIdxs,
		MessageInfos:      file_googlesql_proto_internal_fix_suggestion_proto_msgTypes,
	}.Build()
	File_googlesql_proto_internal_fix_suggestion_proto = out.File
	file_googlesql_proto_internal_fix_suggestion_proto_goTypes = nil
	file_googlesql_proto_internal_fix_suggestion_proto_depIdxs = nil
}
