//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/module_options.proto

package googlesql_core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The default mode for how to find the appropriate UDF server, if a specific
// udf_server_address isn't provided.
type PerModuleOptions_UdfServerImportMode int32

const (
	// Mode unspecified.
	PerModuleOptions_UNKNOWN PerModuleOptions_UdfServerImportMode = 0
	// The UDF server is from the udf_server_address set in the module's
	// OPTIONS. This is the default mode.
	PerModuleOptions_SERVER_ADDRESS_FROM_MODULE PerModuleOptions_UdfServerImportMode = 1
	// The UDF servers will be provided or selected based on setup of the system
	// launching queries. For example, it may be running UDF servers including
	// in some MPM release, or servers built from source code by the user.
	PerModuleOptions_CALLER_PROVIDED PerModuleOptions_UdfServerImportMode = 2
	// There is no default source for this UDF server. An explicit
	// udf_server_address must be provided.
	PerModuleOptions_MANUAL PerModuleOptions_UdfServerImportMode = 3
)

// Enum value maps for PerModuleOptions_UdfServerImportMode.
var (
	PerModuleOptions_UdfServerImportMode_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVER_ADDRESS_FROM_MODULE",
		2: "CALLER_PROVIDED",
		3: "MANUAL",
	}
	PerModuleOptions_UdfServerImportMode_value = map[string]int32{
		"UNKNOWN":                    0,
		"SERVER_ADDRESS_FROM_MODULE": 1,
		"CALLER_PROVIDED":            2,
		"MANUAL":                     3,
	}
)

func (x PerModuleOptions_UdfServerImportMode) Enum() *PerModuleOptions_UdfServerImportMode {
	p := new(PerModuleOptions_UdfServerImportMode)
	*p = x
	return p
}

func (x PerModuleOptions_UdfServerImportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PerModuleOptions_UdfServerImportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_proto_module_options_proto_enumTypes[0].Descriptor()
}

func (PerModuleOptions_UdfServerImportMode) Type() protoreflect.EnumType {
	return &file_googlesql_proto_module_options_proto_enumTypes[0]
}

func (x PerModuleOptions_UdfServerImportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PerModuleOptions_UdfServerImportMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PerModuleOptions_UdfServerImportMode(num)
	return nil
}

// Deprecated: Use PerModuleOptions_UdfServerImportMode.Descriptor instead.
func (PerModuleOptions_UdfServerImportMode) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_proto_module_options_proto_rawDescGZIP(), []int{0, 0}
}

// All possible options that can be overridden for UDF server modules.
// Next id: 5
type PerModuleOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address of the UDF server that the serves functions in the GoogleSQL
	// module. This takes precedence over the default set in
	// udf_server_import_mode if not empty.
	UdfServerAddress *string `protobuf:"bytes,1,opt,name=udf_server_address,json=udfServerAddress" json:"udf_server_address,omitempty"`
	// The namespace of the UDFs when they are registered.
	UdfNamespace *string `protobuf:"bytes,4,opt,name=udf_namespace,json=udfNamespace" json:"udf_namespace,omitempty"`
	// The default import mode of the UDF server.
	UdfServerImportMode *PerModuleOptions_UdfServerImportMode `protobuf:"varint,2,opt,name=udf_server_import_mode,json=udfServerImportMode,enum=googlesql.PerModuleOptions_UdfServerImportMode,def=1" json:"udf_server_import_mode,omitempty"`
	// A hint of ratio between the number of UDF servers to the number of F1
	// workers.
	UdfScalingFactor *float64 `protobuf:"fixed64,3,opt,name=udf_scaling_factor,json=udfScalingFactor" json:"udf_scaling_factor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for PerModuleOptions fields.
const (
	Default_PerModuleOptions_UdfServerImportMode = PerModuleOptions_SERVER_ADDRESS_FROM_MODULE
)

func (x *PerModuleOptions) Reset() {
	*x = PerModuleOptions{}
	mi := &file_googlesql_proto_module_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerModuleOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerModuleOptions) ProtoMessage() {}

func (x *PerModuleOptions) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_module_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerModuleOptions.ProtoReflect.Descriptor instead.
func (*PerModuleOptions) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_module_options_proto_rawDescGZIP(), []int{0}
}

func (x *PerModuleOptions) GetUdfServerAddress() string {
	if x != nil && x.UdfServerAddress != nil {
		return *x.UdfServerAddress
	}
	return ""
}

func (x *PerModuleOptions) GetUdfNamespace() string {
	if x != nil && x.UdfNamespace != nil {
		return *x.UdfNamespace
	}
	return ""
}

func (x *PerModuleOptions) GetUdfServerImportMode() PerModuleOptions_UdfServerImportMode {
	if x != nil && x.UdfServerImportMode != nil {
		return *x.UdfServerImportMode
	}
	return Default_PerModuleOptions_UdfServerImportMode
}

func (x *PerModuleOptions) GetUdfScalingFactor() float64 {
	if x != nil && x.UdfScalingFactor != nil {
		return *x.UdfScalingFactor
	}
	return 0
}

// This proto is passed to ModuleFactory to control how to find and configure
// UDF servers for UDF server stub modules.
//
// Modules with OPTIONS(stub_module_type='udf_server_catalog') represent the
// functions provided by a particular UDF server. The module OPTIONS can suggest
// a default server to connect to.
//
// These options allow telling the ModuleFactory whether to use that default to
// select servers, or to choose servers another way. The proto allows setting a
// default for all modules, and overriding for specific modules.
// Next id: 3
type ModuleOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This option sets the default for all modules, which can be overridden by
	// `per_module_options`.
	GlobalOptions *PerModuleOptions `protobuf:"bytes,1,opt,name=global_options,json=globalOptions" json:"global_options,omitempty"`
	// Module options for specific modules, keyed by the full module name (the
	// dotted path). Fields set here override the corresponding fields from
	// `global_options` for that module.
	PerModuleOptions map[string]*PerModuleOptions `protobuf:"bytes,2,rep,name=per_module_options,json=perModuleOptions" json:"per_module_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModuleOptions) Reset() {
	*x = ModuleOptions{}
	mi := &file_googlesql_proto_module_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleOptions) ProtoMessage() {}

func (x *ModuleOptions) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_module_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleOptions.ProtoReflect.Descriptor instead.
func (*ModuleOptions) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_module_options_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleOptions) GetGlobalOptions() *PerModuleOptions {
	if x != nil {
		return x.GlobalOptions
	}
	return nil
}

func (x *ModuleOptions) GetPerModuleOptions() map[string]*PerModuleOptions {
	if x != nil {
		return x.PerModuleOptions
	}
	return nil
}

var File_googlesql_proto_module_options_proto protoreflect.FileDescriptor

const file_googlesql_proto_module_options_proto_rawDesc = "" +
	"\n" +
	"$googlesql/proto/module_options.proto\x12\tgooglesql\"\xfb\x02\n" +
	"\x10PerModuleOptions\x12,\n" +
	"\x12udf_server_address\x18\x01 \x01(\tR\x10udfServerAddress\x12#\n" +
	"\rudf_namespace\x18\x04 \x01(\tR\fudfNamespace\x12\x80\x01\n" +
	"\x16udf_server_import_mode\x18\x02 \x01(\x0e2/.googlesql.PerModuleOptions.UdfServerImportMode:\x1aSERVER_ADDRESS_FROM_MODULER\x13udfServerImportMode\x12,\n" +
	"\x12udf_scaling_factor\x18\x03 \x01(\x01R\x10udfScalingFactor\"c\n" +
	"\x13UdfServerImportMode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aSERVER_ADDRESS_FROM_MODULE\x10\x01\x12\x13\n" +
	"\x0fCALLER_PROVIDED\x10\x02\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x03\"\x93\x02\n" +
	"\rModuleOptions\x12B\n" +
	"\x0eglobal_options\x18\x01 \x01(\v2\x1b.googlesql.PerModuleOptionsR\rglobalOptions\x12\\\n" +
	"\x12per_module_options\x18\x02 \x03(\v2..googlesql.ModuleOptions.PerModuleOptionsEntryR\x10perModuleOptions\x1a`\n" +
	"\x15PerModuleOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.googlesql.PerModuleOptionsR\x05value:\x028\x01B\x02P\x01"

var (
	file_googlesql_proto_module_options_proto_rawDescOnce sync.Once
	file_googlesql_proto_module_options_proto_rawDescData []byte
)

func file_googlesql_proto_module_options_proto_rawDescGZIP() []byte {
	file_googlesql_proto_module_options_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_module_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_module_options_proto_rawDesc), len(file_googlesql_proto_module_options_proto_rawDesc)))
	})
	return file_googlesql_proto_module_options_proto_rawDescData
}

var file_googlesql_proto_module_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_googlesql_proto_module_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_googlesql_proto_module_options_proto_goTypes = []any{
	(PerModuleOptions_UdfServerImportMode)(0), // 0: googlesql.PerModuleOptions.UdfServerImportMode
	(*PerModuleOptions)(nil),                  // 1: googlesql.PerModuleOptions
	(*ModuleOptions)(nil),                     // 2: googlesql.ModuleOptions
	nil,                                       // 3: googlesql.ModuleOptions.PerModuleOptionsEntry
}
var file_googlesql_proto_module_options_proto_depIdxs = []int32{
	0, // 0: googlesql.PerModuleOptions.udf_server_import_mode:type_name -> googlesql.PerModuleOptions.UdfServerImportMode
	1, // 1: googlesql.ModuleOptions.global_options:type_name -> googlesql.PerModuleOptions
	3, // 2: googlesql.ModuleOptions.per_module_options:type_name -> googlesql.ModuleOptions.PerModuleOptionsEntry
	1, // 3: googlesql.ModuleOptions.PerModuleOptionsEntry.value:type_name -> googlesql.PerModuleOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_googlesql_proto_module_options_proto_init() }
func file_googlesql_proto_module_options_proto_init() {
	if File_googlesql_proto_module_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_module_options_proto_rawDesc), len(file_googlesql_proto_module_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_module_options_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_module_options_proto_depIdxs,
		EnumInfos:         file_googlesql_proto_module_options_proto_enumTypes,
		MessageInfos:      file_googlesql_proto_module_options_proto_msgTypes,
	}.Build()
	File_googlesql_proto_module_options_proto = out.File
	file_googlesql_proto_module_options_proto_goTypes = nil
	file_googlesql_proto_module_options_proto_depIdxs = nil
}
