//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/options.proto

package googlesql_core

import (
	googlesql_public "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowedHintsAndOptionsProto_OptionProto_ResolvingKind int32

const (
	// Legacy kind - option is either constant or an identifier resolved
	// without any given name scope.
	AllowedHintsAndOptionsProto_OptionProto_CONSTANT_OR_EMPTY_NAME_SCOPE_IDENTIFIER AllowedHintsAndOptionsProto_OptionProto_ResolvingKind = 0
	// Option is an identifier resolved against FROM name scope.
	// See: (broken link).
	AllowedHintsAndOptionsProto_OptionProto_FROM_NAME_SCOPE_IDENTIFIER AllowedHintsAndOptionsProto_OptionProto_ResolvingKind = 1
)

// Enum value maps for AllowedHintsAndOptionsProto_OptionProto_ResolvingKind.
var (
	AllowedHintsAndOptionsProto_OptionProto_ResolvingKind_name = map[int32]string{
		0: "CONSTANT_OR_EMPTY_NAME_SCOPE_IDENTIFIER",
		1: "FROM_NAME_SCOPE_IDENTIFIER",
	}
	AllowedHintsAndOptionsProto_OptionProto_ResolvingKind_value = map[string]int32{
		"CONSTANT_OR_EMPTY_NAME_SCOPE_IDENTIFIER": 0,
		"FROM_NAME_SCOPE_IDENTIFIER":              1,
	}
)

func (x AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) Enum() *AllowedHintsAndOptionsProto_OptionProto_ResolvingKind {
	p := new(AllowedHintsAndOptionsProto_OptionProto_ResolvingKind)
	*p = x
	return p
}

func (x AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_proto_options_proto_enumTypes[0].Descriptor()
}

func (AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) Type() protoreflect.EnumType {
	return &file_googlesql_proto_options_proto_enumTypes[0]
}

func (x AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AllowedHintsAndOptionsProto_OptionProto_ResolvingKind(num)
	return nil
}

// Deprecated: Use AllowedHintsAndOptionsProto_OptionProto_ResolvingKind.Descriptor instead.
func (AllowedHintsAndOptionsProto_OptionProto_ResolvingKind) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{3, 1, 0}
}

// Specify what built-in functions should be load.
// Used for getting built-in functions through local server.
type GoogleSQLBuiltinFunctionOptionsProto struct {
	state                   protoimpl.MessageState                 `protogen:"open.v1"`
	LanguageOptions         *LanguageOptionsProto                  `protobuf:"bytes,1,opt,name=language_options,json=languageOptions" json:"language_options,omitempty"`
	IncludeFunctionIds      []googlesql_public.FunctionSignatureId `protobuf:"varint,2,rep,name=include_function_ids,json=includeFunctionIds,enum=googlesql.FunctionSignatureId" json:"include_function_ids,omitempty"`
	ExcludeFunctionIds      []googlesql_public.FunctionSignatureId `protobuf:"varint,3,rep,name=exclude_function_ids,json=excludeFunctionIds,enum=googlesql.FunctionSignatureId" json:"exclude_function_ids,omitempty"`
	EnabledRewritesMapEntry []*EnabledRewriteProto                 `protobuf:"bytes,4,rep,name=enabled_rewrites_map_entry,json=enabledRewritesMapEntry" json:"enabled_rewrites_map_entry,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GoogleSQLBuiltinFunctionOptionsProto) Reset() {
	*x = GoogleSQLBuiltinFunctionOptionsProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleSQLBuiltinFunctionOptionsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleSQLBuiltinFunctionOptionsProto) ProtoMessage() {}

func (x *GoogleSQLBuiltinFunctionOptionsProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleSQLBuiltinFunctionOptionsProto.ProtoReflect.Descriptor instead.
func (*GoogleSQLBuiltinFunctionOptionsProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleSQLBuiltinFunctionOptionsProto) GetLanguageOptions() *LanguageOptionsProto {
	if x != nil {
		return x.LanguageOptions
	}
	return nil
}

func (x *GoogleSQLBuiltinFunctionOptionsProto) GetIncludeFunctionIds() []googlesql_public.FunctionSignatureId {
	if x != nil {
		return x.IncludeFunctionIds
	}
	return nil
}

func (x *GoogleSQLBuiltinFunctionOptionsProto) GetExcludeFunctionIds() []googlesql_public.FunctionSignatureId {
	if x != nil {
		return x.ExcludeFunctionIds
	}
	return nil
}

func (x *GoogleSQLBuiltinFunctionOptionsProto) GetEnabledRewritesMapEntry() []*EnabledRewriteProto {
	if x != nil {
		return x.EnabledRewritesMapEntry
	}
	return nil
}

type EnabledRewriteProto struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Key           *googlesql_public.FunctionSignatureId `protobuf:"varint,1,opt,name=key,enum=googlesql.FunctionSignatureId" json:"key,omitempty"`
	Value         *bool                                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnabledRewriteProto) Reset() {
	*x = EnabledRewriteProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnabledRewriteProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnabledRewriteProto) ProtoMessage() {}

func (x *EnabledRewriteProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnabledRewriteProto.ProtoReflect.Descriptor instead.
func (*EnabledRewriteProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{1}
}

func (x *EnabledRewriteProto) GetKey() googlesql_public.FunctionSignatureId {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return googlesql_public.FunctionSignatureId(-1)
}

func (x *EnabledRewriteProto) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

// Serialized form of LanguageOptions.
type LanguageOptionsProto struct {
	state                          protoimpl.MessageState               `protogen:"open.v1"`
	NameResolutionMode             *googlesql_public.NameResolutionMode `protobuf:"varint,2,opt,name=name_resolution_mode,json=nameResolutionMode,enum=googlesql.NameResolutionMode" json:"name_resolution_mode,omitempty"`
	ProductMode                    *googlesql_public.ProductMode        `protobuf:"varint,3,opt,name=product_mode,json=productMode,enum=googlesql.ProductMode" json:"product_mode,omitempty"`
	ErrorOnDeprecatedSyntax        *bool                                `protobuf:"varint,4,opt,name=error_on_deprecated_syntax,json=errorOnDeprecatedSyntax" json:"error_on_deprecated_syntax,omitempty"`
	EnabledLanguageFeatures        []googlesql_public.LanguageFeature   `protobuf:"varint,5,rep,name=enabled_language_features,json=enabledLanguageFeatures,enum=googlesql.LanguageFeature" json:"enabled_language_features,omitempty"`
	SupportedStatementKinds        []ResolvedNodeKind                   `protobuf:"varint,6,rep,name=supported_statement_kinds,json=supportedStatementKinds,enum=googlesql.ResolvedNodeKind" json:"supported_statement_kinds,omitempty"`
	SupportedGenericEntityTypes    []string                             `protobuf:"bytes,7,rep,name=supported_generic_entity_types,json=supportedGenericEntityTypes" json:"supported_generic_entity_types,omitempty"`
	ReservedKeywords               []string                             `protobuf:"bytes,8,rep,name=reserved_keywords,json=reservedKeywords" json:"reserved_keywords,omitempty"`
	SupportedGenericSubEntityTypes []string                             `protobuf:"bytes,9,rep,name=supported_generic_sub_entity_types,json=supportedGenericSubEntityTypes" json:"supported_generic_sub_entity_types,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *LanguageOptionsProto) Reset() {
	*x = LanguageOptionsProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageOptionsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageOptionsProto) ProtoMessage() {}

func (x *LanguageOptionsProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageOptionsProto.ProtoReflect.Descriptor instead.
func (*LanguageOptionsProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{2}
}

func (x *LanguageOptionsProto) GetNameResolutionMode() googlesql_public.NameResolutionMode {
	if x != nil && x.NameResolutionMode != nil {
		return *x.NameResolutionMode
	}
	return googlesql_public.NameResolutionMode(0)
}

func (x *LanguageOptionsProto) GetProductMode() googlesql_public.ProductMode {
	if x != nil && x.ProductMode != nil {
		return *x.ProductMode
	}
	return googlesql_public.ProductMode(0)
}

func (x *LanguageOptionsProto) GetErrorOnDeprecatedSyntax() bool {
	if x != nil && x.ErrorOnDeprecatedSyntax != nil {
		return *x.ErrorOnDeprecatedSyntax
	}
	return false
}

func (x *LanguageOptionsProto) GetEnabledLanguageFeatures() []googlesql_public.LanguageFeature {
	if x != nil {
		return x.EnabledLanguageFeatures
	}
	return nil
}

func (x *LanguageOptionsProto) GetSupportedStatementKinds() []ResolvedNodeKind {
	if x != nil {
		return x.SupportedStatementKinds
	}
	return nil
}

func (x *LanguageOptionsProto) GetSupportedGenericEntityTypes() []string {
	if x != nil {
		return x.SupportedGenericEntityTypes
	}
	return nil
}

func (x *LanguageOptionsProto) GetReservedKeywords() []string {
	if x != nil {
		return x.ReservedKeywords
	}
	return nil
}

func (x *LanguageOptionsProto) GetSupportedGenericSubEntityTypes() []string {
	if x != nil {
		return x.SupportedGenericSubEntityTypes
	}
	return nil
}

// Serialized form of AllowedHintsAndOptions.
type AllowedHintsAndOptionsProto struct {
	state                             protoimpl.MessageState                     `protogen:"open.v1"`
	DisallowUnknownOptions            *bool                                      `protobuf:"varint,1,opt,name=disallow_unknown_options,json=disallowUnknownOptions" json:"disallow_unknown_options,omitempty"`
	DisallowUnknownHintsWithQualifier []string                                   `protobuf:"bytes,2,rep,name=disallow_unknown_hints_with_qualifier,json=disallowUnknownHintsWithQualifier" json:"disallow_unknown_hints_with_qualifier,omitempty"`
	Hint                              []*AllowedHintsAndOptionsProto_HintProto   `protobuf:"bytes,3,rep,name=hint" json:"hint,omitempty"`
	Option                            []*AllowedHintsAndOptionsProto_OptionProto `protobuf:"bytes,4,rep,name=option" json:"option,omitempty"`
	AnonymizationOption               []*AllowedHintsAndOptionsProto_OptionProto `protobuf:"bytes,5,rep,name=anonymization_option,json=anonymizationOption" json:"anonymization_option,omitempty"`
	DifferentialPrivacyOption         []*AllowedHintsAndOptionsProto_OptionProto `protobuf:"bytes,6,rep,name=differential_privacy_option,json=differentialPrivacyOption" json:"differential_privacy_option,omitempty"`
	DisallowDuplicateOptionNames      *bool                                      `protobuf:"varint,7,opt,name=disallow_duplicate_option_names,json=disallowDuplicateOptionNames" json:"disallow_duplicate_option_names,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *AllowedHintsAndOptionsProto) Reset() {
	*x = AllowedHintsAndOptionsProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedHintsAndOptionsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedHintsAndOptionsProto) ProtoMessage() {}

func (x *AllowedHintsAndOptionsProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedHintsAndOptionsProto.ProtoReflect.Descriptor instead.
func (*AllowedHintsAndOptionsProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{3}
}

func (x *AllowedHintsAndOptionsProto) GetDisallowUnknownOptions() bool {
	if x != nil && x.DisallowUnknownOptions != nil {
		return *x.DisallowUnknownOptions
	}
	return false
}

func (x *AllowedHintsAndOptionsProto) GetDisallowUnknownHintsWithQualifier() []string {
	if x != nil {
		return x.DisallowUnknownHintsWithQualifier
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto) GetHint() []*AllowedHintsAndOptionsProto_HintProto {
	if x != nil {
		return x.Hint
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto) GetOption() []*AllowedHintsAndOptionsProto_OptionProto {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto) GetAnonymizationOption() []*AllowedHintsAndOptionsProto_OptionProto {
	if x != nil {
		return x.AnonymizationOption
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto) GetDifferentialPrivacyOption() []*AllowedHintsAndOptionsProto_OptionProto {
	if x != nil {
		return x.DifferentialPrivacyOption
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto) GetDisallowDuplicateOptionNames() bool {
	if x != nil && x.DisallowDuplicateOptionNames != nil {
		return *x.DisallowDuplicateOptionNames
	}
	return false
}

// Serialized form of AnalyzerOptions.
// next id: 33
type AnalyzerOptionsProto struct {
	state                     protoimpl.MessageState                      `protogen:"open.v1"`
	LanguageOptions           *LanguageOptionsProto                       `protobuf:"bytes,1,opt,name=language_options,json=languageOptions" json:"language_options,omitempty"`
	QueryParameters           []*AnalyzerOptionsProto_QueryParameterProto `protobuf:"bytes,2,rep,name=query_parameters,json=queryParameters" json:"query_parameters,omitempty"`
	PositionalQueryParameters []*googlesql_public.TypeProto               `protobuf:"bytes,12,rep,name=positional_query_parameters,json=positionalQueryParameters" json:"positional_query_parameters,omitempty"`
	ExpressionColumns         []*AnalyzerOptionsProto_QueryParameterProto `protobuf:"bytes,3,rep,name=expression_columns,json=expressionColumns" json:"expression_columns,omitempty"`
	GraphProperties           []*AnalyzerOptionsProto_QueryParameterProto `protobuf:"bytes,32,rep,name=graph_properties,json=graphProperties" json:"graph_properties,omitempty"`
	InScopeExpressionColumn   *AnalyzerOptionsProto_QueryParameterProto   `protobuf:"bytes,4,opt,name=in_scope_expression_column,json=inScopeExpressionColumn" json:"in_scope_expression_column,omitempty"`
	DdlPseudoColumns          []*AnalyzerOptionsProto_QueryParameterProto `protobuf:"bytes,15,rep,name=ddl_pseudo_columns,json=ddlPseudoColumns" json:"ddl_pseudo_columns,omitempty"`
	// base::SequenceNumber does not support getting and setting the current
	// value, so it is not serializable. Reserving tag number 5 in case we want
	// to support it in some other way later.
	ErrorMessageMode *googlesql_public.ErrorMessageMode `protobuf:"varint,6,opt,name=error_message_mode,json=errorMessageMode,enum=googlesql.ErrorMessageMode" json:"error_message_mode,omitempty"`
	// In the form that can be parsed by C++ absl::LoadTimeZone().
	DefaultTimezone                                   *string                                     `protobuf:"bytes,7,opt,name=default_timezone,json=defaultTimezone" json:"default_timezone,omitempty"`
	CreateNewColumnForEachProjectedOutput             *bool                                       `protobuf:"varint,20,opt,name=create_new_column_for_each_projected_output,json=createNewColumnForEachProjectedOutput" json:"create_new_column_for_each_projected_output,omitempty"`
	PruneUnusedColumns                                *bool                                       `protobuf:"varint,9,opt,name=prune_unused_columns,json=pruneUnusedColumns" json:"prune_unused_columns,omitempty"`
	AllowUndeclaredParameters                         *bool                                       `protobuf:"varint,10,opt,name=allow_undeclared_parameters,json=allowUndeclaredParameters" json:"allow_undeclared_parameters,omitempty"`
	ParameterMode                                     *googlesql_public.ParameterMode             `protobuf:"varint,13,opt,name=parameter_mode,json=parameterMode,enum=googlesql.ParameterMode" json:"parameter_mode,omitempty"`
	AllowedHintsAndOptions                            *AllowedHintsAndOptionsProto                `protobuf:"bytes,11,opt,name=allowed_hints_and_options,json=allowedHintsAndOptions" json:"allowed_hints_and_options,omitempty"`
	StatementContext                                  *googlesql_public.StatementContext          `protobuf:"varint,14,opt,name=statement_context,json=statementContext,enum=googlesql.StatementContext" json:"statement_context,omitempty"`
	PreserveColumnAliases                             *bool                                       `protobuf:"varint,17,opt,name=preserve_column_aliases,json=preserveColumnAliases" json:"preserve_column_aliases,omitempty"`
	SystemVariables                                   []*AnalyzerOptionsProto_SystemVariableProto `protobuf:"bytes,18,rep,name=system_variables,json=systemVariables" json:"system_variables,omitempty"`
	TargetColumnTypes                                 []*googlesql_public.TypeProto               `protobuf:"bytes,19,rep,name=target_column_types,json=targetColumnTypes" json:"target_column_types,omitempty"`
	EnabledRewrites                                   []googlesql_public.ResolvedASTRewrite       `protobuf:"varint,21,rep,name=enabled_rewrites,json=enabledRewrites,enum=googlesql.ResolvedASTRewrite" json:"enabled_rewrites,omitempty"`
	ParseLocationRecordType                           *googlesql_public.ParseLocationRecordType   `protobuf:"varint,23,opt,name=parse_location_record_type,json=parseLocationRecordType,enum=googlesql.ParseLocationRecordType" json:"parse_location_record_type,omitempty"`
	PreserveUnnecessaryCast                           *bool                                       `protobuf:"varint,24,opt,name=preserve_unnecessary_cast,json=preserveUnnecessaryCast" json:"preserve_unnecessary_cast,omitempty"`
	DefaultAnonFunctionReportFormat                   *string                                     `protobuf:"bytes,25,opt,name=default_anon_function_report_format,json=defaultAnonFunctionReportFormat" json:"default_anon_function_report_format,omitempty"`
	DefaultAnonKappaValue                             *int64                                      `protobuf:"varint,26,opt,name=default_anon_kappa_value,json=defaultAnonKappaValue" json:"default_anon_kappa_value,omitempty"`
	RewriteOptions                                    *googlesql_public.RewriteOptions            `protobuf:"bytes,28,opt,name=rewrite_options,json=rewriteOptions" json:"rewrite_options,omitempty"`
	ReplaceTableNotFoundErrorWithTvfErrorIfApplicable *bool                                       `protobuf:"varint,29,opt,name=replace_table_not_found_error_with_tvf_error_if_applicable,json=replaceTableNotFoundErrorWithTvfErrorIfApplicable" json:"replace_table_not_found_error_with_tvf_error_if_applicable,omitempty"`
	LogImpactOfLateralColumnReferences                *bool                                       `protobuf:"varint,31,opt,name=log_impact_of_lateral_column_references,json=logImpactOfLateralColumnReferences" json:"log_impact_of_lateral_column_references,omitempty"`
	unknownFields                                     protoimpl.UnknownFields
	sizeCache                                         protoimpl.SizeCache
}

func (x *AnalyzerOptionsProto) Reset() {
	*x = AnalyzerOptionsProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzerOptionsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerOptionsProto) ProtoMessage() {}

func (x *AnalyzerOptionsProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerOptionsProto.ProtoReflect.Descriptor instead.
func (*AnalyzerOptionsProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzerOptionsProto) GetLanguageOptions() *LanguageOptionsProto {
	if x != nil {
		return x.LanguageOptions
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetQueryParameters() []*AnalyzerOptionsProto_QueryParameterProto {
	if x != nil {
		return x.QueryParameters
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetPositionalQueryParameters() []*googlesql_public.TypeProto {
	if x != nil {
		return x.PositionalQueryParameters
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetExpressionColumns() []*AnalyzerOptionsProto_QueryParameterProto {
	if x != nil {
		return x.ExpressionColumns
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetGraphProperties() []*AnalyzerOptionsProto_QueryParameterProto {
	if x != nil {
		return x.GraphProperties
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetInScopeExpressionColumn() *AnalyzerOptionsProto_QueryParameterProto {
	if x != nil {
		return x.InScopeExpressionColumn
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetDdlPseudoColumns() []*AnalyzerOptionsProto_QueryParameterProto {
	if x != nil {
		return x.DdlPseudoColumns
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetErrorMessageMode() googlesql_public.ErrorMessageMode {
	if x != nil && x.ErrorMessageMode != nil {
		return *x.ErrorMessageMode
	}
	return googlesql_public.ErrorMessageMode(0)
}

func (x *AnalyzerOptionsProto) GetDefaultTimezone() string {
	if x != nil && x.DefaultTimezone != nil {
		return *x.DefaultTimezone
	}
	return ""
}

func (x *AnalyzerOptionsProto) GetCreateNewColumnForEachProjectedOutput() bool {
	if x != nil && x.CreateNewColumnForEachProjectedOutput != nil {
		return *x.CreateNewColumnForEachProjectedOutput
	}
	return false
}

func (x *AnalyzerOptionsProto) GetPruneUnusedColumns() bool {
	if x != nil && x.PruneUnusedColumns != nil {
		return *x.PruneUnusedColumns
	}
	return false
}

func (x *AnalyzerOptionsProto) GetAllowUndeclaredParameters() bool {
	if x != nil && x.AllowUndeclaredParameters != nil {
		return *x.AllowUndeclaredParameters
	}
	return false
}

func (x *AnalyzerOptionsProto) GetParameterMode() googlesql_public.ParameterMode {
	if x != nil && x.ParameterMode != nil {
		return *x.ParameterMode
	}
	return googlesql_public.ParameterMode(0)
}

func (x *AnalyzerOptionsProto) GetAllowedHintsAndOptions() *AllowedHintsAndOptionsProto {
	if x != nil {
		return x.AllowedHintsAndOptions
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetStatementContext() googlesql_public.StatementContext {
	if x != nil && x.StatementContext != nil {
		return *x.StatementContext
	}
	return googlesql_public.StatementContext(0)
}

func (x *AnalyzerOptionsProto) GetPreserveColumnAliases() bool {
	if x != nil && x.PreserveColumnAliases != nil {
		return *x.PreserveColumnAliases
	}
	return false
}

func (x *AnalyzerOptionsProto) GetSystemVariables() []*AnalyzerOptionsProto_SystemVariableProto {
	if x != nil {
		return x.SystemVariables
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetTargetColumnTypes() []*googlesql_public.TypeProto {
	if x != nil {
		return x.TargetColumnTypes
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetEnabledRewrites() []googlesql_public.ResolvedASTRewrite {
	if x != nil {
		return x.EnabledRewrites
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetParseLocationRecordType() googlesql_public.ParseLocationRecordType {
	if x != nil && x.ParseLocationRecordType != nil {
		return *x.ParseLocationRecordType
	}
	return googlesql_public.ParseLocationRecordType(0)
}

func (x *AnalyzerOptionsProto) GetPreserveUnnecessaryCast() bool {
	if x != nil && x.PreserveUnnecessaryCast != nil {
		return *x.PreserveUnnecessaryCast
	}
	return false
}

func (x *AnalyzerOptionsProto) GetDefaultAnonFunctionReportFormat() string {
	if x != nil && x.DefaultAnonFunctionReportFormat != nil {
		return *x.DefaultAnonFunctionReportFormat
	}
	return ""
}

func (x *AnalyzerOptionsProto) GetDefaultAnonKappaValue() int64 {
	if x != nil && x.DefaultAnonKappaValue != nil {
		return *x.DefaultAnonKappaValue
	}
	return 0
}

func (x *AnalyzerOptionsProto) GetRewriteOptions() *googlesql_public.RewriteOptions {
	if x != nil {
		return x.RewriteOptions
	}
	return nil
}

func (x *AnalyzerOptionsProto) GetReplaceTableNotFoundErrorWithTvfErrorIfApplicable() bool {
	if x != nil && x.ReplaceTableNotFoundErrorWithTvfErrorIfApplicable != nil {
		return *x.ReplaceTableNotFoundErrorWithTvfErrorIfApplicable
	}
	return false
}

func (x *AnalyzerOptionsProto) GetLogImpactOfLateralColumnReferences() bool {
	if x != nil && x.LogImpactOfLateralColumnReferences != nil {
		return *x.LogImpactOfLateralColumnReferences
	}
	return false
}

type AllowedHintsAndOptionsProto_HintProto struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Qualifier        *string                     `protobuf:"bytes,1,opt,name=qualifier" json:"qualifier,omitempty"`
	Name             *string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type             *googlesql_public.TypeProto `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	AllowUnqualified *bool                       `protobuf:"varint,4,opt,name=allow_unqualified,json=allowUnqualified" json:"allow_unqualified,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllowedHintsAndOptionsProto_HintProto) Reset() {
	*x = AllowedHintsAndOptionsProto_HintProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedHintsAndOptionsProto_HintProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedHintsAndOptionsProto_HintProto) ProtoMessage() {}

func (x *AllowedHintsAndOptionsProto_HintProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedHintsAndOptionsProto_HintProto.ProtoReflect.Descriptor instead.
func (*AllowedHintsAndOptionsProto_HintProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AllowedHintsAndOptionsProto_HintProto) GetQualifier() string {
	if x != nil && x.Qualifier != nil {
		return *x.Qualifier
	}
	return ""
}

func (x *AllowedHintsAndOptionsProto_HintProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AllowedHintsAndOptionsProto_HintProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto_HintProto) GetAllowUnqualified() bool {
	if x != nil && x.AllowUnqualified != nil {
		return *x.AllowUnqualified
	}
	return false
}

type AllowedHintsAndOptionsProto_OptionProto struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	Name          *string                                                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type          *googlesql_public.TypeProto                            `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	ResolvingKind *AllowedHintsAndOptionsProto_OptionProto_ResolvingKind `protobuf:"varint,3,opt,name=resolving_kind,json=resolvingKind,enum=googlesql.AllowedHintsAndOptionsProto_OptionProto_ResolvingKind" json:"resolving_kind,omitempty"`
	// Indicates whether the "+=" and "-=" assignment operators are allowed for
	// fields of Array type.
	AllowAlterArray *bool `protobuf:"varint,4,opt,name=allow_alter_array,json=allowAlterArray" json:"allow_alter_array,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllowedHintsAndOptionsProto_OptionProto) Reset() {
	*x = AllowedHintsAndOptionsProto_OptionProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedHintsAndOptionsProto_OptionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedHintsAndOptionsProto_OptionProto) ProtoMessage() {}

func (x *AllowedHintsAndOptionsProto_OptionProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedHintsAndOptionsProto_OptionProto.ProtoReflect.Descriptor instead.
func (*AllowedHintsAndOptionsProto_OptionProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AllowedHintsAndOptionsProto_OptionProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AllowedHintsAndOptionsProto_OptionProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AllowedHintsAndOptionsProto_OptionProto) GetResolvingKind() AllowedHintsAndOptionsProto_OptionProto_ResolvingKind {
	if x != nil && x.ResolvingKind != nil {
		return *x.ResolvingKind
	}
	return AllowedHintsAndOptionsProto_OptionProto_CONSTANT_OR_EMPTY_NAME_SCOPE_IDENTIFIER
}

func (x *AllowedHintsAndOptionsProto_OptionProto) GetAllowAlterArray() bool {
	if x != nil && x.AllowAlterArray != nil {
		return *x.AllowAlterArray
	}
	return false
}

type AnalyzerOptionsProto_QueryParameterProto struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          *string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type          *googlesql_public.TypeProto `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzerOptionsProto_QueryParameterProto) Reset() {
	*x = AnalyzerOptionsProto_QueryParameterProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzerOptionsProto_QueryParameterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerOptionsProto_QueryParameterProto) ProtoMessage() {}

func (x *AnalyzerOptionsProto_QueryParameterProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerOptionsProto_QueryParameterProto.ProtoReflect.Descriptor instead.
func (*AnalyzerOptionsProto_QueryParameterProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AnalyzerOptionsProto_QueryParameterProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AnalyzerOptionsProto_QueryParameterProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

type AnalyzerOptionsProto_SystemVariableProto struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	NamePath      []string                    `protobuf:"bytes,1,rep,name=name_path,json=namePath" json:"name_path,omitempty"`
	Type          *googlesql_public.TypeProto `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzerOptionsProto_SystemVariableProto) Reset() {
	*x = AnalyzerOptionsProto_SystemVariableProto{}
	mi := &file_googlesql_proto_options_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzerOptionsProto_SystemVariableProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerOptionsProto_SystemVariableProto) ProtoMessage() {}

func (x *AnalyzerOptionsProto_SystemVariableProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_options_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerOptionsProto_SystemVariableProto.ProtoReflect.Descriptor instead.
func (*AnalyzerOptionsProto_SystemVariableProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_options_proto_rawDescGZIP(), []int{4, 1}
}

func (x *AnalyzerOptionsProto_SystemVariableProto) GetNamePath() []string {
	if x != nil {
		return x.NamePath
	}
	return nil
}

func (x *AnalyzerOptionsProto_SystemVariableProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_googlesql_proto_options_proto protoreflect.FileDescriptor

const file_googlesql_proto_options_proto_rawDesc = "" +
	"\n" +
	"\x1dgooglesql/proto/options.proto\x12\tgooglesql\x1a'googlesql/public/builtin_function.proto\x1a\x1egooglesql/public/options.proto\x1a\x1bgooglesql/public/type.proto\x1a/googlesql/resolved_ast/resolved_node_kind.proto\"\xf3\x02\n" +
	"$GoogleSQLBuiltinFunctionOptionsProto\x12J\n" +
	"\x10language_options\x18\x01 \x01(\v2\x1f.googlesql.LanguageOptionsProtoR\x0flanguageOptions\x12P\n" +
	"\x14include_function_ids\x18\x02 \x03(\x0e2\x1e.googlesql.FunctionSignatureIdR\x12includeFunctionIds\x12P\n" +
	"\x14exclude_function_ids\x18\x03 \x03(\x0e2\x1e.googlesql.FunctionSignatureIdR\x12excludeFunctionIds\x12[\n" +
	"\x1aenabled_rewrites_map_entry\x18\x04 \x03(\v2\x1e.googlesql.EnabledRewriteProtoR\x17enabledRewritesMapEntry\"]\n" +
	"\x13EnabledRewriteProto\x120\n" +
	"\x03key\x18\x01 \x01(\x0e2\x1e.googlesql.FunctionSignatureIdR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"\xd4\x04\n" +
	"\x14LanguageOptionsProto\x12O\n" +
	"\x14name_resolution_mode\x18\x02 \x01(\x0e2\x1d.googlesql.NameResolutionModeR\x12nameResolutionMode\x129\n" +
	"\fproduct_mode\x18\x03 \x01(\x0e2\x16.googlesql.ProductModeR\vproductMode\x12;\n" +
	"\x1aerror_on_deprecated_syntax\x18\x04 \x01(\bR\x17errorOnDeprecatedSyntax\x12V\n" +
	"\x19enabled_language_features\x18\x05 \x03(\x0e2\x1a.googlesql.LanguageFeatureR\x17enabledLanguageFeatures\x12W\n" +
	"\x19supported_statement_kinds\x18\x06 \x03(\x0e2\x1b.googlesql.ResolvedNodeKindR\x17supportedStatementKinds\x12C\n" +
	"\x1esupported_generic_entity_types\x18\a \x03(\tR\x1bsupportedGenericEntityTypes\x12+\n" +
	"\x11reserved_keywords\x18\b \x03(\tR\x10reservedKeywords\x12J\n" +
	"\"supported_generic_sub_entity_types\x18\t \x03(\tR\x1esupportedGenericSubEntityTypesJ\x04\b\x01\x10\x02\"\xb5\b\n" +
	"\x1bAllowedHintsAndOptionsProto\x128\n" +
	"\x18disallow_unknown_options\x18\x01 \x01(\bR\x16disallowUnknownOptions\x12P\n" +
	"%disallow_unknown_hints_with_qualifier\x18\x02 \x03(\tR!disallowUnknownHintsWithQualifier\x12D\n" +
	"\x04hint\x18\x03 \x03(\v20.googlesql.AllowedHintsAndOptionsProto.HintProtoR\x04hint\x12J\n" +
	"\x06option\x18\x04 \x03(\v22.googlesql.AllowedHintsAndOptionsProto.OptionProtoR\x06option\x12e\n" +
	"\x14anonymization_option\x18\x05 \x03(\v22.googlesql.AllowedHintsAndOptionsProto.OptionProtoR\x13anonymizationOption\x12r\n" +
	"\x1bdifferential_privacy_option\x18\x06 \x03(\v22.googlesql.AllowedHintsAndOptionsProto.OptionProtoR\x19differentialPrivacyOption\x12E\n" +
	"\x1fdisallow_duplicate_option_names\x18\a \x01(\bR\x1cdisallowDuplicateOptionNames\x1a\x94\x01\n" +
	"\tHintProto\x12\x1c\n" +
	"\tqualifier\x18\x01 \x01(\tR\tqualifier\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x03 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x12+\n" +
	"\x11allow_unqualified\x18\x04 \x01(\bR\x10allowUnqualified\x1a\xbe\x02\n" +
	"\vOptionProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x12g\n" +
	"\x0eresolving_kind\x18\x03 \x01(\x0e2@.googlesql.AllowedHintsAndOptionsProto.OptionProto.ResolvingKindR\rresolvingKind\x12*\n" +
	"\x11allow_alter_array\x18\x04 \x01(\bR\x0fallowAlterArray\"\\\n" +
	"\rResolvingKind\x12+\n" +
	"'CONSTANT_OR_EMPTY_NAME_SCOPE_IDENTIFIER\x10\x00\x12\x1e\n" +
	"\x1aFROM_NAME_SCOPE_IDENTIFIER\x10\x01\"\x8a\x12\n" +
	"\x14AnalyzerOptionsProto\x12J\n" +
	"\x10language_options\x18\x01 \x01(\v2\x1f.googlesql.LanguageOptionsProtoR\x0flanguageOptions\x12^\n" +
	"\x10query_parameters\x18\x02 \x03(\v23.googlesql.AnalyzerOptionsProto.QueryParameterProtoR\x0fqueryParameters\x12T\n" +
	"\x1bpositional_query_parameters\x18\f \x03(\v2\x14.googlesql.TypeProtoR\x19positionalQueryParameters\x12b\n" +
	"\x12expression_columns\x18\x03 \x03(\v23.googlesql.AnalyzerOptionsProto.QueryParameterProtoR\x11expressionColumns\x12^\n" +
	"\x10graph_properties\x18  \x03(\v23.googlesql.AnalyzerOptionsProto.QueryParameterProtoR\x0fgraphProperties\x12p\n" +
	"\x1ain_scope_expression_column\x18\x04 \x01(\v23.googlesql.AnalyzerOptionsProto.QueryParameterProtoR\x17inScopeExpressionColumn\x12a\n" +
	"\x12ddl_pseudo_columns\x18\x0f \x03(\v23.googlesql.AnalyzerOptionsProto.QueryParameterProtoR\x10ddlPseudoColumns\x12I\n" +
	"\x12error_message_mode\x18\x06 \x01(\x0e2\x1b.googlesql.ErrorMessageModeR\x10errorMessageMode\x12)\n" +
	"\x10default_timezone\x18\a \x01(\tR\x0fdefaultTimezone\x12Z\n" +
	"+create_new_column_for_each_projected_output\x18\x14 \x01(\bR%createNewColumnForEachProjectedOutput\x120\n" +
	"\x14prune_unused_columns\x18\t \x01(\bR\x12pruneUnusedColumns\x12>\n" +
	"\x1ballow_undeclared_parameters\x18\n" +
	" \x01(\bR\x19allowUndeclaredParameters\x12?\n" +
	"\x0eparameter_mode\x18\r \x01(\x0e2\x18.googlesql.ParameterModeR\rparameterMode\x12a\n" +
	"\x19allowed_hints_and_options\x18\v \x01(\v2&.googlesql.AllowedHintsAndOptionsProtoR\x16allowedHintsAndOptions\x12H\n" +
	"\x11statement_context\x18\x0e \x01(\x0e2\x1b.googlesql.StatementContextR\x10statementContext\x126\n" +
	"\x17preserve_column_aliases\x18\x11 \x01(\bR\x15preserveColumnAliases\x12^\n" +
	"\x10system_variables\x18\x12 \x03(\v23.googlesql.AnalyzerOptionsProto.SystemVariableProtoR\x0fsystemVariables\x12D\n" +
	"\x13target_column_types\x18\x13 \x03(\v2\x14.googlesql.TypeProtoR\x11targetColumnTypes\x12H\n" +
	"\x10enabled_rewrites\x18\x15 \x03(\x0e2\x1d.googlesql.ResolvedASTRewriteR\x0fenabledRewrites\x12_\n" +
	"\x1aparse_location_record_type\x18\x17 \x01(\x0e2\".googlesql.ParseLocationRecordTypeR\x17parseLocationRecordType\x12:\n" +
	"\x19preserve_unnecessary_cast\x18\x18 \x01(\bR\x17preserveUnnecessaryCast\x12L\n" +
	"#default_anon_function_report_format\x18\x19 \x01(\tR\x1fdefaultAnonFunctionReportFormat\x127\n" +
	"\x18default_anon_kappa_value\x18\x1a \x01(\x03R\x15defaultAnonKappaValue\x12B\n" +
	"\x0frewrite_options\x18\x1c \x01(\v2\x19.googlesql.RewriteOptionsR\x0erewriteOptions\x12u\n" +
	":replace_table_not_found_error_with_tvf_error_if_applicable\x18\x1d \x01(\bR1replaceTableNotFoundErrorWithTvfErrorIfApplicable\x12S\n" +
	"'log_impact_of_lateral_column_references\x18\x1f \x01(\bR\"logImpactOfLateralColumnReferences\x1aS\n" +
	"\x13QueryParameterProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x1a\\\n" +
	"\x13SystemVariableProto\x12\x1b\n" +
	"\tname_path\x18\x01 \x03(\tR\bnamePath\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.googlesql.TypeProtoR\x04typeJ\x04\b\b\x10\tJ\x04\b\x16\x10\x17J\x04\b\x10\x10\x11J\x04\b\x1b\x10\x1cB-\n" +
	"\x14com.google.googlesqlB\x15GoogleSQLOptionsProto"

var (
	file_googlesql_proto_options_proto_rawDescOnce sync.Once
	file_googlesql_proto_options_proto_rawDescData []byte
)

func file_googlesql_proto_options_proto_rawDescGZIP() []byte {
	file_googlesql_proto_options_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_options_proto_rawDesc), len(file_googlesql_proto_options_proto_rawDesc)))
	})
	return file_googlesql_proto_options_proto_rawDescData
}

var file_googlesql_proto_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_googlesql_proto_options_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_googlesql_proto_options_proto_goTypes = []any{
	(AllowedHintsAndOptionsProto_OptionProto_ResolvingKind)(0), // 0: googlesql.AllowedHintsAndOptionsProto.OptionProto.ResolvingKind
	(*GoogleSQLBuiltinFunctionOptionsProto)(nil),               // 1: googlesql.GoogleSQLBuiltinFunctionOptionsProto
	(*EnabledRewriteProto)(nil),                                // 2: googlesql.EnabledRewriteProto
	(*LanguageOptionsProto)(nil),                               // 3: googlesql.LanguageOptionsProto
	(*AllowedHintsAndOptionsProto)(nil),                        // 4: googlesql.AllowedHintsAndOptionsProto
	(*AnalyzerOptionsProto)(nil),                               // 5: googlesql.AnalyzerOptionsProto
	(*AllowedHintsAndOptionsProto_HintProto)(nil),              // 6: googlesql.AllowedHintsAndOptionsProto.HintProto
	(*AllowedHintsAndOptionsProto_OptionProto)(nil),            // 7: googlesql.AllowedHintsAndOptionsProto.OptionProto
	(*AnalyzerOptionsProto_QueryParameterProto)(nil),           // 8: googlesql.AnalyzerOptionsProto.QueryParameterProto
	(*AnalyzerOptionsProto_SystemVariableProto)(nil),           // 9: googlesql.AnalyzerOptionsProto.SystemVariableProto
	(googlesql_public.FunctionSignatureId)(0),                  // 10: googlesql.FunctionSignatureId
	(googlesql_public.NameResolutionMode)(0),                   // 11: googlesql.NameResolutionMode
	(googlesql_public.ProductMode)(0),                          // 12: googlesql.ProductMode
	(googlesql_public.LanguageFeature)(0),                      // 13: googlesql.LanguageFeature
	(ResolvedNodeKind)(0),                                      // 14: googlesql.ResolvedNodeKind
	(*googlesql_public.TypeProto)(nil),                         // 15: googlesql.TypeProto
	(googlesql_public.ErrorMessageMode)(0),                     // 16: googlesql.ErrorMessageMode
	(googlesql_public.ParameterMode)(0),                        // 17: googlesql.ParameterMode
	(googlesql_public.StatementContext)(0),                     // 18: googlesql.StatementContext
	(googlesql_public.ResolvedASTRewrite)(0),                   // 19: googlesql.ResolvedASTRewrite
	(googlesql_public.ParseLocationRecordType)(0),              // 20: googlesql.ParseLocationRecordType
	(*googlesql_public.RewriteOptions)(nil),                    // 21: googlesql.RewriteOptions
}
var file_googlesql_proto_options_proto_depIdxs = []int32{
	3,  // 0: googlesql.GoogleSQLBuiltinFunctionOptionsProto.language_options:type_name -> googlesql.LanguageOptionsProto
	10, // 1: googlesql.GoogleSQLBuiltinFunctionOptionsProto.include_function_ids:type_name -> googlesql.FunctionSignatureId
	10, // 2: googlesql.GoogleSQLBuiltinFunctionOptionsProto.exclude_function_ids:type_name -> googlesql.FunctionSignatureId
	2,  // 3: googlesql.GoogleSQLBuiltinFunctionOptionsProto.enabled_rewrites_map_entry:type_name -> googlesql.EnabledRewriteProto
	10, // 4: googlesql.EnabledRewriteProto.key:type_name -> googlesql.FunctionSignatureId
	11, // 5: googlesql.LanguageOptionsProto.name_resolution_mode:type_name -> googlesql.NameResolutionMode
	12, // 6: googlesql.LanguageOptionsProto.product_mode:type_name -> googlesql.ProductMode
	13, // 7: googlesql.LanguageOptionsProto.enabled_language_features:type_name -> googlesql.LanguageFeature
	14, // 8: googlesql.LanguageOptionsProto.supported_statement_kinds:type_name -> googlesql.ResolvedNodeKind
	6,  // 9: googlesql.AllowedHintsAndOptionsProto.hint:type_name -> googlesql.AllowedHintsAndOptionsProto.HintProto
	7,  // 10: googlesql.AllowedHintsAndOptionsProto.option:type_name -> googlesql.AllowedHintsAndOptionsProto.OptionProto
	7,  // 11: googlesql.AllowedHintsAndOptionsProto.anonymization_option:type_name -> googlesql.AllowedHintsAndOptionsProto.OptionProto
	7,  // 12: googlesql.AllowedHintsAndOptionsProto.differential_privacy_option:type_name -> googlesql.AllowedHintsAndOptionsProto.OptionProto
	3,  // 13: googlesql.AnalyzerOptionsProto.language_options:type_name -> googlesql.LanguageOptionsProto
	8,  // 14: googlesql.AnalyzerOptionsProto.query_parameters:type_name -> googlesql.AnalyzerOptionsProto.QueryParameterProto
	15, // 15: googlesql.AnalyzerOptionsProto.positional_query_parameters:type_name -> googlesql.TypeProto
	8,  // 16: googlesql.AnalyzerOptionsProto.expression_columns:type_name -> googlesql.AnalyzerOptionsProto.QueryParameterProto
	8,  // 17: googlesql.AnalyzerOptionsProto.graph_properties:type_name -> googlesql.AnalyzerOptionsProto.QueryParameterProto
	8,  // 18: googlesql.AnalyzerOptionsProto.in_scope_expression_column:type_name -> googlesql.AnalyzerOptionsProto.QueryParameterProto
	8,  // 19: googlesql.AnalyzerOptionsProto.ddl_pseudo_columns:type_name -> googlesql.AnalyzerOptionsProto.QueryParameterProto
	16, // 20: googlesql.AnalyzerOptionsProto.error_message_mode:type_name -> googlesql.ErrorMessageMode
	17, // 21: googlesql.AnalyzerOptionsProto.parameter_mode:type_name -> googlesql.ParameterMode
	4,  // 22: googlesql.AnalyzerOptionsProto.allowed_hints_and_options:type_name -> googlesql.AllowedHintsAndOptionsProto
	18, // 23: googlesql.AnalyzerOptionsProto.statement_context:type_name -> googlesql.StatementContext
	9,  // 24: googlesql.AnalyzerOptionsProto.system_variables:type_name -> googlesql.AnalyzerOptionsProto.SystemVariableProto
	15, // 25: googlesql.AnalyzerOptionsProto.target_column_types:type_name -> googlesql.TypeProto
	19, // 26: googlesql.AnalyzerOptionsProto.enabled_rewrites:type_name -> googlesql.ResolvedASTRewrite
	20, // 27: googlesql.AnalyzerOptionsProto.parse_location_record_type:type_name -> googlesql.ParseLocationRecordType
	21, // 28: googlesql.AnalyzerOptionsProto.rewrite_options:type_name -> googlesql.RewriteOptions
	15, // 29: googlesql.AllowedHintsAndOptionsProto.HintProto.type:type_name -> googlesql.TypeProto
	15, // 30: googlesql.AllowedHintsAndOptionsProto.OptionProto.type:type_name -> googlesql.TypeProto
	0,  // 31: googlesql.AllowedHintsAndOptionsProto.OptionProto.resolving_kind:type_name -> googlesql.AllowedHintsAndOptionsProto.OptionProto.ResolvingKind
	15, // 32: googlesql.AnalyzerOptionsProto.QueryParameterProto.type:type_name -> googlesql.TypeProto
	15, // 33: googlesql.AnalyzerOptionsProto.SystemVariableProto.type:type_name -> googlesql.TypeProto
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_googlesql_proto_options_proto_init() }
func file_googlesql_proto_options_proto_init() {
	if File_googlesql_proto_options_proto != nil {
		return
	}
	file_googlesql_resolved_ast_resolved_node_kind_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_options_proto_rawDesc), len(file_googlesql_proto_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_options_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_options_proto_depIdxs,
		EnumInfos:         file_googlesql_proto_options_proto_enumTypes,
		MessageInfos:      file_googlesql_proto_options_proto_msgTypes,
	}.Build()
	File_googlesql_proto_options_proto = out.File
	file_googlesql_proto_options_proto_goTypes = nil
	file_googlesql_proto_options_proto_depIdxs = nil
}
