//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/placeholder_descriptor.proto

package googlesql_core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto bundles ((broken link)) may omit types that are
// referenced by other types that are included. When users do this, engines may
// include a placeholder type so that proto2 doesn't get upset. Engines could
// use the built-in proto2 placeholder feature, but it has heuristics that don't
// always work for guessing enum vs. message and exact names, and it can be
// handled better since engines have the real descriptors and can omit them.
// Engines don't need to do this for enum types, only message types, since for
// enum types engines would have to make up a fake enumeration value (since they
// must have at least one). For messages, engines can just make a message with
// no fields and this option, which engines may ignore.
type PlaceholderDescriptorProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPlaceholder *bool                  `protobuf:"varint,1,opt,name=is_placeholder,json=isPlaceholder" json:"is_placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderDescriptorProto) Reset() {
	*x = PlaceholderDescriptorProto{}
	mi := &file_googlesql_proto_placeholder_descriptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderDescriptorProto) ProtoMessage() {}

func (x *PlaceholderDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_placeholder_descriptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderDescriptorProto.ProtoReflect.Descriptor instead.
func (*PlaceholderDescriptorProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_placeholder_descriptor_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceholderDescriptorProto) GetIsPlaceholder() bool {
	if x != nil && x.IsPlaceholder != nil {
		return *x.IsPlaceholder
	}
	return false
}

var file_googlesql_proto_placeholder_descriptor_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*PlaceholderDescriptorProto)(nil),
		Field:         14004,
		Name:          "googlesql.PlaceholderDescriptorProto.placeholder_descriptor",
		Tag:           "bytes,14004,opt,name=placeholder_descriptor",
		Filename:      "googlesql/proto/placeholder_descriptor.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional googlesql.PlaceholderDescriptorProto placeholder_descriptor = 14004;
	E_PlaceholderDescriptorProto_PlaceholderDescriptor = &file_googlesql_proto_placeholder_descriptor_proto_extTypes[0]
)

var File_googlesql_proto_placeholder_descriptor_proto protoreflect.FileDescriptor

const file_googlesql_proto_placeholder_descriptor_proto_rawDesc = "" +
	"\n" +
	",googlesql/proto/placeholder_descriptor.proto\x12\tgooglesql\x1a google/protobuf/descriptor.proto\"\xc3\x01\n" +
	"\x1aPlaceholderDescriptorProto\x12%\n" +
	"\x0eis_placeholder\x18\x01 \x01(\bR\risPlaceholder2~\n" +
	"\x16placeholder_descriptor\x12\x1f.google.protobuf.MessageOptions\x18\xb4m \x01(\v2%.googlesql.PlaceholderDescriptorProtoR\x15placeholderDescriptorB3\n" +
	"\x14com.google.googlesqlB\x1bPlaceholderDescriptorProtos"

var (
	file_googlesql_proto_placeholder_descriptor_proto_rawDescOnce sync.Once
	file_googlesql_proto_placeholder_descriptor_proto_rawDescData []byte
)

func file_googlesql_proto_placeholder_descriptor_proto_rawDescGZIP() []byte {
	file_googlesql_proto_placeholder_descriptor_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_placeholder_descriptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_placeholder_descriptor_proto_rawDesc), len(file_googlesql_proto_placeholder_descriptor_proto_rawDesc)))
	})
	return file_googlesql_proto_placeholder_descriptor_proto_rawDescData
}

var file_googlesql_proto_placeholder_descriptor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_googlesql_proto_placeholder_descriptor_proto_goTypes = []any{
	(*PlaceholderDescriptorProto)(nil),  // 0: googlesql.PlaceholderDescriptorProto
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_googlesql_proto_placeholder_descriptor_proto_depIdxs = []int32{
	1, // 0: googlesql.PlaceholderDescriptorProto.placeholder_descriptor:extendee -> google.protobuf.MessageOptions
	0, // 1: googlesql.PlaceholderDescriptorProto.placeholder_descriptor:type_name -> googlesql.PlaceholderDescriptorProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_googlesql_proto_placeholder_descriptor_proto_init() }
func file_googlesql_proto_placeholder_descriptor_proto_init() {
	if File_googlesql_proto_placeholder_descriptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_placeholder_descriptor_proto_rawDesc), len(file_googlesql_proto_placeholder_descriptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_placeholder_descriptor_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_placeholder_descriptor_proto_depIdxs,
		MessageInfos:      file_googlesql_proto_placeholder_descriptor_proto_msgTypes,
		ExtensionInfos:    file_googlesql_proto_placeholder_descriptor_proto_extTypes,
	}.Build()
	File_googlesql_proto_placeholder_descriptor_proto = out.File
	file_googlesql_proto_placeholder_descriptor_proto_goTypes = nil
	file_googlesql_proto_placeholder_descriptor_proto_depIdxs = nil
}
