//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/script_exception.proto

package googlesql_core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload to attach to absl::Status to indicate that the error can be handled
// by an EXCEPTION clause.
//
// TODO: Add additional fields for engine-specific system variables
// that need to go out of scope when the exception handler is complete.
type ScriptException struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message to expose through the "@@error.message" system variable.
	// If not set, the absl::Status message will be used by default.
	Message         *string                   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Internal        *ScriptException_Internal `protobuf:"bytes,2,opt,name=internal" json:"internal,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScriptException) Reset() {
	*x = ScriptException{}
	mi := &file_googlesql_proto_script_exception_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptException) ProtoMessage() {}

func (x *ScriptException) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_script_exception_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptException.ProtoReflect.Descriptor instead.
func (*ScriptException) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_script_exception_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptException) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ScriptException) GetInternal() *ScriptException_Internal {
	if x != nil {
		return x.Internal
	}
	return nil
}

// A frame in the captured stack trace of an exception.
type ScriptException_StackTraceFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Line and column numbers are one-based and relative to the
	// start of the script/procedure body that contains them.
	Line   *int64 `protobuf:"varint,1,opt,name=line" json:"line,omitempty"`
	Column *int64 `protobuf:"varint,2,opt,name=column" json:"column,omitempty"`
	// Set only when an error is inside of a module; identifies the name
	// of the module which triggered the error.
	Filename *string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	// Set only when an error is inside of a procedure; identifies the name
	// of the procedure which triggered the error.
	Location      *string `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptException_StackTraceFrame) Reset() {
	*x = ScriptException_StackTraceFrame{}
	mi := &file_googlesql_proto_script_exception_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptException_StackTraceFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptException_StackTraceFrame) ProtoMessage() {}

func (x *ScriptException_StackTraceFrame) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_script_exception_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptException_StackTraceFrame.ProtoReflect.Descriptor instead.
func (*ScriptException_StackTraceFrame) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_script_exception_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScriptException_StackTraceFrame) GetLine() int64 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *ScriptException_StackTraceFrame) GetColumn() int64 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

func (x *ScriptException_StackTraceFrame) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *ScriptException_StackTraceFrame) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

// Fields for the script executor's internal use only.  Engines should not set
// this when raising exceptions.
type ScriptException_Internal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value to expose through the "@@error.statement_text" system variable.
	// This field is set automatically by the script executor, based on the
	// current statement at the time the exception is thrown.  Engines should
	// not set it.
	StatementText *string                            `protobuf:"bytes,1,opt,name=statement_text,json=statementText" json:"statement_text,omitempty"`
	StackTrace    []*ScriptException_StackTraceFrame `protobuf:"bytes,2,rep,name=stack_trace,json=stackTrace" json:"stack_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptException_Internal) Reset() {
	*x = ScriptException_Internal{}
	mi := &file_googlesql_proto_script_exception_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptException_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptException_Internal) ProtoMessage() {}

func (x *ScriptException_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_script_exception_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptException_Internal.ProtoReflect.Descriptor instead.
func (*ScriptException_Internal) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_script_exception_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ScriptException_Internal) GetStatementText() string {
	if x != nil && x.StatementText != nil {
		return *x.StatementText
	}
	return ""
}

func (x *ScriptException_Internal) GetStackTrace() []*ScriptException_StackTraceFrame {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

var File_googlesql_proto_script_exception_proto protoreflect.FileDescriptor

const file_googlesql_proto_script_exception_proto_rawDesc = "" +
	"\n" +
	"&googlesql/proto/script_exception.proto\x12\tgooglesql\"\xee\x02\n" +
	"\x0fScriptException\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12?\n" +
	"\binternal\x18\x02 \x01(\v2#.googlesql.ScriptException.InternalR\binternal\x1au\n" +
	"\x0fStackTraceFrame\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x03R\x04line\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x03R\x06column\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x1a~\n" +
	"\bInternal\x12%\n" +
	"\x0estatement_text\x18\x01 \x01(\tR\rstatementText\x12K\n" +
	"\vstack_trace\x18\x02 \x03(\v2*.googlesql.ScriptException.StackTraceFrameR\n" +
	"stackTrace*\t\b\x90N\x10\x80\x80\x80\x80\x02"

var (
	file_googlesql_proto_script_exception_proto_rawDescOnce sync.Once
	file_googlesql_proto_script_exception_proto_rawDescData []byte
)

func file_googlesql_proto_script_exception_proto_rawDescGZIP() []byte {
	file_googlesql_proto_script_exception_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_script_exception_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_script_exception_proto_rawDesc), len(file_googlesql_proto_script_exception_proto_rawDesc)))
	})
	return file_googlesql_proto_script_exception_proto_rawDescData
}

var file_googlesql_proto_script_exception_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_googlesql_proto_script_exception_proto_goTypes = []any{
	(*ScriptException)(nil),                 // 0: googlesql.ScriptException
	(*ScriptException_StackTraceFrame)(nil), // 1: googlesql.ScriptException.StackTraceFrame
	(*ScriptException_Internal)(nil),        // 2: googlesql.ScriptException.Internal
}
var file_googlesql_proto_script_exception_proto_depIdxs = []int32{
	2, // 0: googlesql.ScriptException.internal:type_name -> googlesql.ScriptException.Internal
	1, // 1: googlesql.ScriptException.Internal.stack_trace:type_name -> googlesql.ScriptException.StackTraceFrame
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_googlesql_proto_script_exception_proto_init() }
func file_googlesql_proto_script_exception_proto_init() {
	if File_googlesql_proto_script_exception_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_script_exception_proto_rawDesc), len(file_googlesql_proto_script_exception_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_script_exception_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_script_exception_proto_depIdxs,
		MessageInfos:      file_googlesql_proto_script_exception_proto_msgTypes,
	}.Build()
	File_googlesql_proto_script_exception_proto = out.File
	file_googlesql_proto_script_exception_proto_goTypes = nil
	file_googlesql_proto_script_exception_proto_depIdxs = nil
}
