//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Common types for serializing the ResolvedAST

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/resolved_ast/serialization.proto

package googlesql_core

import (
	googlesql_public "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto representation of googlesql::ResolvedColumn.
type ResolvedColumnProto struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	ColumnId      *int64                               `protobuf:"varint,1,opt,name=column_id,json=columnId" json:"column_id,omitempty"`
	TableName     *string                              `protobuf:"bytes,2,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Name          *string                              `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Type          *googlesql_public.TypeProto          `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	AnnotationMap *googlesql_public.AnnotationMapProto `protobuf:"bytes,5,opt,name=annotation_map,json=annotationMap" json:"annotation_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedColumnProto) Reset() {
	*x = ResolvedColumnProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedColumnProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedColumnProto) ProtoMessage() {}

func (x *ResolvedColumnProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedColumnProto.ProtoReflect.Descriptor instead.
func (*ResolvedColumnProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvedColumnProto) GetColumnId() int64 {
	if x != nil && x.ColumnId != nil {
		return *x.ColumnId
	}
	return 0
}

func (x *ResolvedColumnProto) GetTableName() string {
	if x != nil && x.TableName != nil {
		return *x.TableName
	}
	return ""
}

func (x *ResolvedColumnProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ResolvedColumnProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ResolvedColumnProto) GetAnnotationMap() *googlesql_public.AnnotationMapProto {
	if x != nil {
		return x.AnnotationMap
	}
	return nil
}

type ValueWithTypeProto struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          *googlesql_public.TypeProto  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Value         *googlesql_public.ValueProto `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueWithTypeProto) Reset() {
	*x = ValueWithTypeProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueWithTypeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueWithTypeProto) ProtoMessage() {}

func (x *ValueWithTypeProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueWithTypeProto.ProtoReflect.Descriptor instead.
func (*ValueWithTypeProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{1}
}

func (x *ValueWithTypeProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ValueWithTypeProto) GetValue() *googlesql_public.ValueProto {
	if x != nil {
		return x.Value
	}
	return nil
}

// Reference to a table.
type TableRefProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SerializationId *int64                 `protobuf:"varint,2,opt,name=serialization_id,json=serializationId" json:"serialization_id,omitempty"`
	FullName        *string                `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableRefProto) Reset() {
	*x = TableRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRefProto) ProtoMessage() {}

func (x *TableRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRefProto.ProtoReflect.Descriptor instead.
func (*TableRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{2}
}

func (x *TableRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TableRefProto) GetSerializationId() int64 {
	if x != nil && x.SerializationId != nil {
		return *x.SerializationId
	}
	return 0
}

func (x *TableRefProto) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

// Reference to a model.
type ModelRefProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SerializationId *int64                 `protobuf:"varint,2,opt,name=serialization_id,json=serializationId" json:"serialization_id,omitempty"`
	FullName        *string                `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelRefProto) Reset() {
	*x = ModelRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRefProto) ProtoMessage() {}

func (x *ModelRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRefProto.ProtoReflect.Descriptor instead.
func (*ModelRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{3}
}

func (x *ModelRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ModelRefProto) GetSerializationId() int64 {
	if x != nil && x.SerializationId != nil {
		return *x.SerializationId
	}
	return 0
}

func (x *ModelRefProto) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

// Reference to a connection
type ConnectionRefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName      *string                `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRefProto) Reset() {
	*x = ConnectionRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRefProto) ProtoMessage() {}

func (x *ConnectionRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRefProto.ProtoReflect.Descriptor instead.
func (*ConnectionRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ConnectionRefProto) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

// Reference to a sequence.
type SequenceRefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName      *string                `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceRefProto) Reset() {
	*x = SequenceRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceRefProto) ProtoMessage() {}

func (x *SequenceRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceRefProto.ProtoReflect.Descriptor instead.
func (*SequenceRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{5}
}

func (x *SequenceRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SequenceRefProto) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

// Reference to a named constant.
type ConstantRefProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full name of the function, e.g., catalog1.catalog2.Constant.
	Name          *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstantRefProto) Reset() {
	*x = ConstantRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstantRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantRefProto) ProtoMessage() {}

func (x *ConstantRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantRefProto.ProtoReflect.Descriptor instead.
func (*ConstantRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{6}
}

func (x *ConstantRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Reference to a function.
type FunctionRefProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO: Optimize this by generating unique serialization IDs.
	// Full name of the function, e.g., group:pathname.
	Name          *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionRefProto) Reset() {
	*x = FunctionRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRefProto) ProtoMessage() {}

func (x *FunctionRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRefProto.ProtoReflect.Descriptor instead.
func (*FunctionRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Reference to a table-valued function.
type TableValuedFunctionRefProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full name of the function, e.g., group:pathname.
	Name          *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableValuedFunctionRefProto) Reset() {
	*x = TableValuedFunctionRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableValuedFunctionRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableValuedFunctionRefProto) ProtoMessage() {}

func (x *TableValuedFunctionRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableValuedFunctionRefProto.ProtoReflect.Descriptor instead.
func (*TableValuedFunctionRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{8}
}

func (x *TableValuedFunctionRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ResolvedNodeProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parse location range if present in the ResolvedNode.
	ParseLocationRange *googlesql_public.ParseLocationRangeProto `protobuf:"bytes,1,opt,name=parse_location_range,json=parseLocationRange" json:"parse_location_range,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResolvedNodeProto) Reset() {
	*x = ResolvedNodeProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedNodeProto) ProtoMessage() {}

func (x *ResolvedNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedNodeProto.ProtoReflect.Descriptor instead.
func (*ResolvedNodeProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvedNodeProto) GetParseLocationRange() *googlesql_public.ParseLocationRangeProto {
	if x != nil {
		return x.ParseLocationRange
	}
	return nil
}

// Reference to a proto field descriptor.
type FieldDescriptorRefProto struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ContainingProto *googlesql_public.ProtoTypeProto `protobuf:"bytes,1,opt,name=containing_proto,json=containingProto" json:"containing_proto,omitempty"`
	Number          *int32                           `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldDescriptorRefProto) Reset() {
	*x = FieldDescriptorRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescriptorRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescriptorRefProto) ProtoMessage() {}

func (x *FieldDescriptorRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescriptorRefProto.ProtoReflect.Descriptor instead.
func (*FieldDescriptorRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{10}
}

func (x *FieldDescriptorRefProto) GetContainingProto() *googlesql_public.ProtoTypeProto {
	if x != nil {
		return x.ContainingProto
	}
	return nil
}

func (x *FieldDescriptorRefProto) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

// Reference to a proto2::OneofDescriptor, which describes the fields of an
// Oneof.
type OneofDescriptorRefProto struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ContainingProto *googlesql_public.ProtoTypeProto `protobuf:"bytes,1,opt,name=containing_proto,json=containingProto" json:"containing_proto,omitempty"`
	// 0-based offset which aligns with the order Oneof fields are defined in the
	// containing message.
	Index         *int32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofDescriptorRefProto) Reset() {
	*x = OneofDescriptorRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofDescriptorRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofDescriptorRefProto) ProtoMessage() {}

func (x *OneofDescriptorRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofDescriptorRefProto.ProtoReflect.Descriptor instead.
func (*OneofDescriptorRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{11}
}

func (x *OneofDescriptorRefProto) GetContainingProto() *googlesql_public.ProtoTypeProto {
	if x != nil {
		return x.ContainingProto
	}
	return nil
}

func (x *OneofDescriptorRefProto) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type ProcedureRefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureRefProto) Reset() {
	*x = ProcedureRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureRefProto) ProtoMessage() {}

func (x *ProcedureRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureRefProto.ProtoReflect.Descriptor instead.
func (*ProcedureRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{12}
}

func (x *ProcedureRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Proto representation of googlesql::ResolvedCollation.
type ResolvedCollationProto struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CollationName *string                   `protobuf:"bytes,1,opt,name=collation_name,json=collationName" json:"collation_name,omitempty"`
	ChildList     []*ResolvedCollationProto `protobuf:"bytes,2,rep,name=child_list,json=childList" json:"child_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedCollationProto) Reset() {
	*x = ResolvedCollationProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedCollationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedCollationProto) ProtoMessage() {}

func (x *ResolvedCollationProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedCollationProto.ProtoReflect.Descriptor instead.
func (*ResolvedCollationProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{13}
}

func (x *ResolvedCollationProto) GetCollationName() string {
	if x != nil && x.CollationName != nil {
		return *x.CollationName
	}
	return ""
}

func (x *ResolvedCollationProto) GetChildList() []*ResolvedCollationProto {
	if x != nil {
		return x.ChildList
	}
	return nil
}

type ColumnRefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRef      *TableRefProto         `protobuf:"bytes,1,opt,name=table_ref,json=tableRef" json:"table_ref,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnRefProto) Reset() {
	*x = ColumnRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnRefProto) ProtoMessage() {}

func (x *ColumnRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnRefProto.ProtoReflect.Descriptor instead.
func (*ColumnRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{14}
}

func (x *ColumnRefProto) GetTableRef() *TableRefProto {
	if x != nil {
		return x.TableRef
	}
	return nil
}

func (x *ColumnRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Reference to a PropertyGraph.
type PropertyGraphRefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      *string                `protobuf:"bytes,1,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyGraphRefProto) Reset() {
	*x = PropertyGraphRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyGraphRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyGraphRefProto) ProtoMessage() {}

func (x *PropertyGraphRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyGraphRefProto.ProtoReflect.Descriptor instead.
func (*PropertyGraphRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{15}
}

func (x *PropertyGraphRefProto) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

type GraphPropertyDeclarationRefProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The property graph this graph property declaration belongs to.
	PropertyGraph *PropertyGraphRefProto `protobuf:"bytes,1,opt,name=property_graph,json=propertyGraph" json:"property_graph,omitempty"`
	// Name of the graph property, without prefixes.
	Name          *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPropertyDeclarationRefProto) Reset() {
	*x = GraphPropertyDeclarationRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPropertyDeclarationRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPropertyDeclarationRefProto) ProtoMessage() {}

func (x *GraphPropertyDeclarationRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPropertyDeclarationRefProto.ProtoReflect.Descriptor instead.
func (*GraphPropertyDeclarationRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{16}
}

func (x *GraphPropertyDeclarationRefProto) GetPropertyGraph() *PropertyGraphRefProto {
	if x != nil {
		return x.PropertyGraph
	}
	return nil
}

func (x *GraphPropertyDeclarationRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GraphElementLabelRefProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The property graph this graph element label belongs to.
	PropertyGraph *PropertyGraphRefProto `protobuf:"bytes,1,opt,name=property_graph,json=propertyGraph" json:"property_graph,omitempty"`
	// Name of the graph element label, without prefixes.
	Name          *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphElementLabelRefProto) Reset() {
	*x = GraphElementLabelRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphElementLabelRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphElementLabelRefProto) ProtoMessage() {}

func (x *GraphElementLabelRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphElementLabelRefProto.ProtoReflect.Descriptor instead.
func (*GraphElementLabelRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{17}
}

func (x *GraphElementLabelRefProto) GetPropertyGraph() *PropertyGraphRefProto {
	if x != nil {
		return x.PropertyGraph
	}
	return nil
}

func (x *GraphElementLabelRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GraphElementTableRefProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The property graph this graph element table belongs to.
	PropertyGraph *PropertyGraphRefProto `protobuf:"bytes,1,opt,name=property_graph,json=propertyGraph" json:"property_graph,omitempty"`
	// Name of the graph element table, without prefixes.
	Name          *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphElementTableRefProto) Reset() {
	*x = GraphElementTableRefProto{}
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphElementTableRefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphElementTableRefProto) ProtoMessage() {}

func (x *GraphElementTableRefProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_resolved_ast_serialization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphElementTableRefProto.ProtoReflect.Descriptor instead.
func (*GraphElementTableRefProto) Descriptor() ([]byte, []int) {
	return file_googlesql_resolved_ast_serialization_proto_rawDescGZIP(), []int{18}
}

func (x *GraphElementTableRefProto) GetPropertyGraph() *PropertyGraphRefProto {
	if x != nil {
		return x.PropertyGraph
	}
	return nil
}

func (x *GraphElementTableRefProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_googlesql_resolved_ast_serialization_proto protoreflect.FileDescriptor

const file_googlesql_resolved_ast_serialization_proto_rawDesc = "" +
	"\n" +
	"*googlesql/resolved_ast/serialization.proto\x12\tgooglesql\x1a!googlesql/public/annotation.proto\x1a+googlesql/public/parse_location_range.proto\x1a\x1bgooglesql/public/type.proto\x1a\x1cgooglesql/public/value.proto\"\xd5\x01\n" +
	"\x13ResolvedColumnProto\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\x03R\bcolumnId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x04 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x12D\n" +
	"\x0eannotation_map\x18\x05 \x01(\v2\x1d.googlesql.AnnotationMapProtoR\rannotationMap\"k\n" +
	"\x12ValueWithTypeProto\x12(\n" +
	"\x04type\x18\x01 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.googlesql.ValueProtoR\x05value\"k\n" +
	"\rTableRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10serialization_id\x18\x02 \x01(\x03R\x0fserializationId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"k\n" +
	"\rModelRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10serialization_id\x18\x02 \x01(\x03R\x0fserializationId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"E\n" +
	"\x12ConnectionRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"C\n" +
	"\x10SequenceRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\"&\n" +
	"\x10ConstantRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x10FunctionRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x1bTableValuedFunctionRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"i\n" +
	"\x11ResolvedNodeProto\x12T\n" +
	"\x14parse_location_range\x18\x01 \x01(\v2\".googlesql.ParseLocationRangeProtoR\x12parseLocationRange\"w\n" +
	"\x17FieldDescriptorRefProto\x12D\n" +
	"\x10containing_proto\x18\x01 \x01(\v2\x19.googlesql.ProtoTypeProtoR\x0fcontainingProto\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\"u\n" +
	"\x17OneofDescriptorRefProto\x12D\n" +
	"\x10containing_proto\x18\x01 \x01(\v2\x19.googlesql.ProtoTypeProtoR\x0fcontainingProto\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\"'\n" +
	"\x11ProcedureRefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x81\x01\n" +
	"\x16ResolvedCollationProto\x12%\n" +
	"\x0ecollation_name\x18\x01 \x01(\tR\rcollationName\x12@\n" +
	"\n" +
	"child_list\x18\x02 \x03(\v2!.googlesql.ResolvedCollationProtoR\tchildList\"[\n" +
	"\x0eColumnRefProto\x125\n" +
	"\ttable_ref\x18\x01 \x01(\v2\x18.googlesql.TableRefProtoR\btableRef\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x15PropertyGraphRefProto\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\"\x7f\n" +
	" GraphPropertyDeclarationRefProto\x12G\n" +
	"\x0eproperty_graph\x18\x01 \x01(\v2 .googlesql.PropertyGraphRefProtoR\rpropertyGraph\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"x\n" +
	"\x19GraphElementLabelRefProto\x12G\n" +
	"\x0eproperty_graph\x18\x01 \x01(\v2 .googlesql.PropertyGraphRefProtoR\rpropertyGraph\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"x\n" +
	"\x19GraphElementTableRefProto\x12G\n" +
	"\x0eproperty_graph\x18\x01 \x01(\v2 .googlesql.PropertyGraphRefProtoR\rpropertyGraph\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB0\n" +
	"\x14com.google.googlesqlB\x16GoogleSQLSerializationP\x01"

var (
	file_googlesql_resolved_ast_serialization_proto_rawDescOnce sync.Once
	file_googlesql_resolved_ast_serialization_proto_rawDescData []byte
)

func file_googlesql_resolved_ast_serialization_proto_rawDescGZIP() []byte {
	file_googlesql_resolved_ast_serialization_proto_rawDescOnce.Do(func() {
		file_googlesql_resolved_ast_serialization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_resolved_ast_serialization_proto_rawDesc), len(file_googlesql_resolved_ast_serialization_proto_rawDesc)))
	})
	return file_googlesql_resolved_ast_serialization_proto_rawDescData
}

var file_googlesql_resolved_ast_serialization_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_googlesql_resolved_ast_serialization_proto_goTypes = []any{
	(*ResolvedColumnProto)(nil),                      // 0: googlesql.ResolvedColumnProto
	(*ValueWithTypeProto)(nil),                       // 1: googlesql.ValueWithTypeProto
	(*TableRefProto)(nil),                            // 2: googlesql.TableRefProto
	(*ModelRefProto)(nil),                            // 3: googlesql.ModelRefProto
	(*ConnectionRefProto)(nil),                       // 4: googlesql.ConnectionRefProto
	(*SequenceRefProto)(nil),                         // 5: googlesql.SequenceRefProto
	(*ConstantRefProto)(nil),                         // 6: googlesql.ConstantRefProto
	(*FunctionRefProto)(nil),                         // 7: googlesql.FunctionRefProto
	(*TableValuedFunctionRefProto)(nil),              // 8: googlesql.TableValuedFunctionRefProto
	(*ResolvedNodeProto)(nil),                        // 9: googlesql.ResolvedNodeProto
	(*FieldDescriptorRefProto)(nil),                  // 10: googlesql.FieldDescriptorRefProto
	(*OneofDescriptorRefProto)(nil),                  // 11: googlesql.OneofDescriptorRefProto
	(*ProcedureRefProto)(nil),                        // 12: googlesql.ProcedureRefProto
	(*ResolvedCollationProto)(nil),                   // 13: googlesql.ResolvedCollationProto
	(*ColumnRefProto)(nil),                           // 14: googlesql.ColumnRefProto
	(*PropertyGraphRefProto)(nil),                    // 15: googlesql.PropertyGraphRefProto
	(*GraphPropertyDeclarationRefProto)(nil),         // 16: googlesql.GraphPropertyDeclarationRefProto
	(*GraphElementLabelRefProto)(nil),                // 17: googlesql.GraphElementLabelRefProto
	(*GraphElementTableRefProto)(nil),                // 18: googlesql.GraphElementTableRefProto
	(*googlesql_public.TypeProto)(nil),               // 19: googlesql.TypeProto
	(*googlesql_public.AnnotationMapProto)(nil),      // 20: googlesql.AnnotationMapProto
	(*googlesql_public.ValueProto)(nil),              // 21: googlesql.ValueProto
	(*googlesql_public.ParseLocationRangeProto)(nil), // 22: googlesql.ParseLocationRangeProto
	(*googlesql_public.ProtoTypeProto)(nil),          // 23: googlesql.ProtoTypeProto
}
var file_googlesql_resolved_ast_serialization_proto_depIdxs = []int32{
	19, // 0: googlesql.ResolvedColumnProto.type:type_name -> googlesql.TypeProto
	20, // 1: googlesql.ResolvedColumnProto.annotation_map:type_name -> googlesql.AnnotationMapProto
	19, // 2: googlesql.ValueWithTypeProto.type:type_name -> googlesql.TypeProto
	21, // 3: googlesql.ValueWithTypeProto.value:type_name -> googlesql.ValueProto
	22, // 4: googlesql.ResolvedNodeProto.parse_location_range:type_name -> googlesql.ParseLocationRangeProto
	23, // 5: googlesql.FieldDescriptorRefProto.containing_proto:type_name -> googlesql.ProtoTypeProto
	23, // 6: googlesql.OneofDescriptorRefProto.containing_proto:type_name -> googlesql.ProtoTypeProto
	13, // 7: googlesql.ResolvedCollationProto.child_list:type_name -> googlesql.ResolvedCollationProto
	2,  // 8: googlesql.ColumnRefProto.table_ref:type_name -> googlesql.TableRefProto
	15, // 9: googlesql.GraphPropertyDeclarationRefProto.property_graph:type_name -> googlesql.PropertyGraphRefProto
	15, // 10: googlesql.GraphElementLabelRefProto.property_graph:type_name -> googlesql.PropertyGraphRefProto
	15, // 11: googlesql.GraphElementTableRefProto.property_graph:type_name -> googlesql.PropertyGraphRefProto
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_googlesql_resolved_ast_serialization_proto_init() }
func file_googlesql_resolved_ast_serialization_proto_init() {
	if File_googlesql_resolved_ast_serialization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_resolved_ast_serialization_proto_rawDesc), len(file_googlesql_resolved_ast_serialization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_resolved_ast_serialization_proto_goTypes,
		DependencyIndexes: file_googlesql_resolved_ast_serialization_proto_depIdxs,
		MessageInfos:      file_googlesql_resolved_ast_serialization_proto_msgTypes,
	}.Build()
	File_googlesql_resolved_ast_serialization_proto = out.File
	file_googlesql_resolved_ast_serialization_proto_goTypes = nil
	file_googlesql_resolved_ast_serialization_proto_depIdxs = nil
}
