//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/simple_catalog.proto

package googlesql_core

import (
	googlesql_public "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleCatalogProto struct {
	state     protoimpl.MessageState               `protogen:"open.v1"`
	Name      *string                              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Table     []*googlesql_public.SimpleTableProto `protobuf:"bytes,2,rep,name=table" json:"table,omitempty"`
	NamedType []*SimpleCatalogProto_NamedTypeProto `protobuf:"bytes,3,rep,name=named_type,json=namedType" json:"named_type,omitempty"`
	Catalog   []*SimpleCatalogProto                `protobuf:"bytes,4,rep,name=catalog" json:"catalog,omitempty"`
	// Specify built-in functions to load.
	BuiltinFunctionOptions *GoogleSQLBuiltinFunctionOptionsProto `protobuf:"bytes,5,opt,name=builtin_function_options,json=builtinFunctionOptions" json:"builtin_function_options,omitempty"`
	CustomFunction         []*FunctionProto                      `protobuf:"bytes,6,rep,name=custom_function,json=customFunction" json:"custom_function,omitempty"`
	CustomTvf              []*TableValuedFunctionProto           `protobuf:"bytes,9,rep,name=custom_tvf,json=customTvf" json:"custom_tvf,omitempty"`
	// The index of the FileDescriptorSet in the top-level request proto.
	// If set, SimpleCatalog::SetDescriptorPool will be called with the
	// DescriptorPool deserialized from the referred FileDescriptorSet.
	FileDescriptorSetIndex *int32                                    `protobuf:"varint,7,opt,name=file_descriptor_set_index,json=fileDescriptorSetIndex,def=-1" json:"file_descriptor_set_index,omitempty"`
	Procedure              []*ProcedureProto                         `protobuf:"bytes,8,rep,name=procedure" json:"procedure,omitempty"`
	Constant               []*googlesql_public.SimpleConstantProto   `protobuf:"bytes,10,rep,name=constant" json:"constant,omitempty"`
	PropertyGraph          []*SimplePropertyGraphProto               `protobuf:"bytes,11,rep,name=property_graph,json=propertyGraph" json:"property_graph,omitempty"`
	Connection             []*googlesql_public.SimpleConnectionProto `protobuf:"bytes,12,rep,name=connection" json:"connection,omitempty"`
	Model                  []*googlesql_public.SimpleModelProto      `protobuf:"bytes,13,rep,name=model" json:"model,omitempty"`
	Sequence               []*googlesql_public.SimpleSequenceProto   `protobuf:"bytes,14,rep,name=sequence" json:"sequence,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for SimpleCatalogProto fields.
const (
	Default_SimpleCatalogProto_FileDescriptorSetIndex = int32(-1)
)

func (x *SimpleCatalogProto) Reset() {
	*x = SimpleCatalogProto{}
	mi := &file_googlesql_proto_simple_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleCatalogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleCatalogProto) ProtoMessage() {}

func (x *SimpleCatalogProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleCatalogProto.ProtoReflect.Descriptor instead.
func (*SimpleCatalogProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleCatalogProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimpleCatalogProto) GetTable() []*googlesql_public.SimpleTableProto {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *SimpleCatalogProto) GetNamedType() []*SimpleCatalogProto_NamedTypeProto {
	if x != nil {
		return x.NamedType
	}
	return nil
}

func (x *SimpleCatalogProto) GetCatalog() []*SimpleCatalogProto {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *SimpleCatalogProto) GetBuiltinFunctionOptions() *GoogleSQLBuiltinFunctionOptionsProto {
	if x != nil {
		return x.BuiltinFunctionOptions
	}
	return nil
}

func (x *SimpleCatalogProto) GetCustomFunction() []*FunctionProto {
	if x != nil {
		return x.CustomFunction
	}
	return nil
}

func (x *SimpleCatalogProto) GetCustomTvf() []*TableValuedFunctionProto {
	if x != nil {
		return x.CustomTvf
	}
	return nil
}

func (x *SimpleCatalogProto) GetFileDescriptorSetIndex() int32 {
	if x != nil && x.FileDescriptorSetIndex != nil {
		return *x.FileDescriptorSetIndex
	}
	return Default_SimpleCatalogProto_FileDescriptorSetIndex
}

func (x *SimpleCatalogProto) GetProcedure() []*ProcedureProto {
	if x != nil {
		return x.Procedure
	}
	return nil
}

func (x *SimpleCatalogProto) GetConstant() []*googlesql_public.SimpleConstantProto {
	if x != nil {
		return x.Constant
	}
	return nil
}

func (x *SimpleCatalogProto) GetPropertyGraph() []*SimplePropertyGraphProto {
	if x != nil {
		return x.PropertyGraph
	}
	return nil
}

func (x *SimpleCatalogProto) GetConnection() []*googlesql_public.SimpleConnectionProto {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *SimpleCatalogProto) GetModel() []*googlesql_public.SimpleModelProto {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *SimpleCatalogProto) GetSequence() []*googlesql_public.SimpleSequenceProto {
	if x != nil {
		return x.Sequence
	}
	return nil
}

type SimpleCatalogProto_NamedTypeProto struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          *string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type          *googlesql_public.TypeProto `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleCatalogProto_NamedTypeProto) Reset() {
	*x = SimpleCatalogProto_NamedTypeProto{}
	mi := &file_googlesql_proto_simple_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleCatalogProto_NamedTypeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleCatalogProto_NamedTypeProto) ProtoMessage() {}

func (x *SimpleCatalogProto_NamedTypeProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleCatalogProto_NamedTypeProto.ProtoReflect.Descriptor instead.
func (*SimpleCatalogProto_NamedTypeProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_catalog_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SimpleCatalogProto_NamedTypeProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimpleCatalogProto_NamedTypeProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_googlesql_proto_simple_catalog_proto protoreflect.FileDescriptor

const file_googlesql_proto_simple_catalog_proto_rawDesc = "" +
	"\n" +
	"$googlesql/proto/simple_catalog.proto\x12\tgooglesql\x1a\x1egooglesql/proto/function.proto\x1a\x1dgooglesql/proto/options.proto\x1a+googlesql/proto/simple_property_graph.proto\x1a(googlesql/public/simple_connection.proto\x1a&googlesql/public/simple_constant.proto\x1a#googlesql/public/simple_model.proto\x1a&googlesql/public/simple_sequence.proto\x1a#googlesql/public/simple_table.proto\x1a\x1bgooglesql/public/type.proto\"\xd4\a\n" +
	"\x12SimpleCatalogProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x05table\x18\x02 \x03(\v2\x1b.googlesql.SimpleTableProtoR\x05table\x12K\n" +
	"\n" +
	"named_type\x18\x03 \x03(\v2,.googlesql.SimpleCatalogProto.NamedTypeProtoR\tnamedType\x127\n" +
	"\acatalog\x18\x04 \x03(\v2\x1d.googlesql.SimpleCatalogProtoR\acatalog\x12i\n" +
	"\x18builtin_function_options\x18\x05 \x01(\v2/.googlesql.GoogleSQLBuiltinFunctionOptionsProtoR\x16builtinFunctionOptions\x12A\n" +
	"\x0fcustom_function\x18\x06 \x03(\v2\x18.googlesql.FunctionProtoR\x0ecustomFunction\x12B\n" +
	"\n" +
	"custom_tvf\x18\t \x03(\v2#.googlesql.TableValuedFunctionProtoR\tcustomTvf\x12=\n" +
	"\x19file_descriptor_set_index\x18\a \x01(\x05:\x02-1R\x16fileDescriptorSetIndex\x127\n" +
	"\tprocedure\x18\b \x03(\v2\x19.googlesql.ProcedureProtoR\tprocedure\x12:\n" +
	"\bconstant\x18\n" +
	" \x03(\v2\x1e.googlesql.SimpleConstantProtoR\bconstant\x12J\n" +
	"\x0eproperty_graph\x18\v \x03(\v2#.googlesql.SimplePropertyGraphProtoR\rpropertyGraph\x12@\n" +
	"\n" +
	"connection\x18\f \x03(\v2 .googlesql.SimpleConnectionProtoR\n" +
	"connection\x121\n" +
	"\x05model\x18\r \x03(\v2\x1b.googlesql.SimpleModelProtoR\x05model\x12:\n" +
	"\bsequence\x18\x0e \x03(\v2\x1e.googlesql.SimpleSequenceProtoR\bsequence\x1aN\n" +
	"\x0eNamedTypeProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.googlesql.TypeProtoR\x04typeB+\n" +
	"\x14com.google.googlesqlB\x13SimpleCatalogProtos"

var (
	file_googlesql_proto_simple_catalog_proto_rawDescOnce sync.Once
	file_googlesql_proto_simple_catalog_proto_rawDescData []byte
)

func file_googlesql_proto_simple_catalog_proto_rawDescGZIP() []byte {
	file_googlesql_proto_simple_catalog_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_simple_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_simple_catalog_proto_rawDesc), len(file_googlesql_proto_simple_catalog_proto_rawDesc)))
	})
	return file_googlesql_proto_simple_catalog_proto_rawDescData
}

var file_googlesql_proto_simple_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_googlesql_proto_simple_catalog_proto_goTypes = []any{
	(*SimpleCatalogProto)(nil),                     // 0: googlesql.SimpleCatalogProto
	(*SimpleCatalogProto_NamedTypeProto)(nil),      // 1: googlesql.SimpleCatalogProto.NamedTypeProto
	(*googlesql_public.SimpleTableProto)(nil),      // 2: googlesql.SimpleTableProto
	(*GoogleSQLBuiltinFunctionOptionsProto)(nil),   // 3: googlesql.GoogleSQLBuiltinFunctionOptionsProto
	(*FunctionProto)(nil),                          // 4: googlesql.FunctionProto
	(*TableValuedFunctionProto)(nil),               // 5: googlesql.TableValuedFunctionProto
	(*ProcedureProto)(nil),                         // 6: googlesql.ProcedureProto
	(*googlesql_public.SimpleConstantProto)(nil),   // 7: googlesql.SimpleConstantProto
	(*SimplePropertyGraphProto)(nil),               // 8: googlesql.SimplePropertyGraphProto
	(*googlesql_public.SimpleConnectionProto)(nil), // 9: googlesql.SimpleConnectionProto
	(*googlesql_public.SimpleModelProto)(nil),      // 10: googlesql.SimpleModelProto
	(*googlesql_public.SimpleSequenceProto)(nil),   // 11: googlesql.SimpleSequenceProto
	(*googlesql_public.TypeProto)(nil),             // 12: googlesql.TypeProto
}
var file_googlesql_proto_simple_catalog_proto_depIdxs = []int32{
	2,  // 0: googlesql.SimpleCatalogProto.table:type_name -> googlesql.SimpleTableProto
	1,  // 1: googlesql.SimpleCatalogProto.named_type:type_name -> googlesql.SimpleCatalogProto.NamedTypeProto
	0,  // 2: googlesql.SimpleCatalogProto.catalog:type_name -> googlesql.SimpleCatalogProto
	3,  // 3: googlesql.SimpleCatalogProto.builtin_function_options:type_name -> googlesql.GoogleSQLBuiltinFunctionOptionsProto
	4,  // 4: googlesql.SimpleCatalogProto.custom_function:type_name -> googlesql.FunctionProto
	5,  // 5: googlesql.SimpleCatalogProto.custom_tvf:type_name -> googlesql.TableValuedFunctionProto
	6,  // 6: googlesql.SimpleCatalogProto.procedure:type_name -> googlesql.ProcedureProto
	7,  // 7: googlesql.SimpleCatalogProto.constant:type_name -> googlesql.SimpleConstantProto
	8,  // 8: googlesql.SimpleCatalogProto.property_graph:type_name -> googlesql.SimplePropertyGraphProto
	9,  // 9: googlesql.SimpleCatalogProto.connection:type_name -> googlesql.SimpleConnectionProto
	10, // 10: googlesql.SimpleCatalogProto.model:type_name -> googlesql.SimpleModelProto
	11, // 11: googlesql.SimpleCatalogProto.sequence:type_name -> googlesql.SimpleSequenceProto
	12, // 12: googlesql.SimpleCatalogProto.NamedTypeProto.type:type_name -> googlesql.TypeProto
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_googlesql_proto_simple_catalog_proto_init() }
func file_googlesql_proto_simple_catalog_proto_init() {
	if File_googlesql_proto_simple_catalog_proto != nil {
		return
	}
	file_googlesql_proto_function_proto_init()
	file_googlesql_proto_options_proto_init()
	file_googlesql_proto_simple_property_graph_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_simple_catalog_proto_rawDesc), len(file_googlesql_proto_simple_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_simple_catalog_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_simple_catalog_proto_depIdxs,
		MessageInfos:      file_googlesql_proto_simple_catalog_proto_msgTypes,
	}.Build()
	File_googlesql_proto_simple_catalog_proto = out.File
	file_googlesql_proto_simple_catalog_proto_goTypes = nil
	file_googlesql_proto_simple_catalog_proto_depIdxs = nil
}
