//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/proto/simple_property_graph.proto

package googlesql_core

import (
	googlesql_public "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleGraphElementTableProto_Kind int32

const (
	SimpleGraphElementTableProto_KIND_UNSPECIFIED SimpleGraphElementTableProto_Kind = 0
	SimpleGraphElementTableProto_NODE             SimpleGraphElementTableProto_Kind = 1
	SimpleGraphElementTableProto_EDGE             SimpleGraphElementTableProto_Kind = 2
)

// Enum value maps for SimpleGraphElementTableProto_Kind.
var (
	SimpleGraphElementTableProto_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "NODE",
		2: "EDGE",
	}
	SimpleGraphElementTableProto_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"NODE":             1,
		"EDGE":             2,
	}
)

func (x SimpleGraphElementTableProto_Kind) Enum() *SimpleGraphElementTableProto_Kind {
	p := new(SimpleGraphElementTableProto_Kind)
	*p = x
	return p
}

func (x SimpleGraphElementTableProto_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimpleGraphElementTableProto_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_proto_simple_property_graph_proto_enumTypes[0].Descriptor()
}

func (SimpleGraphElementTableProto_Kind) Type() protoreflect.EnumType {
	return &file_googlesql_proto_simple_property_graph_proto_enumTypes[0]
}

func (x SimpleGraphElementTableProto_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SimpleGraphElementTableProto_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SimpleGraphElementTableProto_Kind(num)
	return nil
}

// Deprecated: Use SimpleGraphElementTableProto_Kind.Descriptor instead.
func (SimpleGraphElementTableProto_Kind) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{1, 0}
}

type SimpleGraphPropertyDeclarationProto_Kind int32

const (
	SimpleGraphPropertyDeclarationProto_KIND_UNSPECIFIED SimpleGraphPropertyDeclarationProto_Kind = 0
	SimpleGraphPropertyDeclarationProto_SCALAR           SimpleGraphPropertyDeclarationProto_Kind = 1
	SimpleGraphPropertyDeclarationProto_MEASURE          SimpleGraphPropertyDeclarationProto_Kind = 2
)

// Enum value maps for SimpleGraphPropertyDeclarationProto_Kind.
var (
	SimpleGraphPropertyDeclarationProto_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "SCALAR",
		2: "MEASURE",
	}
	SimpleGraphPropertyDeclarationProto_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"SCALAR":           1,
		"MEASURE":          2,
	}
)

func (x SimpleGraphPropertyDeclarationProto_Kind) Enum() *SimpleGraphPropertyDeclarationProto_Kind {
	p := new(SimpleGraphPropertyDeclarationProto_Kind)
	*p = x
	return p
}

func (x SimpleGraphPropertyDeclarationProto_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimpleGraphPropertyDeclarationProto_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_googlesql_proto_simple_property_graph_proto_enumTypes[1].Descriptor()
}

func (SimpleGraphPropertyDeclarationProto_Kind) Type() protoreflect.EnumType {
	return &file_googlesql_proto_simple_property_graph_proto_enumTypes[1]
}

func (x SimpleGraphPropertyDeclarationProto_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SimpleGraphPropertyDeclarationProto_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SimpleGraphPropertyDeclarationProto_Kind(num)
	return nil
}

// Deprecated: Use SimpleGraphPropertyDeclarationProto_Kind.Descriptor instead.
func (SimpleGraphPropertyDeclarationProto_Kind) EnumDescriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{4, 0}
}

type SimplePropertyGraphProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEPRECATED: use name_path instead.
	Name                 *string                                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NamePath             []string                               `protobuf:"bytes,2,rep,name=name_path,json=namePath" json:"name_path,omitempty"`
	NodeTables           []*SimpleGraphElementTableProto        `protobuf:"bytes,3,rep,name=node_tables,json=nodeTables" json:"node_tables,omitempty"`
	EdgeTables           []*SimpleGraphElementTableProto        `protobuf:"bytes,4,rep,name=edge_tables,json=edgeTables" json:"edge_tables,omitempty"`
	Labels               []*SimpleGraphElementLabelProto        `protobuf:"bytes,5,rep,name=labels" json:"labels,omitempty"`
	PropertyDeclarations []*SimpleGraphPropertyDeclarationProto `protobuf:"bytes,6,rep,name=property_declarations,json=propertyDeclarations" json:"property_declarations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SimplePropertyGraphProto) Reset() {
	*x = SimplePropertyGraphProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplePropertyGraphProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePropertyGraphProto) ProtoMessage() {}

func (x *SimplePropertyGraphProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePropertyGraphProto.ProtoReflect.Descriptor instead.
func (*SimplePropertyGraphProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{0}
}

func (x *SimplePropertyGraphProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimplePropertyGraphProto) GetNamePath() []string {
	if x != nil {
		return x.NamePath
	}
	return nil
}

func (x *SimplePropertyGraphProto) GetNodeTables() []*SimpleGraphElementTableProto {
	if x != nil {
		return x.NodeTables
	}
	return nil
}

func (x *SimplePropertyGraphProto) GetEdgeTables() []*SimpleGraphElementTableProto {
	if x != nil {
		return x.EdgeTables
	}
	return nil
}

func (x *SimplePropertyGraphProto) GetLabels() []*SimpleGraphElementLabelProto {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SimplePropertyGraphProto) GetPropertyDeclarations() []*SimpleGraphPropertyDeclarationProto {
	if x != nil {
		return x.PropertyDeclarations
	}
	return nil
}

type SimpleGraphElementTableProto struct {
	state                 protoimpl.MessageState                    `protogen:"open.v1"`
	Name                  *string                                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PropertyGraphNamePath []string                                  `protobuf:"bytes,2,rep,name=property_graph_name_path,json=propertyGraphNamePath" json:"property_graph_name_path,omitempty"`
	Kind                  *SimpleGraphElementTableProto_Kind        `protobuf:"varint,3,opt,name=kind,enum=googlesql.SimpleGraphElementTableProto_Kind" json:"kind,omitempty"`
	InputTableName        *string                                   `protobuf:"bytes,4,opt,name=input_table_name,json=inputTableName" json:"input_table_name,omitempty"`
	KeyColumns            []int32                                   `protobuf:"varint,5,rep,packed,name=key_columns,json=keyColumns" json:"key_columns,omitempty"`
	LabelNames            []string                                  `protobuf:"bytes,6,rep,name=label_names,json=labelNames" json:"label_names,omitempty"`
	PropertyDefinitions   []*SimpleGraphPropertyDefinitionProto     `protobuf:"bytes,7,rep,name=property_definitions,json=propertyDefinitions" json:"property_definitions,omitempty"`
	SourceNodeTable       *SimpleGraphNodeTableReferenceProto       `protobuf:"bytes,8,opt,name=source_node_table,json=sourceNodeTable" json:"source_node_table,omitempty"`
	DestNodeTable         *SimpleGraphNodeTableReferenceProto       `protobuf:"bytes,9,opt,name=dest_node_table,json=destNodeTable" json:"dest_node_table,omitempty"`
	DynamicProperties     *SimpleGraphElementDynamicPropertiesProto `protobuf:"bytes,10,opt,name=dynamic_properties,json=dynamicProperties" json:"dynamic_properties,omitempty"`
	DynamicLabel          *SimpleGraphElementDynamicLabelProto      `protobuf:"bytes,11,opt,name=dynamic_label,json=dynamicLabel" json:"dynamic_label,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SimpleGraphElementTableProto) Reset() {
	*x = SimpleGraphElementTableProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphElementTableProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphElementTableProto) ProtoMessage() {}

func (x *SimpleGraphElementTableProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphElementTableProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphElementTableProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleGraphElementTableProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimpleGraphElementTableProto) GetPropertyGraphNamePath() []string {
	if x != nil {
		return x.PropertyGraphNamePath
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetKind() SimpleGraphElementTableProto_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return SimpleGraphElementTableProto_KIND_UNSPECIFIED
}

func (x *SimpleGraphElementTableProto) GetInputTableName() string {
	if x != nil && x.InputTableName != nil {
		return *x.InputTableName
	}
	return ""
}

func (x *SimpleGraphElementTableProto) GetKeyColumns() []int32 {
	if x != nil {
		return x.KeyColumns
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetLabelNames() []string {
	if x != nil {
		return x.LabelNames
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetPropertyDefinitions() []*SimpleGraphPropertyDefinitionProto {
	if x != nil {
		return x.PropertyDefinitions
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetSourceNodeTable() *SimpleGraphNodeTableReferenceProto {
	if x != nil {
		return x.SourceNodeTable
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetDestNodeTable() *SimpleGraphNodeTableReferenceProto {
	if x != nil {
		return x.DestNodeTable
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetDynamicProperties() *SimpleGraphElementDynamicPropertiesProto {
	if x != nil {
		return x.DynamicProperties
	}
	return nil
}

func (x *SimpleGraphElementTableProto) GetDynamicLabel() *SimpleGraphElementDynamicLabelProto {
	if x != nil {
		return x.DynamicLabel
	}
	return nil
}

type SimpleGraphElementLabelProto struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PropertyGraphNamePath    []string               `protobuf:"bytes,2,rep,name=property_graph_name_path,json=propertyGraphNamePath" json:"property_graph_name_path,omitempty"`
	PropertyDeclarationNames []string               `protobuf:"bytes,3,rep,name=property_declaration_names,json=propertyDeclarationNames" json:"property_declaration_names,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SimpleGraphElementLabelProto) Reset() {
	*x = SimpleGraphElementLabelProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphElementLabelProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphElementLabelProto) ProtoMessage() {}

func (x *SimpleGraphElementLabelProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphElementLabelProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphElementLabelProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleGraphElementLabelProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimpleGraphElementLabelProto) GetPropertyGraphNamePath() []string {
	if x != nil {
		return x.PropertyGraphNamePath
	}
	return nil
}

func (x *SimpleGraphElementLabelProto) GetPropertyDeclarationNames() []string {
	if x != nil {
		return x.PropertyDeclarationNames
	}
	return nil
}

type SimpleGraphNodeTableReferenceProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeTableName    *string                `protobuf:"bytes,1,opt,name=node_table_name,json=nodeTableName" json:"node_table_name,omitempty"`
	EdgeTableColumns []int32                `protobuf:"varint,2,rep,packed,name=edge_table_columns,json=edgeTableColumns" json:"edge_table_columns,omitempty"`
	NodeTableColumns []int32                `protobuf:"varint,3,rep,packed,name=node_table_columns,json=nodeTableColumns" json:"node_table_columns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SimpleGraphNodeTableReferenceProto) Reset() {
	*x = SimpleGraphNodeTableReferenceProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphNodeTableReferenceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphNodeTableReferenceProto) ProtoMessage() {}

func (x *SimpleGraphNodeTableReferenceProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphNodeTableReferenceProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphNodeTableReferenceProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleGraphNodeTableReferenceProto) GetNodeTableName() string {
	if x != nil && x.NodeTableName != nil {
		return *x.NodeTableName
	}
	return ""
}

func (x *SimpleGraphNodeTableReferenceProto) GetEdgeTableColumns() []int32 {
	if x != nil {
		return x.EdgeTableColumns
	}
	return nil
}

func (x *SimpleGraphNodeTableReferenceProto) GetNodeTableColumns() []int32 {
	if x != nil {
		return x.NodeTableColumns
	}
	return nil
}

type SimpleGraphPropertyDeclarationProto struct {
	state                 protoimpl.MessageState                    `protogen:"open.v1"`
	Name                  *string                                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PropertyGraphNamePath []string                                  `protobuf:"bytes,2,rep,name=property_graph_name_path,json=propertyGraphNamePath" json:"property_graph_name_path,omitempty"`
	Type                  *googlesql_public.TypeProto               `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	AnnotationMap         *googlesql_public.AnnotationMapProto      `protobuf:"bytes,4,opt,name=annotation_map,json=annotationMap" json:"annotation_map,omitempty"`
	Kind                  *SimpleGraphPropertyDeclarationProto_Kind `protobuf:"varint,5,opt,name=kind,enum=googlesql.SimpleGraphPropertyDeclarationProto_Kind" json:"kind,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SimpleGraphPropertyDeclarationProto) Reset() {
	*x = SimpleGraphPropertyDeclarationProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphPropertyDeclarationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphPropertyDeclarationProto) ProtoMessage() {}

func (x *SimpleGraphPropertyDeclarationProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphPropertyDeclarationProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphPropertyDeclarationProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{4}
}

func (x *SimpleGraphPropertyDeclarationProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SimpleGraphPropertyDeclarationProto) GetPropertyGraphNamePath() []string {
	if x != nil {
		return x.PropertyGraphNamePath
	}
	return nil
}

func (x *SimpleGraphPropertyDeclarationProto) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SimpleGraphPropertyDeclarationProto) GetAnnotationMap() *googlesql_public.AnnotationMapProto {
	if x != nil {
		return x.AnnotationMap
	}
	return nil
}

func (x *SimpleGraphPropertyDeclarationProto) GetKind() SimpleGraphPropertyDeclarationProto_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return SimpleGraphPropertyDeclarationProto_KIND_UNSPECIFIED
}

type SimpleGraphPropertyDefinitionProto struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PropertyDeclarationName *string                `protobuf:"bytes,1,opt,name=property_declaration_name,json=propertyDeclarationName" json:"property_declaration_name,omitempty"`
	ValueExpressionSql      *string                `protobuf:"bytes,2,opt,name=value_expression_sql,json=valueExpressionSql" json:"value_expression_sql,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SimpleGraphPropertyDefinitionProto) Reset() {
	*x = SimpleGraphPropertyDefinitionProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphPropertyDefinitionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphPropertyDefinitionProto) ProtoMessage() {}

func (x *SimpleGraphPropertyDefinitionProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphPropertyDefinitionProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphPropertyDefinitionProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{5}
}

func (x *SimpleGraphPropertyDefinitionProto) GetPropertyDeclarationName() string {
	if x != nil && x.PropertyDeclarationName != nil {
		return *x.PropertyDeclarationName
	}
	return ""
}

func (x *SimpleGraphPropertyDefinitionProto) GetValueExpressionSql() string {
	if x != nil && x.ValueExpressionSql != nil {
		return *x.ValueExpressionSql
	}
	return ""
}

type SimpleGraphElementDynamicPropertiesProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PropertiesExpression *string                `protobuf:"bytes,1,opt,name=properties_expression,json=propertiesExpression" json:"properties_expression,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SimpleGraphElementDynamicPropertiesProto) Reset() {
	*x = SimpleGraphElementDynamicPropertiesProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphElementDynamicPropertiesProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphElementDynamicPropertiesProto) ProtoMessage() {}

func (x *SimpleGraphElementDynamicPropertiesProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphElementDynamicPropertiesProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphElementDynamicPropertiesProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{6}
}

func (x *SimpleGraphElementDynamicPropertiesProto) GetPropertiesExpression() string {
	if x != nil && x.PropertiesExpression != nil {
		return *x.PropertiesExpression
	}
	return ""
}

type SimpleGraphElementDynamicLabelProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LabelExpression *string                `protobuf:"bytes,1,opt,name=label_expression,json=labelExpression" json:"label_expression,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimpleGraphElementDynamicLabelProto) Reset() {
	*x = SimpleGraphElementDynamicLabelProto{}
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleGraphElementDynamicLabelProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleGraphElementDynamicLabelProto) ProtoMessage() {}

func (x *SimpleGraphElementDynamicLabelProto) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_proto_simple_property_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleGraphElementDynamicLabelProto.ProtoReflect.Descriptor instead.
func (*SimpleGraphElementDynamicLabelProto) Descriptor() ([]byte, []int) {
	return file_googlesql_proto_simple_property_graph_proto_rawDescGZIP(), []int{7}
}

func (x *SimpleGraphElementDynamicLabelProto) GetLabelExpression() string {
	if x != nil && x.LabelExpression != nil {
		return *x.LabelExpression
	}
	return ""
}

var File_googlesql_proto_simple_property_graph_proto protoreflect.FileDescriptor

const file_googlesql_proto_simple_property_graph_proto_rawDesc = "" +
	"\n" +
	"+googlesql/proto/simple_property_graph.proto\x12\tgooglesql\x1a!googlesql/public/annotation.proto\x1a\x1bgooglesql/public/type.proto\"\x85\x03\n" +
	"\x18SimplePropertyGraphProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tname_path\x18\x02 \x03(\tR\bnamePath\x12H\n" +
	"\vnode_tables\x18\x03 \x03(\v2'.googlesql.SimpleGraphElementTableProtoR\n" +
	"nodeTables\x12H\n" +
	"\vedge_tables\x18\x04 \x03(\v2'.googlesql.SimpleGraphElementTableProtoR\n" +
	"edgeTables\x12?\n" +
	"\x06labels\x18\x05 \x03(\v2'.googlesql.SimpleGraphElementLabelProtoR\x06labels\x12c\n" +
	"\x15property_declarations\x18\x06 \x03(\v2..googlesql.SimpleGraphPropertyDeclarationProtoR\x14propertyDeclarations\"\x9c\x06\n" +
	"\x1cSimpleGraphElementTableProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x18property_graph_name_path\x18\x02 \x03(\tR\x15propertyGraphNamePath\x12@\n" +
	"\x04kind\x18\x03 \x01(\x0e2,.googlesql.SimpleGraphElementTableProto.KindR\x04kind\x12(\n" +
	"\x10input_table_name\x18\x04 \x01(\tR\x0einputTableName\x12#\n" +
	"\vkey_columns\x18\x05 \x03(\x05B\x02\x10\x01R\n" +
	"keyColumns\x12\x1f\n" +
	"\vlabel_names\x18\x06 \x03(\tR\n" +
	"labelNames\x12`\n" +
	"\x14property_definitions\x18\a \x03(\v2-.googlesql.SimpleGraphPropertyDefinitionProtoR\x13propertyDefinitions\x12Y\n" +
	"\x11source_node_table\x18\b \x01(\v2-.googlesql.SimpleGraphNodeTableReferenceProtoR\x0fsourceNodeTable\x12U\n" +
	"\x0fdest_node_table\x18\t \x01(\v2-.googlesql.SimpleGraphNodeTableReferenceProtoR\rdestNodeTable\x12b\n" +
	"\x12dynamic_properties\x18\n" +
	" \x01(\v23.googlesql.SimpleGraphElementDynamicPropertiesProtoR\x11dynamicProperties\x12S\n" +
	"\rdynamic_label\x18\v \x01(\v2..googlesql.SimpleGraphElementDynamicLabelProtoR\fdynamicLabel\"0\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NODE\x10\x01\x12\b\n" +
	"\x04EDGE\x10\x02\"\xa9\x01\n" +
	"\x1cSimpleGraphElementLabelProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x18property_graph_name_path\x18\x02 \x03(\tR\x15propertyGraphNamePath\x12<\n" +
	"\x1aproperty_declaration_names\x18\x03 \x03(\tR\x18propertyDeclarationNames\"\xb0\x01\n" +
	"\"SimpleGraphNodeTableReferenceProto\x12&\n" +
	"\x0fnode_table_name\x18\x01 \x01(\tR\rnodeTableName\x120\n" +
	"\x12edge_table_columns\x18\x02 \x03(\x05B\x02\x10\x01R\x10edgeTableColumns\x120\n" +
	"\x12node_table_columns\x18\x03 \x03(\x05B\x02\x10\x01R\x10nodeTableColumns\"\xe2\x02\n" +
	"#SimpleGraphPropertyDeclarationProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x18property_graph_name_path\x18\x02 \x03(\tR\x15propertyGraphNamePath\x12(\n" +
	"\x04type\x18\x03 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x12D\n" +
	"\x0eannotation_map\x18\x04 \x01(\v2\x1d.googlesql.AnnotationMapProtoR\rannotationMap\x12G\n" +
	"\x04kind\x18\x05 \x01(\x0e23.googlesql.SimpleGraphPropertyDeclarationProto.KindR\x04kind\"5\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SCALAR\x10\x01\x12\v\n" +
	"\aMEASURE\x10\x02\"\x92\x01\n" +
	"\"SimpleGraphPropertyDefinitionProto\x12:\n" +
	"\x19property_declaration_name\x18\x01 \x01(\tR\x17propertyDeclarationName\x120\n" +
	"\x14value_expression_sql\x18\x02 \x01(\tR\x12valueExpressionSql\"_\n" +
	"(SimpleGraphElementDynamicPropertiesProto\x123\n" +
	"\x15properties_expression\x18\x01 \x01(\tR\x14propertiesExpression\"P\n" +
	"#SimpleGraphElementDynamicLabelProto\x12)\n" +
	"\x10label_expression\x18\x01 \x01(\tR\x0flabelExpressionB1\n" +
	"\x14com.google.googlesqlB\x19SimplePropertyGraphProtos"

var (
	file_googlesql_proto_simple_property_graph_proto_rawDescOnce sync.Once
	file_googlesql_proto_simple_property_graph_proto_rawDescData []byte
)

func file_googlesql_proto_simple_property_graph_proto_rawDescGZIP() []byte {
	file_googlesql_proto_simple_property_graph_proto_rawDescOnce.Do(func() {
		file_googlesql_proto_simple_property_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_proto_simple_property_graph_proto_rawDesc), len(file_googlesql_proto_simple_property_graph_proto_rawDesc)))
	})
	return file_googlesql_proto_simple_property_graph_proto_rawDescData
}

var file_googlesql_proto_simple_property_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_googlesql_proto_simple_property_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_googlesql_proto_simple_property_graph_proto_goTypes = []any{
	(SimpleGraphElementTableProto_Kind)(0),           // 0: googlesql.SimpleGraphElementTableProto.Kind
	(SimpleGraphPropertyDeclarationProto_Kind)(0),    // 1: googlesql.SimpleGraphPropertyDeclarationProto.Kind
	(*SimplePropertyGraphProto)(nil),                 // 2: googlesql.SimplePropertyGraphProto
	(*SimpleGraphElementTableProto)(nil),             // 3: googlesql.SimpleGraphElementTableProto
	(*SimpleGraphElementLabelProto)(nil),             // 4: googlesql.SimpleGraphElementLabelProto
	(*SimpleGraphNodeTableReferenceProto)(nil),       // 5: googlesql.SimpleGraphNodeTableReferenceProto
	(*SimpleGraphPropertyDeclarationProto)(nil),      // 6: googlesql.SimpleGraphPropertyDeclarationProto
	(*SimpleGraphPropertyDefinitionProto)(nil),       // 7: googlesql.SimpleGraphPropertyDefinitionProto
	(*SimpleGraphElementDynamicPropertiesProto)(nil), // 8: googlesql.SimpleGraphElementDynamicPropertiesProto
	(*SimpleGraphElementDynamicLabelProto)(nil),      // 9: googlesql.SimpleGraphElementDynamicLabelProto
	(*googlesql_public.TypeProto)(nil),               // 10: googlesql.TypeProto
	(*googlesql_public.AnnotationMapProto)(nil),      // 11: googlesql.AnnotationMapProto
}
var file_googlesql_proto_simple_property_graph_proto_depIdxs = []int32{
	3,  // 0: googlesql.SimplePropertyGraphProto.node_tables:type_name -> googlesql.SimpleGraphElementTableProto
	3,  // 1: googlesql.SimplePropertyGraphProto.edge_tables:type_name -> googlesql.SimpleGraphElementTableProto
	4,  // 2: googlesql.SimplePropertyGraphProto.labels:type_name -> googlesql.SimpleGraphElementLabelProto
	6,  // 3: googlesql.SimplePropertyGraphProto.property_declarations:type_name -> googlesql.SimpleGraphPropertyDeclarationProto
	0,  // 4: googlesql.SimpleGraphElementTableProto.kind:type_name -> googlesql.SimpleGraphElementTableProto.Kind
	7,  // 5: googlesql.SimpleGraphElementTableProto.property_definitions:type_name -> googlesql.SimpleGraphPropertyDefinitionProto
	5,  // 6: googlesql.SimpleGraphElementTableProto.source_node_table:type_name -> googlesql.SimpleGraphNodeTableReferenceProto
	5,  // 7: googlesql.SimpleGraphElementTableProto.dest_node_table:type_name -> googlesql.SimpleGraphNodeTableReferenceProto
	8,  // 8: googlesql.SimpleGraphElementTableProto.dynamic_properties:type_name -> googlesql.SimpleGraphElementDynamicPropertiesProto
	9,  // 9: googlesql.SimpleGraphElementTableProto.dynamic_label:type_name -> googlesql.SimpleGraphElementDynamicLabelProto
	10, // 10: googlesql.SimpleGraphPropertyDeclarationProto.type:type_name -> googlesql.TypeProto
	11, // 11: googlesql.SimpleGraphPropertyDeclarationProto.annotation_map:type_name -> googlesql.AnnotationMapProto
	1,  // 12: googlesql.SimpleGraphPropertyDeclarationProto.kind:type_name -> googlesql.SimpleGraphPropertyDeclarationProto.Kind
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_googlesql_proto_simple_property_graph_proto_init() }
func file_googlesql_proto_simple_property_graph_proto_init() {
	if File_googlesql_proto_simple_property_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_proto_simple_property_graph_proto_rawDesc), len(file_googlesql_proto_simple_property_graph_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_proto_simple_property_graph_proto_goTypes,
		DependencyIndexes: file_googlesql_proto_simple_property_graph_proto_depIdxs,
		EnumInfos:         file_googlesql_proto_simple_property_graph_proto_enumTypes,
		MessageInfos:      file_googlesql_proto_simple_property_graph_proto_msgTypes,
	}.Build()
	File_googlesql_proto_simple_property_graph_proto = out.File
	file_googlesql_proto_simple_property_graph_proto_goTypes = nil
	file_googlesql_proto_simple_property_graph_proto_depIdxs = nil
}
