//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: googlesql/scripting/variable.proto

package googlesql_scripting

import (
	googlesql_public "github.com/slokam-ai/localbq/internal/googlesql/pb/googlesql_public"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next id: 5
type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the variable.  All variables must have distinct names using
	// case-insensitive matching.  For purposes of error messages, the names of
	// variables stored here should match the case with which the variables were
	// declared.
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The type of the variable
	Type *googlesql_public.TypeProto `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// The current value of the variable.
	Value *googlesql_public.ValueProto `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	// The type parameters of the variable.
	TypeParams    *googlesql_public.TypeParametersProto `protobuf:"bytes,4,opt,name=type_params,json=typeParams" json:"type_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_googlesql_scripting_variable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_googlesql_scripting_variable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_googlesql_scripting_variable_proto_rawDescGZIP(), []int{0}
}

func (x *Variable) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Variable) GetType() *googlesql_public.TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Variable) GetValue() *googlesql_public.ValueProto {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Variable) GetTypeParams() *googlesql_public.TypeParametersProto {
	if x != nil {
		return x.TypeParams
	}
	return nil
}

var File_googlesql_scripting_variable_proto protoreflect.FileDescriptor

const file_googlesql_scripting_variable_proto_rawDesc = "" +
	"\n" +
	"\"googlesql/scripting/variable.proto\x12\tgooglesql\x1a\x1bgooglesql/public/type.proto\x1a&googlesql/public/type_parameters.proto\x1a\x1cgooglesql/public/value.proto\"\xb6\x01\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\v2\x14.googlesql.TypeProtoR\x04type\x12+\n" +
	"\x05value\x18\x03 \x01(\v2\x15.googlesql.ValueProtoR\x05value\x12?\n" +
	"\vtype_params\x18\x04 \x01(\v2\x1e.googlesql.TypeParametersProtoR\n" +
	"typeParamsB)\n" +
	"\x14com.google.googlesqlB\x11GoogleSQLVariable"

var (
	file_googlesql_scripting_variable_proto_rawDescOnce sync.Once
	file_googlesql_scripting_variable_proto_rawDescData []byte
)

func file_googlesql_scripting_variable_proto_rawDescGZIP() []byte {
	file_googlesql_scripting_variable_proto_rawDescOnce.Do(func() {
		file_googlesql_scripting_variable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_googlesql_scripting_variable_proto_rawDesc), len(file_googlesql_scripting_variable_proto_rawDesc)))
	})
	return file_googlesql_scripting_variable_proto_rawDescData
}

var file_googlesql_scripting_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_googlesql_scripting_variable_proto_goTypes = []any{
	(*Variable)(nil),                             // 0: googlesql.Variable
	(*googlesql_public.TypeProto)(nil),           // 1: googlesql.TypeProto
	(*googlesql_public.ValueProto)(nil),          // 2: googlesql.ValueProto
	(*googlesql_public.TypeParametersProto)(nil), // 3: googlesql.TypeParametersProto
}
var file_googlesql_scripting_variable_proto_depIdxs = []int32{
	1, // 0: googlesql.Variable.type:type_name -> googlesql.TypeProto
	2, // 1: googlesql.Variable.value:type_name -> googlesql.ValueProto
	3, // 2: googlesql.Variable.type_params:type_name -> googlesql.TypeParametersProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_googlesql_scripting_variable_proto_init() }
func file_googlesql_scripting_variable_proto_init() {
	if File_googlesql_scripting_variable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_googlesql_scripting_variable_proto_rawDesc), len(file_googlesql_scripting_variable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_googlesql_scripting_variable_proto_goTypes,
		DependencyIndexes: file_googlesql_scripting_variable_proto_depIdxs,
		MessageInfos:      file_googlesql_scripting_variable_proto_msgTypes,
	}.Build()
	File_googlesql_scripting_variable_proto = out.File
	file_googlesql_scripting_variable_proto_goTypes = nil
	file_googlesql_scripting_variable_proto_depIdxs = nil
}
